ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping.field.action.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping.field.detail.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/transition.selection.component.ts
Adds element id's for source/target, index inputs, and action,separator selects. 
closes #92
=> (atlas-ui) Add element id's for inputs and selects in mapping details

parent/pom.xml, runtime/runtime/pom.xml, ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
Fixes: #180
chore: Reduce surefire fork count, expecting to avoid recent VM termination in CircleCI
=> chore: Add twitter4j.Status as a mock Source Document

ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping.field.action.component.ts
"Class" attribute is used instead of "id" due to possibility to get non-unique id values ( combine/separate index input). This helps QE to easily manipulate with inputs in automated tests.
=> fix: wrong id's on field actions input string

ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping.field.action.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts
fix: Missing 'Add Transformation' button for certain field types.
Fixes: #225, #107
Signed-off-by: Paul Leacu <pleacu@redhat.com>
Test PR until reviewed
Hey - since this is my first crack at AtlasMap the more eyes on this the better!
The inital issue was that the 'Add Transformation' button wasn't showing up for some field types.
The MappingFieldActionComponent class has a method to return an array of applicable field actions
for the selected field pair types.  It walks all of the field actions as defined in the TransitionModel
and allows it to determine if we should add the field action to the array.  A non-zero array triggers
the 'Add Transformation' button.
The issue is with the FieldActionConfig class/ appliesToField method in the transition model.
It's basically only set up to work …
=> i225 - test PR - fix add transformation button for some types

ui/src/app/lib/atlasmap-data-mapper/components/document.definition.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/document.field.detail.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/field.edit.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/document.definition.model.spec.ts, ui/src/app/lib/atlasmap-data-mapper/models/document.definition.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/field.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/mapping.definition.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/document.management.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping.serializer.ts
Introduced a `DocumentInitializationModel` which is a subset of `DocumentDefinition`
```TypeScript
export class DocumentInitializationModel {
public id: string; // Document ID. Syndesis would put Step UUID.
public type: DocumentType;
public shortName: string; // Document label. Syndesis would put "Salesforce Contact (Step 1)" here
public fullName: string; // Shown as a tooltip. Put a longer description for the document
public isSource: boolean;
public inspectionType: InspectionType;
public inspectionSource: string;
public inspectionResult: string;
}
```
and let `ConfigModel` accept it via
```TypeScript
addDocument(docInitModel: DocumentInitializationModel): DocumentDefinition
```
and
```TypeScript
addDocuments(docModels: DocumentInitializationModel[]): DocumentDefinition[]
``` 
Also
fix: …
=> fix: Refactor Document initialization model (#242)

ui/package.json, ui/yarn.lock
This is required for ensuring that both Syndesis and Atlasmap share the same `patternfly-ng` version and then the underlying dependency on `angular-tree-component` and then on `mobx-angular` will not break the new Syndesis Angular 5 build.
=> chore: core dependencies shared with Syndesis upgraded

ui/.angular-cli.json, ui/package.json, ui/yarn.lock
This PR aligns patternfly-ng and ngx-bootstrap dependency versions with that of syndesis-ui. @igarashitm please test drive this as I'm having issues linking this with my local syndesis ui. The changes are straight forward so I don't anticipate any issues, but if you find any obviously just let me know. Thx!
update deps to align with what syndesis-ui
include patternfly-ng stylesheet
remove bootstrap stylesheet as those styles are already fulfilled by patternfly core
=> fix(deps): upgrade patternfly-ng and ngx-bootstrap

runtime/modules/xml/model/src/main/resources/atlas-xml-schemaset-model-v2.xsd
This makes AdditionalSchemas optional, to allow for cases where there aren't any additional schemas.
=> refactor(xml): Make AdditionalSchemas optional

runtime/modules/xml/core/src/main/java/io/atlasmap/xml/inspect/SchemaInspector.java, runtime/modules/xml/core/src/test/java/io/atlasmap/xml/inspect/XmlSchemaInspectionMultipleNamespacesTest.java
Setting targetNamespace to the target document prevents handling sub-schema which doesn't have target namespace (i.e. mapped to default namespace "")
Should help #290 but might need also a UI fix
=> fix: Don't set isTargetNamespace to true

camel/pom.xml, camel/src/test/java/org/apache/camel/component/atlasmap/AtlasMapMultiNSTest.java, camel/src/test/resources/atlasmapping-multins.xml, camel/src/test/resources/org/apache/camel/component/atlasmap/AtlasMapMultiNSTest-context.xml, ui/src/app/lib/atlasmap-data-mapper/models/field.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/document.management.service.ts
Fixes: #290 
Bug fix is just this one line change. No idea why it was looking at `this.docDef` at first place.
https://github.com/atlasmap/atlasmap/compare/master...igarashitm:290-ui?expand=1#diff-32bc31d431be77cf4e612663bb4cccee
Also added a mock XML schema doc in UI and a test case for camel-atlasmap.
=> fix: UI is missing namespace prefix in XML field path

runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasFieldActionsServiceTest.java, runtime/model/src/main/resources/atlas-model-v2.xsd, ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Partially addresses #386
Now FieldActionArgument.values can be used to show possible values
=> fix: Deliver possible values for enum field action parameters

ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action.component.ts
Fixes: #420 
I've gone through each transformation text input parameter and corrected an issue with the field action parameter processing function. It was following a pull-down path when it shouldn't.  Hopefully this is the last of these...
=> fix: Correct action field parameter input text field processing

runtime/runtime/src/main/resources/license-custom-assembly.xml
For the rest of the syndesis projects we are copying the ipaas licenses to /opt/ipaas/licenses.
=> Change the directory we are copying the ipaas licenses to.

runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java, runtime/itests/core/src/test/java/io/atlasmap/core/DefaultAtlasContextCollectionExpansionTest.java, runtime/modules/json/module/src/main/java/io/atlasmap/json/module/JsonModule.java
`DefaultAtlasContext::extractCollectionMappings` has the a side effect
of modifying the mapping, thus for already expanded collection mappings
it expands again and replaces the mapping.
For example, given source document of:
```json
{ "array":
[
{ "property": 1 },
{ "property": 2 },
{ "property": 3 }
]
}
```
And mapping containing a JSON field with path like `/array<>/property`.
First invocation modifies the mapping to contain three mappings:
1. `/array<0>/property`
2. `/array<2>/property`
3. `/array<3>/property`
Since this is now replacing the previous mapping on the next invocation
this expands to:
1. `/array<0>/property`
2. `/array<1>/property`
3. `/array<2>/property`
...
9. `/array<8>/property`
This removes the mapping mutation side effect, though I'm not entirely
sure why it was …
=>  fix: don't allocate memory exponentially in collection mappings

runtime/core/src/main/java/io/atlasmap/actions/StringComplexFieldActions.java, runtime/core/src/test/java/io/atlasmap/actions/StringComplexFieldActionsTest.java, runtime/model/src/main/java/io/atlasmap/v2/ActionsJsonDeserializer.java, runtime/model/src/main/java/io/atlasmap/v2/ActionsJsonSerializer.java, runtime/model/src/main/resources/atlas-actions-v2.xsd
Fixes: #549 
We already have `Concatenate` doing same with `COMBINE`. Since there're some `separate*` FieldAction already which does something different, added `Split` as an alternative to `SEPARATE`.
=> feat: Add Split FieldAction

camel/src/test/java/org/apache/camel/component/atlasmap/AtlasMapComponentTest.java, camel/src/test/resources/atlasmapping.xml, ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
Fixes: #544
(cherry picked from commit ee074f8805f5f67df8332fd532c4f22e73db96ef)
@igarashitm I think this is a good fix to backport, can you take a look?
=> fix: Constants value is not saved into mapping definition

ui/src/app/atlasmap-navbar.component.html, ui/src/app/lib/atlasmap-data-mapper/services/document-management.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Fixes: #591 
Also catch valid schemas that don't specify any elements
=> fix: Handle non-ascii unicode characters in schemas/ instance schemas.

docs/src/main/asciidoc/inc/swagger/core/definitions.adoc, runtime/api/src/main/java/io/atlasmap/spi/AtlasModule.java, runtime/core/src/main/java/io/atlasmap/core/BaseAtlasModule.java, runtime/core/src/main/java/io/atlasmap/core/ConstantModule.java, runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java, runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, runtime/core/src/main/java/io/atlasmap/core/PropertyModule.java, runtime/core/src/test/java/io/atlasmap/core/BaseDefaultAtlasContextTest.java, runtime/core/src/test/java/io/atlasmap/core/ConstantModuleTest.java, runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasContextFactoryTest.java, runtime/core/src/test/java/io/atlasmap/core/PropertyModuleTest.java, runtime/itests/core/src/test/java/io/atlasmap/core/ConcatenateSplitTest.java, runtime/itests/core/src/test/java/io/atlasmap/core/issue/CollectionComplexTest.java, runtime/itests/core/src/test/resources/mappings/atlasmapping-concatenate-split.xml, runtime/itests/core/src/test/resources/mappings/issue/collection-complex-mapping.xml, runtime/model/src/main/resources/atlas-model-v2.xjb, runtime/model/src/main/resources/atlas-model-v2.xsd, runtime/modules/java/core/src/main/java/io/atlasmap/java/core/DocumentJavaFieldWriter.java, runtime/modules/java/core/src/main/java/io/atlasmap/java/core/TargetValueConverter.java, runtime/modules/java/core/src/test/java/io/atlasmap/java/core/BaseDocumentWriterTest.java, runtime/modules/java/module/src/main/java/io/atlasmap/java/module/JavaModule.java, runtime/modules/json/module/src/main/java/io/atlasmap/json/module/JsonModule.java, runtime/modules/xml/module/src/main/java/io/atlasmap/xml/module/XmlModule.java
Fixes: #550
This allows transformations to change multiplicity, which is supposed to replace `COMBINE`/`SEPARATE` mode eventually. UI needs to add `Concatenate`/`Split` transformation instead of using `COMBINE`/`SEPARATE` mode, and for `Concatenate` case the source fields needs to be wrapped with `FieldGroup`, so that the `Concatenate` transformation is placed on a `FieldGroup` level.
[An example mapping is here](https://github.com/atlasmap/atlasmap/pull/602/files#diff-11b53e171519d064b287692ae917660e)
This also allows transformations like `Add` mentioned in #461, which consumes multiple number fields and sum up. In combination with #338 we can also apply it for collection field.
At this point we don't support to have a collection field as a part of grouping, i.e. put collection field and …
=> feat: Handle FieldGroup contributed via mapping definition

docs/src/main/asciidoc/inc/_internal_design.adoc, docs/src/main/asciidoc/inc/_tips_for_ui_developer.adoc, docs/src/main/asciidoc/inc/internal/_design_time_service.adoc, docs/src/main/asciidoc/inc/internal/_runtime.adoc
Hi team,
I found some broker URL by reading "AtlasMap Developer Guide". I could not find the broker url in https://github.com/atlasmap/atlasmap.io but this repo, so decided to PR here. Could you take a look at it please?
=> Fix the wrong url from runtime to lib

lib/modules/java/core/src/main/java/io/atlasmap/java/inspect/ClassInspectionService.java
For Kudu connector in Syndesis there are protobuf shaded classes referenced from org.apache.kudu.client.KuduTable which use generics.
The code path leads to ParameterizedType describing a Comparable<T> which cannot be cast to a Class.
This is a super simple workaround for this issue, not sure if it's 100% proper. Please ask for refinements, I'm too lazy to create a unit test even though I know I ought to.
=> fix: class cast when inspecting class with generics

lib/core/src/main/java/io/atlasmap/actions/NumberFieldActions.java, lib/core/src/main/java/io/atlasmap/actions/StringComplexFieldActions.java
Unit tests were failing on my machine as I have another default Locale setting.
Failing test:
https://github.com/atlasmap/atlasmap/blob/master/lib/core/src/test/java/io/atlasmap/actions/StringComplexFieldActionsTest.java#L141
Different local setting returns `"1.234,00"` and assertion fails.
I explicitly added root locale to String format in https://github.com/atlasmap/atlasmap/compare/master...christophd:fix/locale-specific-test-failure?expand=1#diff-e8deec4e7a8840412fdb2406fb2a66b5R123 so the Locale specific adjustments are disabled. 
Also fixed some typos ;-)
=> Fix locale specific test failure

docs/src/main/asciidoc/inc/_quickstart.adoc
Update the quick start instruction as README showed.
NOTE: We may also need to updated the section of Running AtlasMap full build as the build.sh is moved.
=> Update the quick start instructions.

ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.ts
Also added support to drag&drop compound fields. This behavior needs a bit more polish, e.g. multiple source fields are already selected and start drag&drop one of them. Then that field is unexpectedly "unselected". We might need to skip the "unselect" action in this case. @pleacu WDYT?
Fixes: #770
=> fix: Allow drag&drop unselected field

ui/pom.xml, ui/yarn.lock
@igarashitm : I'm creating two profiles here - one for normal use (noproxy) and a productization profile that allows us to operate behind the PNC proxy.      
There's one more change here too - I've think I've changed bower-installer to use the binary rather than github - I had issues building atlasmap in prod with github location, but if I changed to the binary, it worked fine.   Can you check that that looks okay?   I don't know angular real well so I don't know if what I did was the right way to do it, but it did seem to work.
=> ENTESB-10411 Merge prod changes back to dev branch

lib/service/src/main/java/io/atlasmap/service/AtlasService.java, ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
Fixes: #887
backend side is working fine, but it converts to new `@type: actionName` style of action description when it serializes it into JSON. So UI had to support it.
=> feat: Add support @type: actionName style of action description in UI

standalone/pom.xml
Relates to #913.
Tweak to the base image used as the original isn't so OpenShift friendly OOTB.
=> fix: Correct base image name to java-jboss-openjdk8-jdk

ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css, ui/src/app/lib/atlasmap-data-mapper/components/expression.component.html, ui/src/app/lib/atlasmap-data-mapper/components/expression.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.html, ui/src/app/lib/atlasmap-data-mapper/data-mapper.module.ts
Submitting a wip PR - it's not yet really functioning, but shows an initial idea of how it will look like.
There're still many things left to do:
1. Restore a cursor
1. Restore highlighting text selection
1. Show field name instead of `$[n}` ref
1. Show field full path as a tooltip
1. Support removing field ref entirely with single `[backspace]` instead of removing just closing bracket
=> feat: [UI] Show short field label in the expression

ui/src/app/lib/atlasmap-data-mapper/components/expression.component.ts
Fixes: #973
Not sure how ngOnChanges() is invoked while ExpressionModel object is not yet initialized, but this prevents the error anyway.
=> fix: Cannot read property 'expressionUpdated$' of undefined

ui/src/app/lib/atlasmap-data-mapper/components/expression.component.ts
Fixes: #994
It's necessary to call validateMappings() within the expression update observer
in the event a text node is added.  Field nodes are ultimately 'fieldSelected()'
so they get validateMappings() that way.
=> fix: Capture trailing text into generated amppings expressions.

ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/simple-mapping.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/transition-selection.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/transition-selection.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
Fixes: #920
Also added FOR_EACH mode to use for collection<->collection mapping. See #918.
There're some more separate/combine words around field action model, but it has to be addressed as a part of #912.
=> fix: Change wording in UI code: Combine>manyToOne and Separate>OneToMany

ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-detail.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/modal-window.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
Fixes: #981
The specific overlap error was corrected with a previous fix.  This is we shouldn't clear out the error window if the user selects 'Cancel' in a dialog, etc.
=> fix: Correct modal reset to not automatically clear errors.

ui/pom.xml, ui/src/app/lib/atlasmap-data-mapper/components/expression.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-container.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-list-field.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/transition-selection.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/document-definition.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/expression.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/field-action.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
fix: [UI] Remove multiplicity transformation from MappedField
ATM Concatenate/Split transformation is hardcoded in serializer, so we only have to maintain delimiter. We'll have to keep the multiplicity transformation in TransitionModel when we address #912
Fixes: #1060
fix: [UI] Disable delimiter and index edit if expression is enabled
Fixes: #1103
fix: [UI] Remove padding field if expression is enabled
Fixes: #1108
fix: [UI] Disable field search input in Mapping Detail pane when inappropriate
Fixes: #1109
fix: [UI] Remove MappedField.index property and just use array index
Fixes: #1110
fix: [UI] Clean up transition&index handling
Fixes: #1111
fix: mapped/transformation icons disappear once transformation is added
Fixes: #1093
=> fix: [UI] Clean up transition&index handling

docs/src/main/asciidoc/user-guide/topics/quickstart.adoc
I noticed a typo in a file that I updated. This just corrects that typo.
=> user doc: Removes an incorrect . from a command line

ui/src/app/lib/atlasmap-data-mapper/components/expression.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-container.component.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Fixes: #1271
Apologies for this one.  The only real difference between the two refactored executeSearch() methods was one needed isSource.
=> fix: Correct bug in refactoring - make isSource a parameter.

ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
Fixes: #1429
Show/hide should simply toggle the mapping details panel - not imply deselection or new mapping creation.
=> fix: Correct show/hide mapping details.

pom.xml
it allows to have the build working in more environment
see for the latest 10.x LTS version https://nodejs.org/en/download/releases/
=> Use newer version of the LTS for Node and NPM

ui-react/packages/atlasmap-ui/src/views/CanvasView/components/CanvasViewControlBar.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/components/CanvasViewToolbar.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldsBox.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Mapping.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Source.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Target.tsx
Options right now look like this (icons picked semi-randomly):
Hopefully [this](https://github.com/patternfly/patternfly-next/issues/2478) will make it easier to read.
=> feat(react-ui): move the options from the view toolbar to the view controlbar

ui-react/package.json, ui-react/packages/atlasmap-standalone/public/index.html, ui-react/packages/atlasmap-standalone/src/App.tsx, ui-react/packages/atlasmap-standalone/src/useConfirmationDialog.tsx, ui-react/packages/atlasmap-ui/src/atlasmap/Atlasmap.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Document.tsx, ui-react/packages/atlasmap-ui/stories/Atlasmap.stories.tsx, ui-react/packages/atlasmap-ui/stories/views/CanvasView/CanvasView.stories.tsx
This adds a `useConfirmationDialog` hook to deal with confirmations in the app. 
It's a hook in the application and not a UI component since modals need to be handled by the host application - when embedded in Syndesis for example there will be Syndesis's way to deal with modals. The same decoupling will have to be implemented when we'll add notifications support.
=> feat(react-ui): confirmation modals

ui-react/packages/atlasmap-provider/src/AtlasmapProvider.tsx, ui-react/packages/atlasmap-provider/src/components/toolbar/toolbar-util.ts, ui-react/packages/atlasmap-provider/src/utils/to-ui-models-util.ts, ui-react/packages/atlasmap-standalone/src/App.tsx, ui-react/packages/atlasmap-ui/src/atlasmap/Atlasmap.tsx, ui-react/packages/atlasmap-ui/src/atlasmap/components/DocumentField.tsx, ui-react/packages/atlasmap-ui/src/atlasmap/components/DocumentFieldPreview.tsx, ui-react/packages/atlasmap-ui/src/atlasmap/components/DocumentFieldPreviewResults.tsx, ui-react/packages/atlasmap-ui/src/atlasmap/components/index.ts, ui-react/packages/atlasmap-ui/stories/Atlasmap.stories.tsx
I also took a stab at the glue layer, but the functional approach used in the UI components is clashing badly with the RXjs state.
We also need to return back to the UI the preview values.
=> feat(react-ui): UI elements to display mapping previews

ui-react/packages/atlasmap-standalone/src/App.tsx, ui-react/packages/atlasmap-standalone/src/useSingleInputDialog.tsx, ui-react/packages/atlasmap-ui/src/atlasmap/Atlasmap.tsx, ui-react/packages/atlasmap-ui/src/atlasmap/components/DocumentField.tsx, ui-react/packages/atlasmap-ui/src/atlasmap/components/DropTarget.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/CanvasView.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/CanvasViewCanvasProvider.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/CanvasViewLayoutProvider.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/CanvasViewOptionsProvider.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/components/CanvasViewControlBar.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Document.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldElement.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldGroup.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldsBox.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Links.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Mapping.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/components/MappingElement.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Source.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Target.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/components/useMappingLinks.ts, ui-react/packages/atlasmap-ui/src/views/CanvasView/components/useSourceTargetLinks.ts, ui-react/packages/atlasmap-ui/stories/Atlasmap.stories.tsx, ui-react/packages/atlasmap-ui/stories/sampleData.tsx, ui-react/packages/atlasmap-ui/stories/views/CanvasView/Document.stories.tsx, ui-react/packages/atlasmap-ui/stories/views/CanvasView/FieldGroup.stories.tsx, ui-react/packages/atlasmap-ui/stories/views/CanvasView/FieldsBox.stories.tsx, ui-react/packages/atlasmap-ui/stories/views/CanvasView/MappingElement.stories.tsx
* with nothing selected, fields can be drag & dropped on any existing mapping (if possible)
* with a mapping selected, fields can still be drag & dropped as before but they'll also show a button to hint that it can be quickly added (with a click) to the selected mapping (if possible)
* with a mapping in editing mode, the mapping column is automatically hidden and d&d is disabled; fields can still be added using the buttons
=> feat(react-ui): improve the add to mapping flow

ui-react/packages/atlasmap-core/src/Atlasmap.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/AtlasmapCanvasViewMappings.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapUIProvider.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/MappingElement.tsx
Fixes: #1742
If you had Mapoping details open and selected another mapping the UI would blow up.  This now keeps mapping details open and matches it to the selected mapping.  If you select the existing mapping while mapping details is open it toggles the selected mapping and closes the mapping details pane.
=> fix: enable toggle mappings when mapping details is open

ui-react/packages/atlasmap-ui/src/Canvas/CanvasTransforms.tsx
Fixes: #1806 
I'm guessing, however, that there might be a more appropriate way to fix this. Based on previous comments, I believe this violates the division between the 'generic' REACT components we've created and the AtlasMap-specific ones. Should I instead place this code in a new AtlasMap component that gets inserted after AtlasmapLayout and before CanvasTransform?
=> fix: UI_REACT: Deselect current mapping when background clicked

.gitignore, README.md, netlify.toml, ui-react/Makefile, ui-react/_netlify_template/index.html, ui-react/package.json, ui-react/packages/atlasmap-core/package.json, ui-react/packages/atlasmap-ui/package.json
This uses Netlify to publish all the storybooks we have in the React UI.
For master, the website will be accessible under https://atlasmap.netlify.com
For PRs, a link to the preview will be pushed by Netlify Bot as a PR comment, but you can also click on the details link in GH PR checks:
Storybooks will not be built under Circle CI anymore, only on Netlify.
=> feat(project): publish storybooks on Netlify

ui-react/packages/atlasmap-core/src/components/field/field-util.ts, ui-react/packages/atlasmap-core/src/react/Atlasmap.tsx, ui-react/packages/atlasmap-core/src/react/AtlasmapProvider.tsx, ui-react/packages/atlasmap-core/src/services/mapping-management.service.ts, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/AtlasmapCanvasView.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapContextToolbar.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapLayout.tsx, ui-react/packages/atlasmap-ui/stories/Atlasmap.stories.tsx
Fixes: #1862 
Note, the empty mapping currently allows no way to assign fields to it, but I will address this in a separate issue.
=> fix: Create 'New Mapping' button

ui-react/packages/atlasmap/src/UI/ColumnMapper/ColumnHeader.tsx, ui-react/packages/atlasmap/src/UI/Document.tsx, ui-react/packages/atlasmap/src/UI/DocumentField.tsx, ui-react/packages/atlasmap/src/UI/DocumentGroup.tsx, ui-react/packages/atlasmap/src/UI/Tree/Tree.stories.mdx, ui-react/packages/atlasmap/src/UI/Tree/TreeGroup.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Columns/ConstantsTree.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Columns/PropertiesTree.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Columns/SourcesColumn.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Columns/TargetsColumn.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Columns/TraverseFields.tsx
Fixes #1963 
This also removes some styling from the `Tree` family of components to delegate it to the specialised `DocumentXXX` components. It isn't strictly related but we needed some way to properly style the empty state and this change sneaked into the PR.
=> fix(react-ui): always show properties and constants

lib/modules/dfdl/core/pom.xml
=> fix: Some atlas-xml-core classes leaking into atlas-dfdl-core

ui/packages/atlasmap/src/UI/dnd/DraggedField.tsx, ui/packages/atlasmap/src/UI/dnd/FieldDropTarget.tsx, ui/packages/atlasmap/src/UI/dnd/FieldsDndProvider.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Columns/MappingsColumn.tsx
The backend used by the DndProvider was the Touch one with support for
mouse events enabled. The Touch backend isn't the best when used on
"pure desktop" environments because of the need to understand if the
user is performing a click or a drag, which introduces some lag.
With this we perform some device capability detection relying on CSS
media query on the `hover` and `pointer` capabilities. This isn't
bulletproof but should make for a better experience than before.
Fixes #2053.
=> fix(ui): make drag & drop quicker

ui/packages/atlasmap-core/src/utils/mapping-serializer.ts, ui/packages/atlasmap-core/src/utils/mapping-util.ts, ui/packages/atlasmap/src/Atlasmap/utils/field.ts
Fixes: #2012
If a constant or property appeared as part of a mapping it became
duplicated.
Business logic fix.
=> fix: Avoid duplication of property/constant fields nodes.

ui/packages/atlasmap/.storybook/webpack.config.js
This gets rid of the warnings when building and running Storybook.
=> chore(ui): load sourcemaps only for our own packages

ui/packages/atlasmap/src/Views/ColumnMapperView/Columns/TraverseFields.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Columns/TreeGroupAndNodeRefsAndDnD.tsx
Also preserve the previously expanded state when ending a drag&drop
interaction.
This fixes loading the FHIR document, and in general improves performance.
=> feat(ui): make tree items lazy

ui/packages/atlasmap/src/UI/useInputTextSelectDialog.tsx
=> fix: When creating a new property, set focus in first field

ui/packages/atlasmap/src/UI/Document.tsx, ui/packages/atlasmap/src/UI/MappingTransformation.tsx, ui/packages/atlasmap/src/UI/Tree/Tree.tsx, ui/packages/atlasmap/src/Views/MappingDetailsView.tsx
This is a workaround 'til the [Notification Drawer](https://patternfly-react.surge.sh/documentation/react/components/notificationdrawer) from the next major release of PatternFly lands.
Ref ENTESB-13740
=> feat(ui): group notifications inside the mapping details

ui/packages/atlasmap-core/src/models/document-definition.model.ts
Fixes ENTESB-13817
This fragment of HTML from the angular UI was not ported to the React UI:
https://github.com/atlasmap/atlasmap/blob/master/__ui-old/src/app/lib/atlasmap-data-mapper/components/document/document-field-detail.component.html#L21
Even in recursive field references you populate the children once with
cached field children.
=> Make sure we populate complex field's children

.circleci/config.yml, pom.xml, ui/packages/atlasmap-core/package.json, ui/packages/atlasmap-standalone/package.json, ui/packages/atlasmap/package.json, ui/pom.xml
=> chore: Collect UI test coverage report and upload to CircleCI

ui/packages/atlasmap/src/UI/MappingField.tsx
=> fix: The delete/transform icons in mapping details page are not aligned

standalone/src/test/java/io/atlasmap/standalone/E2ETest.java, ui/packages/atlasmap/src/Atlasmap/Atlasmap.stories.tsx, ui/packages/atlasmap/src/Atlasmap/Atlasmap.tsx, ui/packages/atlasmap/src/Atlasmap/toolbarItems.tsx, ui/packages/atlasmap/src/Atlasmap/useContextToolbar.tsx, ui/packages/atlasmap/src/Layout/MainLayout.tsx, ui/packages/atlasmap/src/UI/ConditionalExpressionInput.tsx, ui/packages/atlasmap/src/UI/ExpressionContent.stories.tsx, ui/packages/atlasmap/src/UI/ExpressionContent.tsx
Toolbars background is now white, fixes #2122
The main actions (import, export, reset)  are now grouped in a menu,
fixes #2123.
The "Import catalog" doesn't allow for jar files, a new "Import Java archive" voice has been added to do that, fixes ##2110.
Align the conditional expression control to PatternFly guidelines, fixes
#2124.
=> fix(ui): address UXD feedback for toolbars

lib/core/src/main/java/io/atlasmap/core/ADMArchiveHandler.java, lib/model/src/main/java/io/atlasmap/v2/ActionListUpgradeDeserializer.java, lib/model/src/main/java/io/atlasmap/v2/ActionResolver.java, lib/model/src/main/java/io/atlasmap/v2/AtlasHandlerInstantiator.java, lib/model/src/main/java/io/atlasmap/v2/Json.java, lib/model/src/main/java/io/atlasmap/v2/SimpleResolver.java, lib/service/src/main/java/io/atlasmap/service/AtlasService.java, lib/service/src/test/java/io/atlasmap/service/AtlasServiceTest.java, lib/service/src/test/resources/mappings/atlasmapping-custom-action.json, ui/packages/atlasmap-core/src/utils/mapping-serializer.ts
Fixes: #1757
I guess this was caused by the jackson upgrade, it seems the class loader used for custom TypeIdResolver has been changed. But haven't nailed it down to the specific spot. Anyway this change solves the problem.
=> fix: Custom action causes mapping definition deserialization error

lib/modules/java/module/src/main/java/io/atlasmap/java/module/JavaValidationService.java
Use java.class.version System property to parse major Java version of the current VM. Remove usage of a known Java versions map in order to support all Java versions out there.
java.class.version gives us the major Java version (e.g. 52.0, 53.0, 54.0, ...)
Fixes #2260
=> fix(#2260): Fix service to support Java versions beyond Java 9

ui/packages/atlasmap-core/src/utils/mapping-serializer.ts, ui/packages/atlasmap-core/src/utils/mapping-util.ts, ui/packages/atlasmap/src/Atlasmap/useSidebar.tsx
- Correct sidebar addable sources/ targets
- Correct mapped field processing to ignore property value
- Correct property path to include '/'
Fixes: #2327
Fixes: #2330
Fixes: #2334
=> fix: Correct target props handling:

ui/packages/atlasmap/src/UI/Canvas/NodeRefProvider.tsx
Fixes: #2333
Wasn't able to reproduce but from call stack this should correct the issue.
=> fix: Avoid undefined reference when calling unsetRef on reset command.

ui/packages/atlasmap/src/Atlasmap/utils/field.ts, ui/packages/atlasmap/src/Views/ColumnMapperView/Columns/TreeItemFieldAndNodeRefsAndDnD.tsx
Fixes: #2348
Since the name and path are identical, use the decorated (with scope) name as the property name internally.
=> fix: Handle multiple properties with the same name.

.circleci/config.yml, parent/pom.xml, release.sh, standalone/pom.xml
Fixes: #2369
Fixes: #2368
Using eclipse/jkube with Jib strategy, docker image build&push no longer requires local docker daemon instance.
=> fix: Remove docker dependency for release process

lib/modules/xml/core/src/main/java/io/atlasmap/xml/inspect/XmlSchemaInspector.java, lib/modules/xml/core/src/test/java/io/atlasmap/xml/inspect/XmlSchemaInspectionFhirTest.java, lib/modules/xml/core/src/test/resources/inspect/fhir-patient.xsd, ui/test-resources/xml/schema/fhir-patient.xsd
Fixes: #2406
Narrowed element/type caching to only apply vertically to avoid recursion. It causes OOM if it runs with the previous FHIR XSD, but it turned out the `xhtml:div` involved in FHIR XSD (!!!!!) is disabled in Syndesis FHIR connector. Did the same thing and now response time of FHIR inspection is realistic.
=> fix: XML schema inspection type cache disables too many fields for FHIR

lib/modules/xml/core/src/main/java/io/atlasmap/xml/inspect/XmlSchemaInspector.java, lib/modules/xml/core/src/test/java/io/atlasmap/xml/inspect/BaseXmlInspectionServiceTest.java, lib/modules/xml/core/src/test/java/io/atlasmap/xml/inspect/XmlSchemaInspectionFhirTest.java, lib/modules/xml/core/src/test/java/io/atlasmap/xml/inspect/XmlSchemaInspectionTest.java, lib/modules/xml/core/src/test/resources/inspect/fhir-patient.xsd, lib/modules/xml/model/src/main/java/io/atlasmap/xml/v2/XmlField.java, ui/test-resources/xml/schema/fhir-patient.xsd
Fixes: #2406
Narrowed element/type caching to only apply vertically to avoid recursion. It causes OOM if it runs with the previous FHIR XSD, but it turned out the `xhtml:div` involved in FHIR XSD (!!!!!) is disabled in Syndesis FHIR connector. Did the same thing and now response time of FHIR inspection is realistic.
=> fix: XML schema inspection type cache disables too many fields for FHIR 

ui/packages/atlasmap-core/src/services/mapping-management.service.ts
Fixes: #2438
Also cleanup up code a bit - remove redundant check and create a real error if mappings update fail.
=> fix: Correct erroneous check for JSON response when updating mapping.

ui/packages/atlasmap-core/src/models/document-definition.model.ts, ui/packages/atlasmap/src/Views/ColumnMapperView/Columns/TreeItemFieldAndNodeRefsAndDnD.tsx
Correct cascading '@' chars prepended to attribute fields.
Trivial change to avoid adding a new '@' every time the adm file is loaded.  Also evened out the tooltips.
=> Fixes: #1518

ui/packages/atlasmap/src/UI/MappingField.tsx
=> fix: Limit index modifications to two methods - arrows and d&d.

ui/packages/atlasmap/src/UI/dnd/FieldsDndProvider.tsx
Fixes: #2307
@riccardo-forina - please see if d&d still behaves correctly on Apple - don't have one to try.  This now works on Chrome and Firefox ok,  It's triggering through TouchBackend (enableMouseEvents = true).
=> fix: Corrects d&d on Chrome.

standalone/src/test/java/io/atlasmap/standalone/E2ETest.java
Fixes: #2527
It appears the ` waitForLoad` method doesn't always wait long enough.  I dropped in a 1 second sleep to get the e2e test to behave.
=> fix: Correct intermittent e2etest failure.

ui/packages/atlasmap/src/UI/ExpressionFieldSearch.tsx
Fixes: #2540
This persists the dropdown until you select outside the menu or select an item.
=> fix: Use standard toggle/open state for expression box select construct.

ui/packages/atlasmap-core/src/models/field-action.model.ts, ui/packages/atlasmap-core/src/services/initialization.service.ts, ui/packages/atlasmap-core/src/services/mapping-management.service.ts
=> fix: Syndesis: one-to-many transformation disappears upon reopen

ui/packages/atlasmap/src/UI/MappingField.tsx
Fixes: #2622
The build warning circ dependency is a bug in shelljs (fixed in v0.8.4).  It requires a new storybook and tsdx which then requires new jest, etc.  Recommend tacking this upgrade when we do the patternfly upgrade.
=> fix: Correct UI circular dependency in MappingField.tsx

lib/core/src/main/java/io/atlasmap/converters/BigDecimalConverter.java, lib/core/src/main/java/io/atlasmap/converters/CharSequenceConverter.java, lib/core/src/main/java/io/atlasmap/converters/DoubleConverter.java, lib/core/src/test/java/io/atlasmap/core/DefaultAtlasConversionServiceTest.java
Fixes: #2647
fix: `BigDecimalConverter#toDouble()` unnecessarily loses fractional part
Fixes: #2648
=> fix: Wrong use of float/double MIN/MAX

lib/modules/dfdl/service/src/test/java/io/atlasmap/dfdl/service/DfdlServiceTest.java, lib/modules/xml/core/src/main/java/io/atlasmap/xml/inspect/XmlSchemaInspector.java, lib/modules/xml/core/src/test/java/io/atlasmap/xml/inspect/XmlSchemaInspection2372Test.java, lib/modules/xml/core/src/test/java/io/atlasmap/xml/inspect/XmlSchemaInspectionFhirTest.java, lib/modules/xml/core/src/test/java/io/atlasmap/xml/inspect/XmlSchemaInspectionFormTest.java, lib/modules/xml/core/src/test/java/io/atlasmap/xml/inspect/XmlSchemaInspectionMultipleNamespacesTest.java, lib/modules/xml/core/src/test/java/io/atlasmap/xml/inspect/XmlSchemaInspectionTest.java, lib/modules/xml/core/src/test/resources/inspect/form-default-qualified-schema.xsd, lib/modules/xml/core/src/test/resources/inspect/form-default-unqualified-schema.xsd, lib/modules/xml/core/src/test/resources/inspect/form-no-default-schema.xsd
Fixes: #2655
This fix changes the default behavior for XML Schema inspection. It used to ignore form/elementFormDefault/attributeFormDefault and always apply targetNamespace, while XML Schema defines `elementFormDefault=unqualified` and `attributeFormDefault=unqualified` by default. After this fix, subsequent children are no longer qualified with namespace unless `elementFormDefault=qualified`, `attributeFormDefault=qualified` or `form=qualified` is explicitly specified. Also note that the global element, i.e. defined at the top of the schema is always qualified.
=> fix: XML Schema: Support form/elementFormDefault/attributeFormDefault

pom.xml, ui/package.json, ui/packages/atlasmap-core/package.json, ui/packages/atlasmap-core/src/services/file-management.service.spec.ts, ui/packages/atlasmap-standalone/package.json, ui/packages/atlasmap/.storybook/main.js, ui/packages/atlasmap/package.json, ui/packages/atlasmap/src/Views/SourceMappingTargetView.tsx, ui/yarn.lock
Fixes: #2767
Fixes: #2784
* Updated shelljs
* Updated lerna
* Updated node/npm/yarn used by maven frontend plugin
* Aligned jest version to 24.9.0 (see #2778)
* Updated typescript to 3.9.9
* Ran yarn upgrade
=> chore: UI dependency updates

ui/packages/atlasmap-core/package.json, ui/packages/atlasmap-core/src/services/file-management.service.spec.ts, ui/packages/atlasmap-core/src/services/mapping-management.service.spec.ts, ui/packages/atlasmap-core/src/services/mapping-management.service.ts, ui/packages/atlasmap-core/src/utils/mapping-serializer.spec.ts, ui/packages/atlasmap-standalone/package.json, ui/packages/atlasmap/package.json, ui/packages/atlasmap/src/UI/DocumentFieldPreview.tsx, ui/yarn.lock
Fixes: #2739
Wrapping up this round with updating some small libraries and cleaning up dependency related sections in each package.json
ky couldn't be updated as it caused errors with Jest, even with ky 0.25
Unexpectedly webpack 4.46.0 was still in the yarn.lock, removed manually.
=> chore: Update UI dependencies

standalone/src/test/java/io/atlasmap/standalone/E2ETest.java, ui/packages/atlasmap-core/src/services/document-management.service.ts, ui/packages/atlasmap-core/src/utils/document-inspection-util.ts
Fixes: #2925
It turned out the FQDN was used as a Document label for Java Document, and somehow changed to simple name after refactoring. Using simple name as a Document display name is right (#2919), but it might be better to use Document ID for data-testid to be unique (#2928).
=> fix: E2ETest failure

ui/packages/atlasmap/src/UI/Canvas/NodesArc.stories.tsx
It seems the animation causes snapshot check to emit false positive
https://www.chromatic.com/docs/ignoring-elements
=> chore: Add chromatic ignore for NodesArc story

lib/model/pom.xml, lib/modules/csv/model/pom.xml, lib/modules/dfdl/model/pom.xml, lib/modules/java/model/pom.xml, lib/modules/json/model/pom.xml, lib/modules/xml/model/pom.xml, parent/pom.xml
Fixes: #2721
FYI, if I put this configuration in `parent/pom.xml`:  
`<Include-Resource>${osgi.include.resource},META-INF/jandex.idx=target/classes/META-INF/jandex.idx</Include-Resource>`
The build doesn't work for modules that don't have the jandex.idx. This is the reason why I've overwrote this maven plugin section everywhere, I've created the jandex.
If you have an idea of how I can improve this, let me know.
=> fix: Add jandex index for atlasmap model beans discovery

ui/packages/atlasmap-core/src/services/mapping-management.service.spec.ts, ui/packages/atlasmap-core/src/services/mapping-management.service.ts, ui/packages/atlasmap/src/Atlasmap/utils/field.ts
Fixes: #2976
Renamed to `addFieldToActiveMapping()` as it is the only task this method serves.
=> fix: Clean up mapping-management.service#fieldSelected()

lib/service/src/test/java/io/atlasmap/service/AtlasServiceTest.java, lib/service/src/test/resources/mappings/process-mapping-request-2977.json, ui/packages/atlasmap-core/src/contracts/common.ts, ui/packages/atlasmap-core/src/contracts/documents/java.ts, ui/packages/atlasmap-core/src/contracts/documents/json.ts, ui/packages/atlasmap-core/src/contracts/documents/xml.ts, ui/packages/atlasmap-core/src/contracts/mapping-preview.ts, ui/packages/atlasmap-core/src/contracts/mapping.ts, ui/packages/atlasmap-core/src/models/config.model.ts, ui/packages/atlasmap-core/src/models/document-definition.model.ts, ui/packages/atlasmap-core/src/models/expression.model.ts, ui/packages/atlasmap-core/src/models/field.model.ts, ui/packages/atlasmap-core/src/models/inspect/java-inspection.model.ts, ui/packages/atlasmap-core/src/models/inspect/json-inspection.model.ts, ui/packages/atlasmap-core/src/models/inspect/xml-inspection.model.ts, ui/packages/atlasmap-core/src/models/mapping.model.ts, ui/packages/atlasmap-core/src/services/document-management.service.ts, ui/packages/atlasmap-core/src/services/file-management.service.spec.ts, ui/packages/atlasmap-core/src/services/mapping-expression.service.ts, ui/packages/atlasmap-core/src/services/mapping-preview.service.ts, ui/packages/atlasmap-core/src/utils/mapping-serializer.spec.ts, ui/packages/atlasmap-core/src/utils/mapping-serializer.ts, ui/packages/atlasmap-core/src/utils/mapping-util.ts, ui/packages/atlasmap/src/Atlasmap/utils/field.ts, ui/packages/atlasmap/src/Atlasmap/utils/ui.ts, ui/packages/atlasmap/src/UI/ExpressionContent.tsx, ui/test-resources/mapping/atlasmapping-coll-expr-mapping.json, ui/test-resources/mapping/atlasmapping-coll-expr-preview.json, ui/test-resources/mapping/atlasmapping-coll-ref-expr-preview.json, ui/test-resources/mapping/atlasmapping-expr-prop.json
Fixes: #2977
Expression mapping needs corresponding field entry in `inputFieldGroup` or `inputField` where it's identified with Document ID and path. Same for property, path has to match. No need to handle property scope separately as it's supposed to be put in path.
=> fix: scope is missing in property field path

ui/packages/atlasmap-core/src/contracts/common.ts, ui/packages/atlasmap-core/src/contracts/documents/csv.ts, ui/packages/atlasmap/src/Atlasmap/Atlasmap.tsx, ui/packages/atlasmap/src/Atlasmap/dialogs/index.ts, ui/packages/atlasmap/src/Atlasmap/dialogs/useImportDocumentDialog.tsx, ui/packages/atlasmap/src/Atlasmap/dialogs/useParametersDialog.tsx, ui/packages/atlasmap/src/Atlasmap/useAtlasmapDialogs.tsx, ui/packages/atlasmap/src/Atlasmap/utils/document.ts, ui/packages/atlasmap/src/UI/dialogs/ParametersDialog.stories.tsx, ui/packages/atlasmap/src/UI/dialogs/ParametersDialog.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Actions/EditCSVParamsAction.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Actions/index.ts, ui/packages/atlasmap/src/Views/ColumnMapperView/Columns/SourcesColumn.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Columns/TargetsColumn.tsx, ui/packages/atlasmap/src/Views/SourceTargetView.stories.tsx
Fixes: #2990
As stated in the issue - this adds full CSV parameter edit support and solves the Atlasmap cancel issue.  We can open a new issue or reopen this one if there are Syndesis integration problems.
=> fix: Add support for editing CSV processing parameters.

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasPreviewContext.java, lib/core/src/test/java/io/atlasmap/core/DefaultAtlasPreviewContextTest.java, ui/packages/atlasmap-core/src/utils/mapping-serializer.spec.ts, ui/packages/atlasmap-core/src/utils/mapping-serializer.ts, ui/test-resources/mapping/atlasmapping-split.json
Fixes: #3109
It turned out UI is sending unexpected field index when it's one-to-many with a collection target, which breaks the calculation of collection nest level at backend. Fixed to avoid adding an index if there's only one field at UI side, as well as a safe guard at backend side to ignore the index if there's only one field.
=> fix: [BUG] Wrong index for preview target collection

ui/pom.xml
@pleacu #3141 seems to be rather Java side issue, Java inspection doesn't have collection suffix on the field path as expected. This PR will add TargetTestClass to be inspected and generate `ui/test-resources/inspected/atlasmap-inspection-io.atlasmap.java.test.TargetTestClass.json`
=> chore: Add TargetTestClass for an UI test resource

.github/workflows/cancel-previous.yml
=> chore: Enable canceling previous GitHub workflow

lib/modules/java/core/src/main/java/io/atlasmap/java/inspect/ClassInspectionService.java, lib/modules/java/core/src/test/java/io/atlasmap/java/inspect/ClassInspectionServiceTest.java, lib/modules/java/core/src/test/java/io/atlasmap/java/inspect/ComplexClassInspectTest.java, lib/modules/java/test-model/src/main/java/io/atlasmap/java/test/TargetTestClassExtended.java
Fixes: #3197
Since Java hidden field is generally a bad practice and doesn't work well together with AtlasMap path expression, we'll simply ignore it.
=> fix: Hidden Java Field is shwon duplicated

lib/itests/reference-mappings/pom.xml, lib/itests/reference-mappings/src/test/java/io/atlasmap/itests/reference/csv_to_java/CsvJavaTest.java, lib/itests/reference-mappings/src/test/resources/csvToJava/atlasmapping-csvWithHeaders.csv, lib/itests/reference-mappings/src/test/resources/csvToJava/atlasmapping-csvWithHeaders.json, ui/packages/atlasmap-core/src/models/inspect/csv-inspection.model.ts
=> fix: CSV document does not persist with inspection parameters

lib/core/src/main/java/io/atlasmap/core/AtlasPath.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, lib/core/src/test/java/io/atlasmap/core/DefaultAtlasPreviewContextTest.java, lib/itests/reference-mappings/src/test/java/io/atlasmap/itests/reference/java_to_java/JavaJavaCollectionTest.java, lib/itests/reference-mappings/src/test/resources/javaToJava/atlasmapping-collection-fieldaction2.json, lib/model/src/main/java/io/atlasmap/v2/SimpleField.java, lib/modules/java/core/src/main/java/io/atlasmap/java/core/JavaFieldWriter.java, lib/modules/java/test-model/src/main/java/io/atlasmap/java/test/SourceCollectionsClass.java, lib/modules/java/test-model/src/main/java/io/atlasmap/java/test/TargetCollectionsClass.java
=> fix: Transformation is not applied for Java Target

lib/service/src/main/java/io/atlasmap/service/AtlasLibraryLoader.java, lib/service/src/test/java/io/atlasmap/service/AtlasServiceTest.java
jars
fixes: #3324 ENTESB-15784
URL.getPath should not be used directly. it needs to go through toURi
see Javadoc https://docs.oracle.com/javase/7/docs/api/java/net/URL.html
The URL class does not itself encode or decode any URL components
according to the escaping mechanism defined in RFC2396. It is the
responsibility of the caller to encode any fields, which need to be
escaped prior to calling URL, and also to decode any escaped fields,
that are returned from URL. Furthermore, because URL has no knowledge of
URL escaping, it does not recognise equivalence between the encoded or
decoded form of the same URL
Note, the URI class does perform escaping of its component fields in
certain circumstances. The recommended way to manage the encoding and
decoding of URLs is to use URI, and to …
=> ENTESB-15784 - support space in path to atlasmap workspace when loading

ui/packages/atlasmap/src/UI/ExpressionContent.tsx
My first attempt at fixing this was to establish a new browser-based MutableRefObject editor window. The event flow was sporadic and non-functional. Then simply dynamically expanding the existing editor window seems to work well.
Fixes: #3484
=> fix: Expand the conditional expression box when in focus.

ui/packages/atlasmap-core/src/services/file-management.service.spec.ts, ui/yarn.lock
=> fix: Use `spyOn` to mock `FileSaver.saveAs()`

pom.xml, ui/packages/atlasmap-core/src/services/document-management.service.spec.ts, ui/packages/atlasmap-core/src/services/mapping-expression.service.spec.ts, ui/packages/atlasmap-core/src/utils/mapping-serializer.spec.ts, ui/packages/atlasmap-core/test/setup.tsx, ui/packages/atlasmap-standalone/src/setupTests.js
Fixes: #3560
Also updated to the latest node 16 and npm 8.3.0
node_modules would have to be rebuilt after this update. Remove it and run yarn install (or mvn install)
=> fix: Fix unhandled promise rejection in UI tests

ui/packages/atlasmap-core/src/models/inspect/csv-inspection.model.ts, ui/packages/atlasmap-core/src/models/inspect/cvs-inspection.model.spec.ts, ui/packages/atlasmap-core/src/utils/common-util.spec.ts, ui/packages/atlasmap-core/src/utils/common-util.ts
When changing the CVS parameters the document URI accumulates previously
set parameters. This leads to unwanted parameters remaining, or more
than one value for a parameter being used.
This makes sure that when setting the CVS inspection parameters the
existing parameters are first removed. This way only the desired new
parameters are used.
=> fix: replace existing CVS inspection parameters

ui/packages/atlasmap-core/src/services/initialization.service.spec.ts, ui/packages/atlasmap-core/src/services/initialization.service.ts, ui/test-resources/mapping/atlasmapping-cvs-to-json.json
When initializing with a preloaded mapping JSON, if the mapping JSON
changed, say because the inspection parameters that have changed and
this is reflected in the document URI, we need to notify that the
mapping changed.
A scenario in which this issue is encountered is when CSV parameters
change and no other change is performed. The saved mapping in that case
contains the old URI in the CVS document.
Fixes #3755
=> fix: notify of mapping changes in initialization

ui/packages/atlasmap-core/src/services/initialization.service.spec.ts, ui/packages/atlasmap-core/src/services/initialization.service.ts
This adds two guards to the subscriptions via the `first` operator,
firstly to continue only after all the documents have been processed,
and secondly to get notifications only for the first time the
initialization was done. Otherwise the notification would be triggered
for each document times each time initialization was done, and with each
document another observer would be registered with the subject, all'
leading to an exponentially increasing number of requests to the server
to validate the mapping.
Fixes #3761
=> fix: exponentially increasing validation requests

lib/modules/xml/core/src/test/java/io/atlasmap/xml/inspect/XmlSchemaInspection3826Test.java, lib/modules/xml/core/src/test/resources/inspect/schemaset-3826.xml
Fixes: #3826
It needs `elementFormDefault="qualified"` to propagate target namespace to the sub elements.
=> chore: A test case for https://github.com/atlasmap/atlasmap/issues/3826

docs/src/main/asciidoc/developer-guide/openapi/dfdl/index.adoc, docs/src/main/asciidoc/developer-guide/openapi/java/index.adoc, docs/src/main/asciidoc/developer-guide/openapi/json/index.adoc, docs/src/main/asciidoc/developer-guide/openapi/xml/index.adoc, lib/core/src/main/java/io/atlasmap/core/AtlasUtil.java, lib/core/src/test/java/io/atlasmap/core/AtlasUtilTest.java, lib/model/src/main/java/io/atlasmap/v2/BaseInspectionRequest.java, lib/modules/json/service/src/main/java/io/atlasmap/json/service/JsonService.java, lib/modules/xml/service/src/main/java/io/atlasmap/xml/service/XmlService.java
Fixes: #603
It implements the API side by introducing searchPhrase into InspectionRequest sent to /inspect. 
It should be straightforward to modify UI search to first call the /inspect with the searchPhrase provided and then do a usual client side search to update the tree.
=> fix: Implement server side field search

ui/packages/atlasmap/src/UI/dialogs/ConstantDialog.tsx
=> fix: UI: Set constants dialog focus to the name input widget, not value.

.github/workflows/experimental-build.yml, .github/workflows/main.yml, .github/workflows/post-release.yml, .github/workflows/supported-build.yml
Also use 11.0.14 for JDK 11 build to avoid #3969 windows build error. Monitor JDK 11 latest build as experimental.
=> chore: Set the primary JDK target to 18

ui/packages/atlasmap-core/package.json, ui/packages/atlasmap/package.json, ui/yarn.lock
There's not much benefit to run UI lint as a pre-commit hook separately since both of `yarn build` and `mvn install` run lint as a part of it.
Also husky is not very monorepo friendly and has been having a problem on version update - https://github.com/atlasmap/atlasmap/pull/4025
=> chore: Remove husky

lib/modules/xml/xsom/test/com/sun/xml/xsom/XSOMParserTest.java
Fixes: #4190
Disable the test for now... tried to enforce https but couldn't find an easy way to hijack resolving XML import that works for transitive one
=> fix: Test failure in XSOM due to non secure schema URL

ui/packages/atlasmap-core/package.json, ui/packages/atlasmap-core/src/models/inspect/document-inspection.model.ts, ui/packages/atlasmap-core/src/services/document-management.service.spec.ts, ui/packages/atlasmap-core/src/services/document-management.service.ts, ui/packages/atlasmap-core/src/services/field-action.service.spec.ts, ui/packages/atlasmap-core/src/services/file-management.service.spec.ts, ui/packages/atlasmap-core/src/services/initialization.service.spec.ts, ui/packages/atlasmap-core/src/services/initialization.service.ts, ui/packages/atlasmap-core/src/services/mapping-management.service.spec.ts, ui/packages/atlasmap-core/src/services/mapping-preview.service.spec.ts, ui/packages/atlasmap-standalone/craco.config.js, ui/packages/atlasmap-standalone/package.json, ui/packages/atlasmap/.storybook/webpack.config.js, ui/packages/atlasmap/package.json, ui/packages/mock-embedded/craco.config.js, ui/packages/mock-embedded/package.json, ui/yarn.lock
Fixes: #4320
Google Chrome 105 made a breaking change and made some case fail which used to be working fine with older Chrome. https://developer.chrome.com/articles/fetch-streaming-requests/
ky made a fix for that
https://github.com/sindresorhus/ky/issues/450
But since the newer ky no longer provides umd, we had to change the Jest configuration to deal with esm. Also we needed to introduce craco to add @babel/plugin-proposal-nullish-coalescing-operator which is required to update ky.
=> fix: AtlasMap is stuck after importing CSV on latest Google Chrome 105

parent/pom.xml
=> [ENTESB-20837] Remove references to org.slfj4:slf4j-log4j12
