ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts
=> fix: UI puts invalid uri for Java DataSource

runtime/atlasmap-maven-plugin/atlasmap-maven-plugin-example.pom, runtime/atlasmap-maven-plugin/src/main/java/io/atlasmap/maven/GenerateInspectionsMojo.java
=> fix: atlasmap-maven-plugin: Can't inspect COMPLEX fields

runtime/modules/java/core/src/main/java/io/atlasmap/java/inspect/ClassInspectionService.java, runtime/modules/java/core/src/test/java/io/atlasmap/java/inspect/ClassInspectionServiceTest.java, runtime/modules/java/core/src/test/java/io/atlasmap/java/inspect/TestEnum.java, runtime/modules/java/core/src/test/java/io/atlasmap/java/inspect/TestEnumExtendedStatus.java, runtime/modules/java/core/src/test/java/io/atlasmap/java/inspect/TestEnumStatus.java
=> fix: Java field inspection doesn't support Enum fields

runtime/modules/json/module/src/main/java/io/atlasmap/json/module/JsonModule.java
This is a duplicate of the one in BaseAtlasModule
=> chore: remove duplicated method

build.sh, camel/pom.xml, pom.xml, runtime/pom.xml, ui/pom.xml
=> fix: Moved release profiles into root pom and added release targets to build.sh

ui/src/app/lib/atlasmap-data-mapper/components/data.mapper.example.host.component.ts, ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
=> enable all target mock documents

runtime/core/src/test/java/io/atlasmap/core/AtlasModuleSupportTest.java, runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasModuleInfoTest.java, runtime/core/src/test/java/io/atlasmap/core/ValidationConstantsTest.java
added more JUnit tests to increase codes coverage
=> chore: added new module supported unit tests 

ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping.detail.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping.field.action.component.ts
=> fix: datamapper buttons are links

ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping.field.detail.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/document.definition.model.ts
=> fix: Make [None] disappear on focus

runtime/core/src/main/java/io/atlasmap/actions/DateFieldActions.java, runtime/core/src/main/java/io/atlasmap/actions/StringComplexFieldActions.java, runtime/core/src/main/resources/META-INF/services/io.atlasmap.api.AtlasFieldAction, runtime/core/src/test/java/io/atlasmap/actions/DateFieldActionsTest.java, runtime/core/src/test/java/io/atlasmap/actions/StringComplexFieldActionsTest.java, runtime/itests/reference-mappings/src/test/java/io/atlasmap/reference/AtlasBaseActionsTest.java, runtime/model/src/main/java/io/atlasmap/v2/ActionsJsonDeserializer.java, runtime/model/src/main/java/io/atlasmap/v2/ActionsJsonSerializer.java, runtime/model/src/main/java/io/atlasmap/v2/AtlasModelFactory.java, runtime/model/src/main/resources/atlas-actions-v2.xsd, runtime/model/src/test/java/io/atlasmap/v2/BaseMarshallerTest.java
=> Fixes #175: Implement Date-related p0 field actions

runtime/modules/java/core/src/main/java/io/atlasmap/java/inspect/ClassInspectionService.java, runtime/modules/java/core/src/test/java/io/atlasmap/java/inspect/MapTest.java, runtime/modules/java/core/src/test/java/io/atlasmap/java/inspect/TestMap.java, runtime/modules/java/test-model/src/main/java/io/atlasmap/java/test/TestMapOrders.java
=> fix: Java inspection to support Map as a root-level object

runtime/core/pom.xml, runtime/core/src/test/java/io/atlasmap/actions/NumberFieldActionsTest.java, runtime/core/src/test/java/io/atlasmap/converters/StringConverterTest.java, runtime/core/src/test/java/io/atlasmap/core/AtlasMappingServiceTest.java, runtime/core/src/test/java/io/atlasmap/core/AtlasPathTest.java, runtime/core/src/test/java/io/atlasmap/core/AtlasUtilTest.java, runtime/core/src/test/java/io/atlasmap/core/ConstantModuleTest.java, runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasContextFactoryTest.java, runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasContextTest.java, runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasConversionServiceTest.java, runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasFieldActionsServiceTest.java, runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasModuleInfoRegistryTest.java, runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasSessionTest.java, runtime/core/src/test/java/io/atlasmap/core/PropertyModuleTest.java, runtime/core/src/test/java/io/atlasmap/validators/AtlasValidationHelperTest.java, runtime/core/src/test/java/io/atlasmap/validators/CompositeValidatorTest.java, runtime/core/src/test/resources/AtlasUtilTest.properties, runtime/core/src/test/resources/atlasmapping.json, runtime/core/src/test/resources/atlasmapping.xml
chore: added test cases to increase unit test coverage of atlas-core
Relates to: #16
=> chore: added test cases to increase unit test coverage of atlas-core

runtime/service/src/main/java/io/atlasmap/service/AtlasService.java
=> fix: AtlasService.converterCheck() contains incomplete code

runtime/model/src/main/java/io/atlasmap/v2/ActionsJsonDeserializer.java
=> fix: ActionsJsonDeserializer: in case of "Add", it should return new Add();"Concatentate" should be "Concatenate"

runtime/model/src/main/java/io/atlasmap/v2/AtlasModelFactory.java
=> fix: AtlasModelFactory - potential NullPointerException

runtime/core/src/main/java/io/atlasmap/actions/StringComplexFieldActions.java, runtime/core/src/test/java/io/atlasmap/actions/StringComplexFieldActionsTest.java
=> fix: Substring before/after end index check

runtime/modules/json/core/src/main/java/io/atlasmap/json/core/JsonComplexTypeFactory.java, runtime/modules/json/core/src/main/java/io/atlasmap/json/inspect/InstanceInspector.java, runtime/modules/json/core/src/main/java/io/atlasmap/json/inspect/SchemaInspector.java, runtime/modules/json/core/src/test/java/io/atlasmap/json/core/JsonFieldWriterTest.java, runtime/modules/xml/core/src/main/java/io/atlasmap/xml/core/XmlComplexTypeFactory.java, runtime/modules/xml/core/src/main/java/io/atlasmap/xml/inspect/InstanceInspector.java, runtime/modules/xml/core/src/main/java/io/atlasmap/xml/inspect/SchemaInspector.java
=> fix: Create XMLComplexType and JsonComplexType using the factory method

runtime/modules/xml/core/src/test/java/io/atlasmap/xml/core/XmlFieldReaderTest.java
=> fix: XmlFieldReader test fails with the method really in use

ui/src/app/lib/atlasmap-data-mapper/common/focus.directive.ts, ui/src/app/lib/atlasmap-data-mapper/components/document.definition.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping.list.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/namespace.list.component.ts, ui/src/app/lib/atlasmap-data-mapper/data.mapper.module.ts
=> fix: No focus on text field when search is selected

ui/src/app/lib/atlasmap-data-mapper/common/to-error-icon-class.pipe.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping.list.component.ts, ui/src/app/lib/atlasmap-data-mapper/data.mapper.module.ts, ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts
=> fix: Table view shows wrong icon for the validation error

runtime/modules/java/core/src/test/java/io/atlasmap/java/core/BaseDocumentWriterTest.java, runtime/modules/java/core/src/test/java/io/atlasmap/java/core/DocumentJavaFieldWriterTest.java
=> fix: DocumentJavaFieldWriterTest depends on test only method

runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java
=> fix: DefaultAtlasFieldActionService.java - potential NullPointerException

ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts
fix: Simplify appliesToField method for target types
=> Fixes: #225

ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts
=> fix: Do not lose user specified argument values between sessions.

ui/package.json, ui/src/app/lib/atlasmap-data-mapper/components/document.definition.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/document.definition.model.ts, ui/yarn.lock
=> fix: ui search fix for child fields

runtime/model/src/test/java/io/atlasmap/v2/BaseMarshallerTest.java, runtime/modules/java/model/src/test/java/io/atlasmap/java/v2/BaseMarshallerTest.java, runtime/modules/java/model/src/test/java/io/atlasmap/java/v2/JsonMarshallerTest.java, runtime/modules/java/model/src/test/java/io/atlasmap/java/v2/XmlMarshallerTest.java, runtime/modules/json/model/src/test/java/io/atlasmap/json/v2/BaseMarshallerTest.java, runtime/modules/json/model/src/test/java/io/atlasmap/json/v2/JsonMarshallerTest.java, runtime/modules/json/model/src/test/java/io/atlasmap/json/v2/XmlMarshallerTest.java, runtime/modules/xml/model/src/test/java/io/atlasmap/xml/v2/BaseMarshallerTest.java
=> chore: Add json and xml serialize+deserialize tests for 100% field coverage

ui/src/app/lib/atlasmap-data-mapper/models/document.definition.model.ts
=> fix: handle array and list complex use cases for priming doc definition model

runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasConversionService.java
=> chore: removed unused method

ui/src/app/lib/atlasmap-data-mapper/models/document.definition.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/document.management.service.ts
=> fix: Dont step on field types for Collection LIST or ARRAY mappings.

ui/src/app/lib/atlasmap-data-mapper/common/data.mapper.util.ts, ui/src/app/lib/atlasmap-data-mapper/components/constant.field.edit.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/field.edit.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/namespace.edit.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/property.field.edit.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts
Corrects the first dependency identified in issue #128
Move isRequiredFieldValid() out of data.mapper.util to break the circular dep.
=> fix: Correct circular dependency involving DM utility and config model.

build.sh
#258  
Tag also minor number when release Docker images
=> Tag also minor number when releasing Docker images

runtime/modules/xml/core/src/main/java/io/atlasmap/xml/inspect/SchemaInspector.java, runtime/modules/xml/core/src/test/java/io/atlasmap/xml/inspect/XmlSchemaInspectionMultipleNamespacesTest.java, runtime/modules/xml/core/src/test/java/io/atlasmap/xml/inspect/XmlSchemaInspectionTest.java, runtime/modules/xml/core/src/test/resources/inspect/multiple-namespaces-syndesis.xml, runtime/modules/xml/core/src/test/resources/inspect/multiple-no-namespace-root-schema.xml, runtime/modules/xml/core/src/test/resources/inspect/multiple-no-namespace-schemas-conflict.xml, runtime/modules/xml/core/src/test/resources/inspect/multiple-no-namespace-schemas.xml, runtime/modules/xml/model/src/main/resources/atlas-xml-schemaset-model-v2.xsd
=> fix: Support XML schemas without namespaces

ui/src/app/lib/atlasmap-data-mapper/components/data.mapper.app.component.css, ui/src/app/lib/atlasmap-data-mapper/components/document.definition.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping.detail.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
Fixes: #274 
Need to review what the semantics of the 'Add Mapping' button is supposed to be within 'Repeating Mapping'
=> fix: Add tooltips and enlarge icons for repeating mapping/ editing.

runtime/itests/reference-mappings/README.md
Sample rendered view: https://github.com/mattrpav/atlasmap/tree/wip-104/runtime/itests/reference-mappings
Note: Please squash when merging!
=> Add README.md for reference-mappings

runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasConversionService.java
=> fix: filter out redudant converter methods

camel/src/main/java/org/apache/camel/component/atlasmap/AtlasEndpoint.java, camel/src/test/java/org/apache/camel/component/atlasmap/AtlasMapComponentJavaToJsonTest.java, camel/src/test/java/org/apache/camel/component/atlasmap/AtlasMapMultiNSTest.java
=> chore: Set the Content-Type message header

ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts
=> chore: Support source/target document shown collapsed at first

runtime/core/src/main/java/io/atlasmap/converters/DateConverter.java, runtime/modules/java/module/src/test/java/io/atlasmap/java/module/JavaValidationServiceTest.java
=> fix: DateConverter should not use FieldType.COMPLEX

runtime/modules/java/module/src/main/java/io/atlasmap/java/module/JavaModule.java, runtime/modules/json/module/src/main/java/io/atlasmap/json/module/JsonModule.java, runtime/modules/xml/module/src/main/java/io/atlasmap/xml/module/XmlModule.java
=> fix: Better error handling for null source document

runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasConversionService.java, runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, runtime/modules/java/core/src/test/java/io/atlasmap/java/inspect/ClassInspectionServiceTest.java, runtime/modules/java/core/src/test/java/io/atlasmap/java/inspect/ClassValidationUtil.java
=> chore: Use java.util.Date as a DATE_TIME representative class

ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.html, ui/src/app/lib/atlasmap-data-mapper/services/document-management.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
=> fix: Better error message when Atlasmap Service is not running

ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.ts
=> fix: Disable "Add Field" on JSON/XML doc

runtime/api/src/main/java/io/atlasmap/api/AtlasConversionService.java, runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasConversionService.java, runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasConversionServiceTest.java, runtime/itests/reference-mappings/src/test/java/io/atlasmap/reference/java_to_java/JavaJavaFieldActionsTest.java, runtime/modules/java/core/src/main/java/io/atlasmap/java/core/TargetValueConverter.java, ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
=> fix: Avoid class loading against primitive types

runtime/core/src/main/java/io/atlasmap/core/ConstantModule.java, runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasPropertyStrategy.java, runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasPropertyStrategyTest.java, runtime/itests/core/src/test/java/io/atlasmap/core/issue/ConstantPropertyTest.java, runtime/itests/core/src/test/resources/mappings/issue/constant-property-mapping.xml
=> fix: Implement property order and fixed conversion for property/constant

runtime/core/src/main/java/io/atlasmap/actions/DateFieldActions.java, runtime/core/src/main/java/io/atlasmap/converters/CalendarConverter.java, runtime/core/src/main/java/io/atlasmap/converters/DateConverter.java, runtime/core/src/main/java/io/atlasmap/converters/DateTimeHelper.java, runtime/core/src/main/java/io/atlasmap/converters/LocalDateConverter.java, runtime/core/src/main/java/io/atlasmap/converters/LocalDateTimeConverter.java, runtime/core/src/main/java/io/atlasmap/converters/LocalTimeConverter.java, runtime/core/src/main/java/io/atlasmap/converters/ZonedDateTimeConverter.java, runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasConversionService.java, runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, runtime/core/src/test/java/io/atlasmap/actions/DateFieldActionsTest.java, runtime/core/src/test/java/io/atlasmap/converters/CalendarConverterTest.java, runtime/core/src/test/java/io/atlasmap/converters/DateConverterTest.java, runtime/core/src/test/java/io/atlasmap/converters/LocalDateConverterTest.java, runtime/core/src/test/java/io/atlasmap/converters/ZonedDateTimeConverterTest.java, runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasConversionServiceTest.java, runtime/model/src/main/resources/atlas-model-v2.xsd
=> fix: Fix date/time related runtime code so fields show up correctly in UI

ui/src/app/lib/atlasmap-data-mapper/components/mapping/collection-mapping.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-detail.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/simple-mapping.component.html, ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.html
fixes https://github.com/atlasmap/atlasmap/issues/349
=> fix tooltip elements from going outside of the page

ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts
=> fix: Prevent multiple mappings to the same target element.

.circleci/config.yml, parent/pom.xml
=> chore: Use community version of xsom

parent/pom.xml, runtime/docs/ci-docs.sh
And removed credential placeholder from github URL, now circleci should be able to use deploy key
=> chore: Also removed redhat maven repo for #366

ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
=> fix: Correct certain ctrl-m1 select-deselect scenarios

ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
=> fix: Correct auto index resequencing for combine/ separate modes.

runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, runtime/itests/core/src/test/java/io/atlasmap/core/issue/Atlasmap381Test.java, runtime/itests/core/src/test/java/io/atlasmap/core/issue/SourceClass.java, runtime/itests/core/src/test/java/io/atlasmap/core/issue/TargetClass.java, runtime/itests/core/src/test/resources/mappings/issue/atlasmap-381-mapping.xml
=> fix: Handle ANY_DATE when resolving converter

ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css
since `ViewEncapsulation` is `None` for this component, the `.toolbar` class is affecting other parts of the syndesis app. fixes https://github.com/syndesisio/syndesis/issues/2419
=> limit .toolbar class to .DataMapperUI

runtime/api/src/main/java/io/atlasmap/spi/AtlasConversionConcern.java, runtime/core/src/main/java/io/atlasmap/converters/StringConverter.java, runtime/core/src/test/java/io/atlasmap/converters/StringConverterTest.java, runtime/modules/java/module/src/test/java/io/atlasmap/java/module/JavaValidationServiceTest.java, runtime/modules/json/core/src/test/java/io/atlasmap/json/core/JsonFieldWriterTest.java, runtime/modules/json/module/src/test/java/io/atlasmap/json/module/JsonValidationServiceTest.java, runtime/modules/xml/core/src/test/java/io/atlasmap/xml/core/XmlFieldReaderTest.java, runtime/modules/xml/core/src/test/java/io/atlasmap/xml/core/XmlFieldWriterTest.java, runtime/modules/xml/module/src/test/java/io/atlasmap/xml/module/XmlValidationServiceTest.java
=> fix: String > int/long converter fails with decimal expression

build.sh, camel/src/main/java/org/apache/camel/component/atlasmap/AtlasEndpoint.java, docs/pom-javadoc.xml, docs/publish-docs.sh, docs/src/main/asciidoc/inc/internal/_design_time_service.adoc, docs/src/main/asciidoc/inc/internal/_runtime.adoc, docs/src/main/asciidoc/index.adoc, runtime/api/src/main/java/io/atlasmap/api/AtlasConversionService.java, runtime/core/src/main/java/io/atlasmap/core/AtlasUtil.java, runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java, runtime/modules/json/core/src/main/java/io/atlasmap/json/inspect/JsonInspectionException.java, runtime/modules/xml/core/src/main/java/io/atlasmap/xml/inspect/XmlInspectionException.java, runtime/runtime/src/main/java/io/atlasmap/runtime/Application.java
=> feat: Publish javadoc at docs.atlasmap.io

runtime/modules/json/core/src/main/java/io/atlasmap/json/core/JsonFieldWriter.java, runtime/modules/json/core/src/test/java/io/atlasmap/json/core/JsonFieldWriterTest.java
=> fix: Add NUMBER check in JsonFieldWriter

runtime/modules/json/core/src/main/java/io/atlasmap/json/core/JsonFieldWriter.java, runtime/modules/json/core/src/test/java/io/atlasmap/json/core/JsonFieldWriterTest.java
=> Add NUMBER check in JsonFieldWriter

ui/src/app/lib/atlasmap-data-mapper/models/transition.model.spec.ts
This is more a test check-in to make sure I'm doing this correctly. I want a review and check-in, without closing the issue.
=> Fix for #405: Add UI tests for fixes to field action availability

runtime/runtime/pom.xml, runtime/runtime/src/main/java/io/atlasmap/runtime/AtlasMapXsrfRepository.java, runtime/runtime/src/main/java/io/atlasmap/runtime/SecurityConfiguration.java, runtime/runtime/src/test/java/io/atlasmap/runtime/RestTest.java
=> fix: Implement XSRF header handling with spring-boot adapter

runtime/core/src/main/java/io/atlasmap/converters/DateConverter.java, runtime/core/src/main/java/io/atlasmap/converters/LocalDateConverter.java, runtime/core/src/main/java/io/atlasmap/converters/LocalDateTimeConverter.java, runtime/core/src/main/java/io/atlasmap/converters/LocalTimeConverter.java, ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-example-host.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/line-machine.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-detail.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/modal-window.component.ts, ui/src/app/lib/atlasmap-data-mapper/services/document-management.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Fixes: #111 
chore: Remove redundant converter which cause warnings
=>  fix: Unsubscribe abandoned Subscription, or use Promise for one-time callback

ui/src/app/lib/atlasmap-data-mapper/common/to-error-icon-class.pipe.ts, ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css, ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-error.component.html, ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-error.component.ts, ui/src/app/lib/atlasmap-data-mapper/data-mapper.module.ts, ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
=> fix: Add auto action mode change to the mapping details section.

runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java, runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasContextTest.java, runtime/itests/core/src/test/java/io/atlasmap/core/issue/CollectionComplexTest.java, runtime/itests/core/src/test/java/io/atlasmap/core/issue/Item.java, runtime/itests/core/src/test/java/io/atlasmap/core/issue/SourceClass.java, runtime/itests/core/src/test/java/io/atlasmap/core/issue/TargetClass.java, runtime/itests/core/src/test/resources/mappings/issue/collection-complex-mapping.xml
=> fix: Target field must be created via target module

.circleci/config.yml, runtime/api/src/main/java/io/atlasmap/spi/AtlasInternalSession.java, runtime/core/src/main/java/io/atlasmap/core/AtlasUtil.java, runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java, runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasSession.java, runtime/modules/java/core/src/main/java/io/atlasmap/java/core/DocumentJavaFieldReader.java, runtime/modules/java/core/src/test/java/io/atlasmap/java/core/BaseDocumentReaderTest.java, runtime/modules/java/core/src/test/java/io/atlasmap/java/core/DocumentJavaFieldReaderTest.java
=> fix: NPE from DocumentJavaFieldReader.read() is thrown up to client

ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css, ui/src/app/lib/atlasmap-data-mapper/components/mapping/collection-mapping.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/simple-mapping.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/transition-selection.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/document-definition.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
=> fix: Add gap support in combine/ separate modes.

ui/src/app/lib/atlasmap-data-mapper/components/mapping/collection-mapping.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts
=> fix: Add transformation UI support to arrays/collection mappings.

docs/src/main/asciidoc/inc/swagger/core/definitions.adoc, docs/src/main/asciidoc/inc/swagger/core/paths.adoc, runtime/api/src/main/java/io/atlasmap/api/AtlasContext.java, runtime/core/src/main/java/io/atlasmap/core/AtlasUtil.java, runtime/core/src/main/java/io/atlasmap/core/BaseAtlasModule.java, runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java, runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasContextTest.java, runtime/model/src/main/resources/atlas-model-v2.xjb, runtime/model/src/main/resources/atlas-model-v2.xsd, runtime/runtime/src/main/java/io/atlasmap/runtime/Application.java, runtime/service/src/main/java/io/atlasmap/service/AtlasService.java, runtime/service/src/test/java/io/atlasmap/service/AtlasServiceTest.java, ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-example-host.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-detail.component.html, ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.html, ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
Fixes: #453
Also partially addresses: #454 - UX design needs to be polished (#455)
=> feat: Support process single mapping in preview mode

ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-list-field.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-list.component.ts
=> chore: Enable mapping preview also in table view

runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java
=> fix: Check source field value type in processPreview()

runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java
=> fix: Skip incomplete mapping in processPreview()

runtime/api/src/main/java/io/atlasmap/spi/AtlasCombineStrategy.java, runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasCombineStrategy.java, runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java, runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasContextFactory.java, runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasValidationService.java, runtime/core/src/main/java/io/atlasmap/core/TemplateCombineStrategy.java, runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasCombineStrategyTest.java, runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasContextFactoryTest.java, runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasContextTest.java, runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasModuleInfoRegistryTest.java
=> Fix for #46: Add TemplateCombineStrategy

ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.html
fixes https://github.com/atlasmap/atlasmap/issues/513 and https://github.com/syndesisio/syndesis/issues/2858
=> add placement attr to add/remove transformation tooltip

ui/src/app/lib/atlasmap-data-mapper/components/mapping/simple-mapping.component.ts
=> fix: Correct drag&drop on firefox.

ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-detail.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.ts
=> fix: Remove LookupTable when corresponding mapping is removed

ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/transition-selection.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/error.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/error-handler.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
=> fix: Clear mapping error notifications when no longer valid.

ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css, ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.html, ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-list-field.component.html
=> fix: Apply UXD outcome for data preview - single entry

runtime/core/src/main/java/io/atlasmap/actions/StringComplexFieldActions.java, ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts
=> Fixes #515: Prepend FieldAction doesn't show up for STRING target field

ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.html, ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
=> fix: Make "Editor Settings" gear icon blue only when it's open

runtime/api/src/main/java/io/atlasmap/api/v3/Mapping.java, runtime/api/src/main/java/io/atlasmap/api/v3/MappingDocument.java, runtime/api/src/main/java/io/atlasmap/api/v3/Parameter.java, runtime/api/src/main/java/io/atlasmap/api/v3/Transformation.java, runtime/api/src/main/java/io/atlasmap/spi/v3/BaseParameter.java, runtime/api/src/main/java/io/atlasmap/spi/v3/BaseTransformation.java, runtime/api/src/main/java/io/atlasmap/spi/v3/DataHandler.java, runtime/api/src/main/java/io/atlasmap/spi/v3/TransformationSupport.java, runtime/core/src/main/java/io/atlasmap/core/v3/MappingDocumentImpl.java, runtime/core/src/main/java/io/atlasmap/core/v3/MappingImpl.java, runtime/core/src/main/java/io/atlasmap/core/v3/MessageImpl.java, runtime/core/src/main/java/io/atlasmap/core/v3/transformation/AddTransformation.java, runtime/itests/core/src/test/java/io/atlasmap/core/v3/AddTransformationTest.java, runtime/itests/core/src/test/java/io/atlasmap/core/v3/EndToEndTest.java, runtime/itests/core/src/test/java/io/atlasmap/core/v3/TestClass.java, runtime/modules/java/module/src/main/java/io/atlasmap/datahandler/java/JavaHandler.java
Plus some miscellaneous cleanup
=> Update for auto-conversions and validations

docs/src/main/asciidoc/inc/swagger/core/definitions.adoc, runtime/atlasmap-maven-plugin/atlasmap-maven-plugin-example.pom, runtime/atlasmap-maven-plugin/src/main/java/io/atlasmap/maven/AbstractAtlasMapMojo.java, runtime/atlasmap-maven-plugin/src/main/java/io/atlasmap/maven/GenerateFieldActionsMojo.java, runtime/atlasmap-maven-plugin/src/main/java/io/atlasmap/maven/GenerateInspectionsMojo.java, runtime/atlasmap-maven-plugin/src/test/java/io/atlasmap/maven/test/DummyFieldActions.java, runtime/atlasmap-maven-plugin/src/test/resources/META-INF/services/io.atlasmap.api.AtlasFieldAction, runtime/atlasmap-maven-plugin/test.sh, runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, runtime/model/src/main/java/io/atlasmap/v2/ActionsJsonDeserializer.java, runtime/model/src/main/java/io/atlasmap/v2/ActionsJsonSerializer.java, runtime/model/src/main/resources/atlas-actions-v2.xsd, runtime/model/src/main/resources/atlas-model-v2.xsd, runtime/model/src/test/java/io/atlasmap/v2/JsonMarshallerTest.java, ui/package.json
=> feat: Create GenerateFieldActionsMojo

runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, ui/karma.conf.js, ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.spec.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts, ui/test-resources/fieldActions/atlasmap-field-action.json
fix: Disable CustomAction parameter
Fixes: #537
feat: Support receiving FieldActions metadata from outside
Fixes: #483
=> feat: Support receiving FieldActions metadata from outside (#483)

camel/src/test/java/org/apache/camel/component/atlasmap/AtlasMapComponentTest.java, camel/src/test/resources/atlasmapping.xml, ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
=> fix: Constants value is not saved into mapping definition

ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css, ui/src/app/lib/atlasmap-data-mapper/components/modal-window.component.html, ui/src/app/lib/atlasmap-data-mapper/components/modal-window.component.ts
fixes https://github.com/atlasmap/atlasmap/issues/489
=> fix(modal): update title font, close icon, cancel button, modal fade in/out

runtime/core/src/test/java/io/atlasmap/converters/ByteConverterTest.java, runtime/core/src/test/java/io/atlasmap/core/DefaultAtlasContextTest.java, runtime/modules/java/core/src/test/java/io/atlasmap/java/inspect/JavaConstructServiceSimpleTest.java
as reported by Codacy
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
=> Remove Unnecessary use of fully qualified name

ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-list-field.component.html
=> fix: UI freezes with data preview enabled in table view

ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css
=> fix: Correct merge error affecting Constant/Property

ui/src/app/atlasmap-navbar.component.html, ui/src/app/atlasmap-navbar.component.ts
This PR adds get accessors for properties used navbar and in turn fixes an error found in the UI build scripts.
=> fix(build): fix demo app build script

pom.xml
Add Fuse early access repository for camel builds.
=> Add Fuse early access repository for camel builds.

ui/src/app/atlasmap-navbar.component.html, ui/src/app/atlasmap-navbar.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.html, ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.ts, ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
=> fix: Enable loading spinners on schema/mappings import.

runtime/core/src/main/java/io/atlasmap/actions/DateFieldActions.java, runtime/core/src/main/java/io/atlasmap/actions/ObjectFieldActions.java, runtime/core/src/test/java/io/atlasmap/actions/DateFieldActionsTest.java, runtime/core/src/test/java/io/atlasmap/actions/ObjectFieldActionsTest.java, runtime/model/src/main/java/io/atlasmap/v2/ActionsJsonDeserializer.java, runtime/model/src/main/java/io/atlasmap/v2/ActionsJsonSerializer.java, runtime/model/src/main/resources/atlas-actions-v2.xsd
Fixes: #556
Still DayOf* doesn't appear for Date/Time source field. We'll continue on #385
=> feat: Add `ItemAt` and `DayOfMonth` Transformation

.circleci/config.yml, .mvn/wrapper/maven-wrapper.properties, parent/pom.xml, runtime/pom.xml
=> fix: CircleCI build fails with VM terminated error

docs/src/main/asciidoc/inc/swagger/java/definitions.adoc, runtime/core/src/main/java/io/atlasmap/core/AtlasUtil.java, runtime/itests/core/src/test/java/io/atlasmap/core/BaseClass.java, runtime/itests/core/src/test/java/io/atlasmap/core/NestedClassTest.java, runtime/itests/core/src/test/java/io/atlasmap/core/SourceClass.java, runtime/itests/core/src/test/java/io/atlasmap/core/TargetClass.java, runtime/itests/core/src/test/resources/mappings/atlasmapping-nested-class.xml, runtime/modules/java/core/src/main/java/io/atlasmap/java/core/JavaWriterUtil.java, runtime/modules/java/core/src/main/java/io/atlasmap/java/inspect/ClassInspectionService.java, runtime/modules/java/core/src/main/java/io/atlasmap/java/inspect/JavaConstructService.java, runtime/modules/java/core/src/test/java/io/atlasmap/java/inspect/ClassValidationUtil.java, runtime/modules/java/core/src/test/java/io/atlasmap/java/inspect/ComplexClassInspectTest.java, runtime/modules/java/core/src/test/java/io/atlasmap/java/inspect/PrimitiveInspectTest.java, runtime/modules/java/core/src/test/java/io/atlasmap/java/inspect/PrimitiveValidationUtil.java, runtime/modules/java/core/src/test/java/io/atlasmap/java/inspect/TestListOrdersTest.java, runtime/modules/java/model/src/main/resources/atlas-java-model-v2.xsd, runtime/modules/java/module/src/main/java/io/atlasmap/java/module/JavaModule.java, runtime/modules/java/test-model/src/main/java/io/atlasmap/java/test/BaseOrder.java, ui/src/app/lib/atlasmap-data-mapper/services/document-management.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
=> fix: Class inspection can't inspect nested class

camel/src/test/java/org/apache/camel/component/atlasmap/AtlasMapComponentXmlToXmlTest.java, camel/src/test/resources/atlasmapping-xml-to-xml.json, camel/src/test/resources/org/apache/camel/component/atlasmap/AtlasMapComponentXmlToXmlTest-context.xml
Add a test for xml->xml for the AtlasComponent. Useful for troubleshooting
=> Add Xml To Xml Camel AtlasMap test

runtime/core/src/main/java/io/atlasmap/actions/ObjectFieldActions.java, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/transition.model.spec.ts, ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts, ui/test-resources/fieldActions/atlasmap-field-action.json
=> fix: Support source-side transformations with no target selected

ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.ts
=> fix: Correct firefox bug with drag&drop mappings

ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-list-field.component.html
Fixes: #621
Actually #564 was rolled back at some point it seems, reapplying.
=> fix: UI freezes after showing previews in mapping table

ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts
Fixes: #385 
No function specific coding required
=> fix: Correct DayOf transformation inclusion

ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.html, ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
=> fix: Fix issue with export name change in text widget

ui/src/app/lib/atlasmap-data-mapper/components/mapping/collection-mapping.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-detail.component.html, ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
=> fix: Support source side transformation for collections

ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.ts
=> fix: Correct missing line for Constants in UI after reload

ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.ts
Fixes: #565 
This might have fixed #641 as well by accident \o/
@pleacu can you double check?
=> fix: Line machine is broken with data preview enabled

ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.html, ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
=> fix: Correct 'Cancel' button on adm file input.

runtime/modules/json/core/src/main/java/io/atlasmap/json/inspect/InstanceInspector.java, runtime/modules/json/core/src/test/java/io/atlasmap/json/inspect/JsonDocumentInspectionServiceTest.java, runtime/modules/json/core/src/test/resources/inspect/address.json, ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-example-host.component.ts
=> fix: Fix JSON instance inspection including array handling

runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
=> fix: Ignore null value for COMBINE mode

ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts
=> fix: Concatenate transformation shows up for non-collection source field

docs/src/main/asciidoc/inc/swagger/core/paths.adoc, runtime/api/src/main/java/io/atlasmap/spi/AtlasFieldActionService.java, runtime/core/src/main/java/io/atlasmap/core/BaseModuleValidationService.java, runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, runtime/modules/java/module/src/main/java/io/atlasmap/java/module/JavaModule.java, runtime/modules/java/module/src/main/java/io/atlasmap/java/module/JavaValidationService.java, runtime/modules/java/module/src/test/java/io/atlasmap/java/module/JavaValidationServiceTest.java, runtime/modules/java/module/src/test/resources/mappings/HappyPathMappingTransformation.xml, runtime/modules/json/module/src/main/java/io/atlasmap/json/module/JsonModule.java, runtime/modules/json/module/src/main/java/io/atlasmap/json/module/JsonValidationService.java, runtime/modules/json/module/src/test/java/io/atlasmap/json/module/JsonValidationServiceTest.java, runtime/modules/xml/module/src/main/java/io/atlasmap/xml/module/XmlModule.java, runtime/modules/xml/module/src/main/java/io/atlasmap/xml/module/XmlValidationService.java, runtime/modules/xml/module/src/test/java/io/atlasmap/xml/module/XmlValidationServiceTest.java
=> fix: Validation should look at the output of transformations

docs/src/main/asciidoc/inc/swagger/core/paths.adoc, parent/pom.xml, runtime/modules/java/service/pom.xml, runtime/modules/json/service/pom.xml, runtime/modules/xml/service/pom.xml, runtime/service/pom.xml
=> fix: Migrate to resteasy

docs/pom.xml, docs/src/main/asciidoc/inc/swagger/core/definitions.adoc, docs/src/main/asciidoc/inc/swagger/core/paths.adoc, parent/pom.xml, runtime/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, runtime/modules/java/core/src/main/java/io/atlasmap/java/inspect/ClassInspectionService.java, runtime/modules/java/service/pom.xml, runtime/modules/java/service/src/main/java/io/atlasmap/java/service/JavaService.java, runtime/runtime/pom.xml, runtime/service/pom.xml, runtime/service/src/main/java/io/atlasmap/service/AtlasLibraryLoader.java, runtime/service/src/main/java/io/atlasmap/service/AtlasService.java, runtime/service/src/test/java/io/atlasmap/service/AtlasServiceTest.java, runtime/service/src/test/resources/upload/META-INF/services/io.atlasmap.api.AtlasFieldAction, runtime/service/src/test/resources/upload/io/atlasmap/service/my/MyFieldActions.java
=> feat: Update ClassInspection service to consider user-provided jars

camel/src/main/java/org/apache/camel/component/atlasmap/AtlasComponent.java, camel/src/main/java/org/apache/camel/component/atlasmap/AtlasEndpoint.java, camel/src/test/java/org/apache/camel/component/atlasmap/AtlasMapMultiDocsTest.java, camel/src/test/resources/org/apache/camel/component/atlasmap/AtlasMapMultiDocsTest-context.xml
=> fix: Support multiple source Documents via java.util.Map IN message body

atlasmap-maven-plugin/src/main/java/io/atlasmap/maven/GenerateInspectionsMojo.java, lib/core/src/main/java/io/atlasmap/core/AtlasPath.java, lib/core/src/test/java/io/atlasmap/core/AtlasPathTest.java, lib/modules/java/core/src/main/java/io/atlasmap/java/core/JavaFieldReader.java, lib/modules/java/core/src/main/java/io/atlasmap/java/core/JavaFieldWriter.java, lib/modules/java/core/src/test/java/io/atlasmap/java/core/BaseJavaFieldReaderTest.java, lib/modules/java/core/src/test/java/io/atlasmap/java/core/BaseJavaFieldWriterTest.java, lib/modules/java/core/src/test/java/io/atlasmap/java/core/JavaFieldReaderTest.java, lib/modules/java/core/src/test/java/io/atlasmap/java/core/JavaFieldWriterTest.java, lib/modules/java/core/src/test/java/io/atlasmap/java/core/JavaWriterUtilTest.java, lib/modules/java/module/src/main/java/io/atlasmap/java/module/JavaModule.java, lib/modules/json/core/src/main/java/io/atlasmap/json/core/JsonFieldReader.java, lib/modules/json/core/src/main/java/io/atlasmap/json/core/JsonFieldWriter.java, lib/modules/json/core/src/main/java/io/atlasmap/json/inspect/JsonInspectionService.java, lib/modules/json/core/src/main/java/io/atlasmap/json/inspect/JsonInstanceInspector.java, lib/modules/json/core/src/main/java/io/atlasmap/json/inspect/JsonSchemaInspector.java, lib/modules/json/core/src/test/java/io/atlasmap/json/core/JsonFieldReaderTest.java, lib/modules/json/core/src/test/java/io/atlasmap/json/core/JsonFieldWriterTest.java, lib/modules/json/core/src/test/java/io/atlasmap/json/inspect/JsonInstanceInspectorTest.java, lib/modules/json/core/src/test/java/io/atlasmap/json/inspect/JsonSchemaInspectorTest.java, lib/modules/json/service/src/main/java/io/atlasmap/json/service/JsonService.java, lib/modules/xml/core/src/main/java/io/atlasmap/xml/inspect/XmlInspectionService.java, lib/modules/xml/core/src/main/java/io/atlasmap/xml/inspect/XmlInstanceInspector.java, lib/modules/xml/core/src/main/java/io/atlasmap/xml/inspect/XmlSchemaInspector.java
=> feat: Collection as a Document root - Json Instance

lib/modules/json/core/src/main/java/io/atlasmap/json/inspect/JsonSchemaInspector.java, lib/modules/json/core/src/test/java/io/atlasmap/json/inspect/JsonSchemaInspectorTest.java, lib/modules/json/core/src/test/resources/inspect/schema/topmost-array-object.json
=> feat: Collection as a Document root - Json Schema

ui/src/app/lib/atlasmap-data-mapper/services/document-management.service.ts
=> fix: Correct schema and instance identification.  Fixes: #708

.gitignore, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, lib/core/src/test/java/io/atlasmap/core/DefaultAtlasFieldActionsServiceTest.java, lib/itests/core/src/test/java/io/atlasmap/core/issue/PrependAppendTest.java, lib/itests/core/src/test/resources/mappings/issue/prepend-append-mapping.xml
=> fix: Relax parameter type constraint on FieldAction

lib/model/src/main/java/io/atlasmap/v2/ActionsJsonDeserializer.java, ui/src/app/lib/atlasmap-data-mapper/common/data-mapper-util.ts, ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
=> fix: Correct creation/ consumption of JSON for custom field actions.

ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.html
=> fix: Correct hover help placement bubble for import icon.

ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.ts
=> fix: Correct compound select drag&drop mappings

ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action.component.ts
=> Issue 96: Provide display name for transformation parameters

ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.html
=> fix: Move tooltip for delete icon to top from left to avoid flickering

ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-list-field.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-list.component.html
=> fix: Fix truncated tool tip in mappings table.

standalone/pom.xml
=> chore: Update from image URI

ui/src/app/lib/atlasmap-data-mapper/models/field.model.ts
=> fix: Wrong name for the constant to remove - first letter uppercased

lib/service/pom.xml, lib/service/src/main/java/io/atlasmap/service/AtlasLibraryLoader.java, lib/service/src/main/java/io/atlasmap/service/AtlasService.java, lib/service/src/test/java/io/atlasmap/service/AtlasServiceTest.java, lib/service/src/test/resources/log4j2.xml
=> fix: CNFE: io.atlasmap.api.AtlasFieldAction when uploading library

ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
=> fix: Correct a potential NPE in mapping validation response.

ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css
Fixes: #769 
This was actually affecting the Namespace view also
=> fix: the p and g of Mappings is truncated in mapping table view

ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.html
=> fix: Cannot change the settings when clicking on the checkbox

ui/src/app/lib/atlasmap-data-mapper/components/class-name.component.html, ui/src/app/lib/atlasmap-data-mapper/components/class-name.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/constant-field-edit.component.html, ui/src/app/lib/atlasmap-data-mapper/components/constant-field-edit.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/field-edit.component.html, ui/src/app/lib/atlasmap-data-mapper/components/field-edit.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/lookup-table.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-selection.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/modal-window.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/namespace-edit.component.html, ui/src/app/lib/atlasmap-data-mapper/components/namespace-edit.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/property-field-edit.component.html, ui/src/app/lib/atlasmap-data-mapper/components/property-field-edit.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/template-edit.component.html, ui/src/app/lib/atlasmap-data-mapper/components/template-edit.component.ts
=> chore: Set initial focus on a first input element for modal components

ui/src/app/lib/atlasmap-data-mapper/components/line-machine.component.ts, ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
The mappings XML file did not have a chance to complete its update before the UI went
to look for it.  Similar issue with fetching field actions.  Synchronized both.
Fixes: #803
=> fix: Correct missing mapping lines from large schema document mappings.

ui/src/app/lib/atlasmap-data-mapper/components/constant-field-edit.component.html, ui/src/app/lib/atlasmap-data-mapper/components/property-field-edit.component.html
=> fix: fix CSS class for constant/property field type pull down

ui/src/app/lib/atlasmap-data-mapper/components/modal-window.component.ts
=> fix: Cast error on default modal window

ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.ts
=> fix: Transformation is duplicated

coverage-report/pom.xml, lib/core/src/main/java/io/atlasmap/core/AtlasPath.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java, lib/itests/core/pom.xml, lib/itests/core/src/test/java/io/atlasmap/itests/core/DefaultAtlasContextTest.java, lib/itests/core/src/test/java/io/atlasmap/itests/core/issue/AtlasMap846Test.java, lib/itests/core/src/test/java/io/atlasmap/itests/core/issue/Item.java, lib/itests/core/src/test/java/io/atlasmap/itests/core/issue/TargetClass.java, lib/itests/core/src/test/resources/log4j2.xml, lib/itests/core/src/test/resources/mappings/issue/atlasmap-846-mapping.json, lib/modules/java/core/src/main/java/io/atlasmap/java/core/JavaFieldWriter.java, lib/modules/java/core/src/main/java/io/atlasmap/java/core/JavaFieldWriterUtil.java, lib/modules/java/module/src/main/java/io/atlasmap/java/module/JavaModule.java, lib/modules/json/core/src/main/java/io/atlasmap/json/core/JsonFieldWriter.java, lib/modules/json/module/src/main/java/io/atlasmap/json/module/JsonModule.java, lib/modules/xml/core/src/main/java/io/atlasmap/xml/core/XmlFieldWriter.java, lib/modules/xml/core/src/main/java/io/atlasmap/xml/core/XmlPath.java, lib/modules/xml/module/src/main/java/io/atlasmap/xml/module/XmlModule.java
=> fix: Create empty collection at target even when there's no data to map

lib/modules/json/module/src/main/java/io/atlasmap/json/module/JsonModule.java, lib/modules/xml/module/src/main/java/io/atlasmap/xml/module/XmlModule.java
=> fix: Module validation doesn't work for JSON and XML

docs/src/main/asciidoc/developer-guide/swagger/core/definitions.adoc, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java, lib/model/src/main/java/io/atlasmap/v2/FormulaExpression.java, lib/model/src/main/java/io/atlasmap/v2/Mapping.java, lib/model/src/test/java/io/atlasmap/v2/BaseMarshallerTest.java
=> feat: Extend mapping model to deliver conditional mapping expression

camel/src/main/java/org/apache/camel/component/atlasmap/AtlasEndpoint.java, camel/src/test/java/org/apache/camel/component/atlasmap/AtlasEndpointTest.java, lib/api/src/main/java/io/atlasmap/api/AtlasContext.java
=> fix: Cannot execute AtlasSession created by the other AtlasContext

ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css, ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.html, ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
=> feat: [UI] Add expression entry widget for conditional mapping

lib/model/src/main/java/io/atlasmap/v2/AreaUnitType.java, lib/model/src/main/java/io/atlasmap/v2/DistanceUnitType.java, lib/model/src/main/java/io/atlasmap/v2/MassUnitType.java, lib/model/src/main/java/io/atlasmap/v2/VolumeUnitType.java
=> fix: *UnitType enum models should use value instead of name

lib/core/src/main/java/io/atlasmap/functions/ISEMPTY.java, lib/core/src/main/resources/META-INF/services/io.atlasmap.spi.FunctionFactory, lib/core/src/test/java/io/atlasmap/actions/ExpressionFieldActionTest.java
=> feat: Add ISEMPTY function

ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.html, ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
=> fix: Update cond mapping toolbar icon and implement drag&drop

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java, lib/core/src/test/java/io/atlasmap/core/DefaultAtlasContextTest.java
=> fix: processPreview() doesn't handle inputFieldGroup

lib/core/src/main/java/io/atlasmap/actions/ExpressionFieldAction.java, lib/core/src/test/java/io/atlasmap/actions/ExpressionFieldActionTest.java
=> fix: Avoid preview error with empty expression

parent/pom.xml, standalone/pom.xml
fixes #913
Note: I chose the versions to align with what Fuse & Syndesis already use.
=> fix: No CMD or ENTRYPOINT configured for atlasmap docker image

ui/src/app/lib/atlasmap-data-mapper/components/expression.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/expression.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
=> fix: expression serialize/deserialize is broken

ui/src/app/lib/atlasmap-data-mapper/components/expression.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/expression.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts
Mapped source fields are added into expression automatically when expression is turned on. If all reference is removed from expression, the field is removed from mapping.
Fixes: #869
Fixes: #931
Fixes: #932
=> feat: Sync mapped source fields and expression field reference

ui/src/app/lib/atlasmap-data-mapper/components/expression.component.ts
=> fix: Field drop in expression adds two of them

ui/src/app/lib/atlasmap-data-mapper/components/expression.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/modal-error-window.component.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
Fixes: #941 #944
Need to revisit fieldSelected() in the mapping-management service at some point and attempt to refactor some of the logic - overly complex.
=> fix: Correct auto completion mapped field conditional expression errors.

ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
=> fix: Correct null ref in preview mode error catch-block.

lib/modules/java/core-test/pom.xml, pom.xml
=> Add <name> to <repository/> tags

ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css, ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-detail.component.html, ui/src/styles.scss
=> fix: Modify AtlasMap geometry to scale correctly to VSCode

ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css, ui/src/app/lib/atlasmap-data-mapper/components/expression.component.html, ui/src/app/lib/atlasmap-data-mapper/components/expression.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/expression.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
Added key input support at caret position. Another commit will follow for Backspace/Delete support.
=> fix: [UI] Insert/Delete text into/from where the caret is (#928)

ui/src/app/lib/atlasmap-data-mapper/components/expression.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/expression.model.ts
=> fix: handle caret position for backspace/delete (#928)

ui/src/app/lib/atlasmap-data-mapper/components/expression.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.html, ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts
=> fix: cond-expr: Selecting a new mapping with cond expr enabled show old

ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
=> chore: Show Document name in error message

lib/core/src/main/java/io/atlasmap/core/validate/MappingFieldPairValidator.java, lib/core/src/test/java/io/atlasmap/actions/ExpressionFieldActionTest.java, lib/itests/core/src/test/java/io/atlasmap/itests/core/MultiplicityTransformationTest.java, lib/itests/core/src/test/resources/mappings/atlasmapping-multiplicity-transformation-expression.json
=> fix: Conditional Mapping: no converter is available validation error

ui/src/app/lib/atlasmap-data-mapper/components/expression.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/expression.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts, ui/test-resources/schema/JSONInstanceSource.json
fix: Support in-line insertion of auto-completed source fields in a conditional expression.
Fixes: #969
=> fix: Support in-line insertion of auto-completed source fields in a conditional expression. Fixes: #969

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, lib/itests/core/src/test/java/io/atlasmap/itests/core/MultiplicityTransformationTest.java, lib/itests/core/src/test/resources/mappings/atlasmapping-multiplicity-transformation-expression.json
=> fix: NPE from backend when filling mapping preview

ui/src/app/lib/atlasmap-data-mapper/models/expression.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
=> fix: Correct conditional expression field node location on reload.

ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
=> fix: mappingUpdated event is not triggered when mapping is established

ui/src/app/lib/atlasmap-data-mapper/components/expression.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/expression.model.ts
=> fix: Unable to specify one field twice

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java, lib/core/src/test/java/io/atlasmap/core/DefaultAtlasContextTest.java, lib/service/src/main/java/io/atlasmap/service/AtlasService.java
=> fix: Mapping preview shows nothing when split involved

ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
fix: Add new fields to the end of the mapping when adding through the mapping details panel.
Fixes: #1018
=> fix: Add new fields to the end of the mapping when adding through the mapping details panel.

ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css
=> fix: Correct mapping details scrollbar for sources and targets windows.

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, lib/core/src/test/java/io/atlasmap/core/DefaultAtlasContextTest.java
=> fix: Concatenate ignores gaps

ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
=> fix: Correct sync issues with field/ mapping removal.

.circleci/config.yml, parent/pom.xml, standalone/pom.xml, standalone/src/test/java/io/atlasmap/standalone/E2ETest.java
=> fix: Introduce e2e test (#1040)

standalone/pom.xml, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/simple-mapping.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/expression.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/field-action.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
=> fix: [UI] Hold field index in MappedField but not as a action parameter

ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
=> fix: Correct sync issues with field selection/ validation.

lib/modules/java/core/src/main/java/io/atlasmap/java/core/JavaFieldReader.java, lib/modules/json/core/src/main/java/io/atlasmap/json/core/JsonFieldReader.java, lib/modules/json/core/src/test/java/io/atlasmap/json/core/JsonFieldReaderTest.java, lib/modules/json/module/src/main/java/io/atlasmap/json/module/JsonModule.java, lib/modules/xml/core/src/main/java/io/atlasmap/xml/core/XmlFieldReader.java, lib/modules/xml/core/src/test/java/io/atlasmap/xml/core/XmlFieldReaderTest.java, lib/modules/xml/module/src/main/java/io/atlasmap/xml/module/XmlModule.java
=> fix: Empty doc results in stacktrace

ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-selection-section.component.html
=> fix: Select Mapping dialog is broken

ui/src/app/atlasmap-navbar.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-example-host.component.spec.ts, ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts, ui/src/app/lib/atlasmap-data-mapper/data-mapper.module.ts, ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/document-definition.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/file-management.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.spec.ts, ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
=> fix: [UI] Split file handling into file-management.service

ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts
Fixes: #1078
Note: due to #1079 it seems duplicated target check doesn't work for me. We should address it separately.
=> fix: Already mapped target check should look at docId and path

ui/src/app/lib/atlasmap-data-mapper/models/field-action.model.ts
=> fix: [UI] Don't show multiplicity transformations where not eligible

ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-container.component.ts
=> fix: Mapping details search box pulldown shows only leaf names

ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.html, ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-container.component.ts
=> fix: Add a label for topmost collection field

ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.html, ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-container.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts
=> fix: No multiple mappings to same target field check fails sometimes

lib/modules/java/service/src/main/java/io/atlasmap/java/service/JavaService.java, ui/src/app/lib/atlasmap-data-mapper/common/config.types.ts, ui/src/app/lib/atlasmap-data-mapper/components/class-name.component.html, ui/src/app/lib/atlasmap-data-mapper/components/class-name.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/document-definition.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/document-management.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
=> feat: Support topmost collection Java object for standalone

ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts
=> fix: Remove trailing padding fields.

docs/src/main/asciidoc/user-guide/index.adoc, docs/src/main/asciidoc/user-guide/topics/basics.adoc
Hi @pleacu, @TovaCohen,
I'm adding some description about mapping basics into user-doc, would you take a look?
=> chore: Added basics to user-doc

ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action-argument.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-container.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/transition-selection.component.html
=> fix: Optimize the space usage in the mapping detail panel.

ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
=> fix: Backport fix to removeMapping in the mapping-management service,

ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
=> fix: [UI] undefined error when clicking a field

ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css
=> fix: wrong displaying of conditional mapping expression

ui/src/app/lib/atlasmap-data-mapper/components/modal-error-window.component.ts, ui/src/app/lib/atlasmap-data-mapper/services/error-handler.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/field-action.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
=> fix: Correct when the UI queries for field actions.

ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css
=> fix: Set default background color for modal windows to white.

ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
=> fix: Do not error if no mapping file is found on initialization.

ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.ts
=> fix: Last added document disappears after refreshing website

ui/src/app/lib/atlasmap-data-mapper/components/expression.component.html, ui/src/app/lib/atlasmap-data-mapper/components/expression.component.ts
Fixes: #1008
SInce we trap on mouse-leave no need to track onBlur.
=> fix: Clear search mode when caret leaves expression box/ pulldown.

ui/src/app/lib/atlasmap-data-mapper/models/mapping-definition.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
=> fix: Correct UI null ptr refs on init.

ui/src/app/lib/atlasmap-data-mapper/components/expression.component.ts
=> fix: Correct condition expression search algorithm.

docs/src/main/asciidoc/developer-guide/swagger/core/paths.adoc, lib/service/src/main/java/io/atlasmap/service/AtlasService.java, ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
=> fix: Call runtime service 'ping' interface to determine it's there.

ui/src/app/lib/atlasmap-data-mapper/common/data-mapper-util.ts, ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css, ui/src/app/lib/atlasmap-data-mapper/components/expression.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-container.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-container.component.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts, ui/test-resources/json/schema/JSONSchemaLong.json
=> fix: Add code to fit long path names into pull downs

docs/publish-docs.sh, docs/src/main/asciidoc/developer-guide/index.adoc, ui/package.json, ui/pom.xml, ui/yarn.lock
It should link from here - https://docs.atlasmap.io/developer-guide
Fixes: #1178
=> chore: Introduce compodoc and link from developer-guide

lib/core/src/main/java/io/atlasmap/actions/StringComplexFieldActions.java, lib/core/src/test/java/io/atlasmap/core/DefaultAtlasContextTest.java
relates: https://github.com/atlasmap/atlasmap/issues/1020
=> fix: Concatenate ingores first Gap

lib/api/src/main/java/io/atlasmap/spi/AtlasActionProcessor.java, lib/core/src/main/java/io/atlasmap/actions/DateFieldActions.java, lib/core/src/main/java/io/atlasmap/actions/StringComplexFieldActions.java, lib/core/src/main/java/io/atlasmap/actions/StringSimpleFieldActions.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action.component.ts
=> fix: Date transformations missing in date types

ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.html
=> fix: Correct 'slightly shifted' tooltip.

ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts
=> fix: Don't blow up src/tgt docs fed from Syndesis

ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts, ui/src/app/lib/atlasmap-data-mapper/services/file-management.service.ts
=> fix: Clear docs and reset mappings on rset all and import ADM catalog.

ui/src/app/lib/atlasmap-data-mapper/models/field.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.spec.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.spec.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
=> fix: Ban nested collection field until #435 is addressed

ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.ts, ui/src/app/lib/atlasmap-data-mapper/models/expression.model.ts, ui/src/app/lib/atlasmap-data-mapper/models/mapping.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-serializer.service.ts
=> fix: Handle constants/properties/field actions in serialize/deserialize.

ui/package.json, ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.spec.ts, ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts, ui/yarn.lock
=> fix: InitializationService UT is not working

ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.spec.ts
=> fix: Add 'reset all' test to toolbar component spec.

ui/src/app/lib/atlasmap-data-mapper/utils/mapping-serializer.spec.ts, ui/src/app/lib/atlasmap-data-mapper/utils/mapping-serializer.ts
=> fix: Multiplicity transformations aren't saved in mapping.json

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, lib/itests/core/pom.xml, lib/itests/core/src/test/java/io/atlasmap/itests/core/MultiplicityTransformationTest.java, lib/itests/core/src/test/resources/mappings/atlasmapping-multiplicity-transformation-concatenate-types.json
=> fix: Should convert collection elements before transformation

lib/core/src/main/java/io/atlasmap/core/validate/MappingFieldPairValidator.java, lib/modules/java/module/src/test/java/io/atlasmap/java/module/JavaValidationServiceTest.java, lib/modules/json/module/src/test/java/io/atlasmap/json/module/JsonValidationServiceTest.java, lib/modules/xml/module/src/test/java/io/atlasmap/xml/module/XmlValidationServiceTest.java, ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-error.component.ts, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-detail.component.html, ui/src/app/lib/atlasmap-data-mapper/services/error-handler.service.ts
Fixes: #1184
fix: Remove "... is supported" validation log
Fixes: #1244
=> fix: Update validation when transformation is selected

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, lib/core/src/test/java/io/atlasmap/core/BaseDefaultAtlasContextTest.java, lib/core/src/test/java/io/atlasmap/core/DefaultAtlasContextTest.java
=> fix: Preview: Conversion error for collection field

lib/core/src/test/java/io/atlasmap/actions/ExpressionFieldActionTest.java, lib/expression/src/main/java/io/atlasmap/expression/internal/ComparisonExpression.java, lib/expression/src/test/java/io/atlasmap/expression/ExpressionTest.java, ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts, ui/src/app/lib/atlasmap-data-mapper/utils/mapping-serializer.spec.ts, ui/src/app/lib/atlasmap-data-mapper/utils/mapping-serializer.ts
Fixes: #1234
fix: Unable to map expression index to field node
Fixes: #1249
=> fix: NUMBER FieldType in expressions not evaluating correctly

lib/itests/core/src/test/java/io/atlasmap/itests/core/MultiplicityTransformationTest.java, lib/itests/core/src/test/resources/mappings/atlasmapping-multiplicity-transformation-add.json, lib/modules/java/core/src/main/java/io/atlasmap/java/inspect/ClassInspectionService.java, lib/modules/java/core/src/test/java/io/atlasmap/java/inspect/ClassValidationUtil.java, lib/modules/java/test-model/src/main/java/io/atlasmap/java/test/BaseFlatPrimitiveClass.java, lib/modules/java/test-model/src/main/java/io/atlasmap/java/test/FlatPrimitiveInterface.java
Fixes: #1254
Also added List<Integer> UT for #1241
=> fix: Java method inspection doesn't detect List as a collection field

parent/pom.xml
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
=> Use https instead of http for Maven repositories #1260

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, lib/itests/core/src/test/java/io/atlasmap/itests/core/issue/AtlasMap1241Test.java, lib/itests/core/src/test/resources/mappings/issue/atlasmap-1241-mapping.json
=> fix: many-to-one transformation for collection source doesn't work

ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts, ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.spec.ts, ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.ts, ui/src/app/lib/atlasmap-data-mapper/utils/mapping-serializer.ts, ui/test-resources/json/schema/old-action-source.json, ui/test-resources/json/schema/old-action-target.json, ui/test-resources/mapping/atlasmapping-old-action.json
=> fix: Ghost field is added when opening existing mapping in Syndesis

parent/pom.xml
=> chore: Update asciidoctorj

pom.xml
=> chore: Update maven-javadoc-plugin

ui/package.json, ui/src/app/lib/atlasmap-data-mapper/services/initialization.service.spec.ts, ui/yarn.lock
=> chore: Update @types/jasmine

ui/src/app/lib/atlasmap-data-mapper/utils/mapping-serializer.spec.ts, ui/src/app/lib/atlasmap-data-mapper/utils/mapping-serializer.ts
=> fix: UI serializer still uses old action schema

ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.css, ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.html, ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.html, ui/src/app/lib/atlasmap-data-mapper/components/document-field-detail.component.html, ui/src/app/lib/atlasmap-data-mapper/components/field-edit.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action-argument.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-action.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-container.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-field-detail.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/mapping-list-field.component.html, ui/src/app/lib/atlasmap-data-mapper/components/mapping/transition-selection.component.html, ui/src/app/lib/atlasmap-data-mapper/components/namespace-edit.component.html, ui/src/app/lib/atlasmap-data-mapper/components/namespace-list.component.html, ui/src/app/lib/atlasmap-data-mapper/components/toolbar.component.html, ui/src/app/lib/atlasmap-data-mapper/models/transition.model.ts
=> fix: Refactor all embedded css style info out of html files.

pom.xml
=> chore: Update maven-checkstyle-plugin

lib/itests/core/src/test/java/io/atlasmap/itests/core/issue/AtlasMap1408Test.java, lib/itests/core/src/test/resources/mappings/issue/atlasmap-1408-mapping.json, lib/itests/core/src/test/resources/mappings/issue/atlasmap-1408-source.xml, lib/itests/core/src/test/resources/mappings/issue/atlasmap-1408-target.json, lib/modules/xml/core/src/main/java/io/atlasmap/xml/core/XmlFieldReader.java
=> fix: NPE when XML field reader read namespace

ui/src/app/lib/atlasmap-data-mapper/utils/mapping-serializer.ts
=> fix: UI fails to serialize CustomAction

ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-document.component.css, ui/src/app/lib/atlasmap-data-mapper/components/document-definition.component.ts
=> fix: Correct lines when panel search reduces fields.

ui-react/packages/atlasmap-provider/src/utils/to-ui-models-util.ts, ui-react/packages/atlasmap-ui/src/canvas/CanvasObject.tsx, ui-react/packages/atlasmap-ui/src/models.ts, ui-react/packages/atlasmap-ui/src/views/sourcetargetmapper/DragLayer.tsx, ui-react/packages/atlasmap-ui/src/views/sourcetargetmapper/FieldElement.tsx, ui-react/packages/atlasmap-ui/src/views/sourcetargetmapper/FieldGroup.tsx, ui-react/packages/atlasmap-ui/src/views/sourcetargetmapper/FieldGroupList.tsx, ui-react/packages/atlasmap-ui/src/views/sourcetargetmapper/FieldsBox.tsx, ui-react/packages/atlasmap-ui/src/views/sourcetargetmapper/MappingList.tsx, ui-react/packages/atlasmap-ui/src/views/sourcetargetmapper/SourceTargetMapper.tsx, ui-react/packages/atlasmap-ui/src/views/sourcetargetmapper/index.ts, ui-react/packages/atlasmap-ui/stories/utils/fromJava.ts, ui-react/packages/atlasmap-ui/stories/utils/fromJson.ts, ui-react/packages/atlasmap-ui/stories/utils/fromXML.ts, ui-react/packages/atlasmap-ui/stories/views/sourcetargetmapper/FieldGroup.stories.tsx, ui-react/packages/atlasmap-ui/stories/views/sourcetargetmapper/FieldGroupList.stories.tsx
change the d&d layer apprearance, make the documents more visible, remove visual components from the provider
=> chore(ui-react): some ui tweaks

parent/pom.xml, standalone/src/main/java/io/atlasmap/standalone/Application.java, standalone/src/test/java/io/atlasmap/standalone/E2ETest.java, standalone/src/test/java/io/atlasmap/standalone/RestTest.java
=> chore: Update to Camel-2.23 + SpringBoot 2.1

ui-react/packages/atlasmap-provider/src/components/toolbar/MapperUtilsToolbar.ts, ui-react/packages/atlasmap-provider/src/services/file-management.service.ts, ui-react/packages/atlasmap-provider/src/useAtlasmap.tsx, ui-react/packages/atlasmap-standalone/src/App.tsx, ui-react/packages/atlasmap-ui/src/mapper/Mapper.tsx, ui-react/packages/atlasmap-ui/src/mapper/MapperContextToolbar.tsx
Partial fix for i1523
Needs react modal/ dialog support for export file name.
=> fix: Add glue layer support for export icon.

ui-react/packages/atlasmap-provider/src/services/document-management.service.ts, ui-react/packages/atlasmap-provider/src/useAtlasmap.tsx
document service to handle both a raw JSON buffer or a JSON object
ref i1523
=> Remove unneeded useCallback for export Atlas file and correct

ui-react/packages/atlasmap-provider/src/AtlasmapProvider.tsx, ui-react/packages/atlasmap-provider/src/components/document/document-util.ts, ui-react/packages/atlasmap-provider/src/components/toolbar/toolbar-util.ts, ui-react/packages/atlasmap-ui/src/atlasmap/Atlasmap.tsx, ui-react/packages/atlasmap-ui/src/atlasmap/AtlasmapContextToolbar.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldsBoxHeader.tsx
Still needs modal/dialog support - i1553
Small refactoring.
=> Add glue layer support for instance/ schema file import

ui-react/packages/atlasmap-provider/src/AtlasmapProvider.tsx, ui-react/packages/atlasmap-provider/src/components/document/document-util.ts, ui-react/packages/atlasmap-provider/src/components/toolbar/toolbar-util.ts, ui-react/packages/atlasmap-provider/src/services/initialization.service.ts, ui-react/packages/atlasmap-standalone/src/App.tsx, ui-react/packages/atlasmap-ui/src/atlasmap/Atlasmap.tsx
Fixes: #1555
Addressed previous pull issues.
=> fix: wire glue layer for document delete

ui-react/packages/atlasmap-ui/src/atlasmap/Atlasmap.tsx, ui-react/packages/atlasmap-ui/src/atlasmap/components/DocumentField.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/components/FieldGroup.tsx
=> feat(react-ui): make fields more visible when a mapping is selected

ui-react/packages/atlasmap-provider/src/AtlasmapProvider.tsx, ui-react/packages/atlasmap-provider/src/index.ts, ui-react/packages/atlasmap-provider/src/utils/to-ui-models-util.ts, ui-react/packages/atlasmap-standalone/src/App.tsx, ui-react/packages/atlasmap-ui/src/atlasmap/Atlasmap.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/models.ts, ui-react/packages/atlasmap-ui/stories/Atlasmap.stories.tsx, ui-react/packages/atlasmap-ui/stories/utils/fromJava.ts, ui-react/packages/atlasmap-ui/stories/utils/fromJson.ts, ui-react/packages/atlasmap-ui/stories/utils/fromXML.ts, ui-react/packages/atlasmap-ui/stories/views/CanvasView/FieldGroup.stories.tsx
=> feat(react-ui): wire the mapping preview

ui-react/packages/atlasmap-provider/src/utils/to-ui-models-util.ts, ui-react/packages/atlasmap-ui/src/atlasmap/Atlasmap.tsx, ui-react/packages/atlasmap-ui/src/atlasmap/components/DocumentField.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/components/Document.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/components/MappingElement.tsx, ui-react/packages/atlasmap-ui/src/views/CanvasView/models.ts, ui-react/packages/atlasmap-ui/stories/sampleData.tsx, ui-react/packages/atlasmap-ui/stories/views/CanvasView/MappingElement.stories.tsx
Simplify the mapped element UI.
Let the document start fully collapsed and improve the auto-open
feature, with autoscroll to the field.
=> feat(react-ui): quality of life changes

parent/pom.xml
https://issues.redhat.com/browse/ENTESB-11208
=> Add dependency on logback-classic

ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.spec.ts
=> fix: UI test failure in mapping-management.service.spec.ts

ui-react/packages/atlasmap-provider/src/components/toolbar/toolbar-util.ts, ui-react/packages/atlasmap-standalone/src/App.tsx, ui-react/packages/atlasmap-standalone/src/useSingleInputDialog.tsx
Fixes: #1523
Contains previous comment fixes.
Note - ui-react is broken after the community push yesterday (need to add mappingDefinitionId to all of the REST calls).  Would like to get this pushed in first.
=> fix: complete dialog portion of export catalog (ADM)

docs/src/main/asciidoc/developer-guide/swagger/core/paths.adoc, lib/service/src/main/java/io/atlasmap/service/AtlasService.java, ui-react/packages/atlasmap-provider/src/services/file-management.service.ts, ui-react/packages/atlasmap-provider/src/services/mapping-management.service.ts
=> fix: add support for old style REST apis (no mapping ID)

lib/modules/json/core/src/main/java/io/atlasmap/json/inspect/JsonSchemaInspector.java, lib/modules/json/core/src/test/java/io/atlasmap/json/inspect/JsonSchemaInspectorTest.java, lib/modules/json/core/src/test/resources/inspect/schema/ref.json
=> feat: JSON schema: support local definition reference

lib/service/src/main/java/io/atlasmap/service/AtlasService.java
=> fix: Mappings of an imported ADM catalog can be lost

lib/service/src/main/java/io/atlasmap/service/AtlasService.java
=> fix: regression: older .adm file fails to be loaded

ui-react/packages/atlasmap-standalone/src/App.tsx, ui-react/packages/atlasmap-standalone/src/useSingleInputDialog.tsx
Fixes: #1592
This matches the user experience on the angular side.
=> fix: add placeholder support for export

ui-react/packages/atlasmap-provider/src/AtlasmapProvider.tsx, ui-react/packages/atlasmap-provider/src/components/toolbar/toolbar-util.ts, ui-react/packages/atlasmap-standalone/src/App.tsx
=> fix: add challenge dialog to import document if it already exists

ui-react/packages/atlasmap-standalone/public/index.html, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/DocumentFieldPreview.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/DocumentFieldPreviewResults.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/DragLayer.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapContextToolbar.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/MappingDetails/MappingField.tsx, ui-react/packages/atlasmap-ui/src/Canvas/Canvas.tsx, ui-react/packages/atlasmap-ui/src/Canvas/CanvasContext.tsx, ui-react/packages/atlasmap-ui/src/Canvas/CanvasLink.tsx, ui-react/packages/atlasmap-ui/src/Canvas/CanvasObject.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/CanvasViewLayoutProvider.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/Box.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/CanvasViewCanvas.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/CanvasViewToolbar.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/Document.tsx, ui-react/packages/atlasmap-ui/src/common/useDimensions.ts
=> chore(react-ui): performance improvements

ui-react/packages/atlasmap-ui/src/Canvas/CanvasObject.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/Box.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/Document.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/DocumentProvider.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/FieldElement.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/FieldGroup.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/FieldsBox.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/index.ts
Lines should be contained in the document they are part of.
=> chore(react-ui): fix wrong line boundaries detection

atlasmap-maven-plugin/src/main/java/io/atlasmap/maven/GenerateFieldActionsMojo.java, lib/core/src/main/java/io/atlasmap/actions/ExpressionFieldAction.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasContextFactory.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasConversionService.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasFunctionResolver.java, lib/core/src/main/java/io/atlasmap/core/validate/BaseModuleValidationService.java, lib/core/src/test/java/io/atlasmap/actions/ExpressionFieldActionTest.java, lib/core/src/test/java/io/atlasmap/core/DefaultAtlasFieldActionsServiceTest.java, lib/expression/src/test/java/io/atlasmap/expression/ExpressionTest.java, lib/modules/java/module/src/test/java/io/atlasmap/java/module/JavaValidationServiceTest.java, lib/modules/json/module/src/test/java/io/atlasmap/json/module/BaseJsonValidationServiceTest.java, lib/modules/xml/module/src/test/java/io/atlasmap/xml/module/XmlValidationServiceTest.java
https://github.com/atlasmap/atlasmap/issues/890
=> Fixes #890 Support invoking arbitrary transformation in expression

ui/src/app/lib/atlasmap-data-mapper/components/toolbar/toolbar.component.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.spec.ts, ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts
https://github.com/atlasmap/atlasmap/issues/1185
I'll include ui-react changes as as follow up once merged.
=> Fixes #1185 Support collection field in expression

ui/build.sh, ui/package.json, ui/pom.xml, ui/scripts/inline-css.ts, ui/src/app/lib/atlasmap-data-mapper/components/app/_data-mapper-app.component.css, ui/src/app/lib/atlasmap-data-mapper/components/app/data-mapper-app.component.ts, ui/yarn.lock
=> fix: ng-packagr doesn't support CSS @import

ui-react/packages/atlasmap-core/src/models/mapping.model.ts, ui-react/packages/atlasmap-core/src/utils/to-ui-models-util.ts
Fixes: #1659
The to-ui-models-util.ts change was because I ran into an undefined error twice.
=> fix: notify mapping updated after mapped field removal

ui/src/app/lib/atlasmap-data-mapper/components/app/data-mapper-error.component.ts
=> fix: check for a valid mapping object in the error component

ui-react/packages/atlasmap-core/src/services/mapping-management.service.ts, ui-react/packages/atlasmap-core/test/mapping-management.service.spec.ts
@riccardo-forina, I've carried over just the service code. I don't see toggleExpressionMode being called in any react-ui component yet, am I right?
=> Porting #1185 to react-ui

standalone/src/main/java/io/atlasmap/standalone/SecurityConfiguration.java
used fro integration in VS Code, Eclipse Theia and Eclipse Che
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
=> Provide option to disable Frame Options #1501

ui/src/app/lib/atlasmap-data-mapper/models/config.model.ts
Fixes: #1669
Tested with Syndesis staging site
=> fix: Validate request with having mappingDefinitionId `undefined`

ui-react/packages/atlasmap-ui/src/CanvasView/components/FieldsBoxHeader.tsx
Fixes: https://issues.redhat.com/browse/ENTESB-12728?filter=12344528
=> Partially fixes ENTESB-12728: Search Icon could be consistent

ui/src/app/lib/atlasmap-data-mapper/components/mapping-detail/transition-selection.component.html
=> fix: Multiplicity transformation parameter name is placed at wrong place

ui/src/app/lib/atlasmap-data-mapper/components/mapping-detail/transition-selection.component.html
=> fix: Multiplicity transformation cannot be changed

lib/core/src/main/java/io/atlasmap/actions/NumberFieldActions.java, lib/core/src/test/java/io/atlasmap/actions/NumberFieldActionsTest.java
=> fix: Number many-to-one transformations should just ignore null values

ui-react/packages/atlasmap-core/src/utils/filter-fields.ts, ui-react/packages/atlasmap-ui/src/CanvasView/components/FieldsBoxHeader.tsx
Fixes https://issues.redhat.com/browse/ENTESB-12728?filter=12344528
=> fix: ENTESB-12728: Search Icon could be consistent

ui-react/packages/atlasmap-ui/src/CanvasView/components/FieldsBoxHeader.tsx
=> fix: Dropdown menu items should be selectable across entire row

ui-react/packages/atlasmap-core/src/Atlasmap.tsx, ui-react/packages/atlasmap-core/src/AtlasmapMappingDetails.tsx, ui-react/packages/atlasmap-standalone/src/App.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/MappingDetails/MappingAction.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/MappingDetails/MappingField.tsx
=> fix: add support for adding a new transformation (source/target)

ui/src/app/lib/atlasmap-data-mapper/components/mapping-detail/mapping-field-container.component.ts
=> fix: non-unique id error in mapping-field-container.component

ui/src/app/lib/atlasmap-data-mapper/services/mapping-management.service.ts, ui/src/app/lib/atlasmap-data-mapper/utils/mapping-serializer.ts
=> fix: Split doc refs to avoid name confliction between source and target

ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/AtlasmapCanvasView.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapContextToolbar.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapLayout.tsx
Fixes: https://issues.redhat.com/browse/ENTESB-12730?filter=12344528
=> fix: ENTESB-12730: Toolbar position and order

ui-react/packages/atlasmap-core/src/Atlasmap.tsx, ui-react/packages/atlasmap-core/src/AtlasmapMappingDetails.tsx, ui-react/packages/atlasmap-standalone/src/App.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/MappingDetails/MappingAction.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/MappingDetails/MappingField.tsx
=> fix: add support for removing existing field transformations

ui-react/packages/atlasmap-ui/src/CanvasView/components/FieldsBoxHeader.tsx
Fixes the file picker displaying correctly for import of sources/targets
=> partial fix: UI_REACT: correct main toolbar icons

lib/modules/xml/core/src/main/java/io/atlasmap/xml/core/XmlPath.java, lib/modules/xml/core/src/main/java/io/atlasmap/xml/inspect/XmlInstanceInspector.java, lib/modules/xml/core/src/test/java/io/atlasmap/xml/inspect/XmlInstanceInspectionTest.java, lib/modules/xml/core/src/test/resources/inspect/nested-collection-2-instance.xml, lib/modules/xml/model/src/main/java/io/atlasmap/xml/v2/XmlField.java
=> fix: XML instance inspection handles repeating element incorrectly

ui-react/packages/atlasmap-core/src/AtlasmapMappingDetails.tsx, ui-react/packages/atlasmap-core/src/models/field-action.model.ts, ui-react/packages/atlasmap-ui/src/AtlasmapUI/MappingDetails/MappingAction.tsx
=> fix: add support for transformations/ field action arguments

ui-react/packages/atlasmap-core/src/utils/to-ui-models-util.ts, ui-react/packages/atlasmap-ui/src/AtlasmapUI/models.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/FieldGroup.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/models.ts
=> fix: UI_REACT: UI should indicate when containers are collections

ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/DocumentField.tsx
Fixes: [ENTESB-12726](https://issues.redhat.com/browse/ENTESB-12726)
=> fix: ENTESB-12726: Remove source/target behavior

ui-react/packages/atlasmap-core/src/AtlasmapMappingDetails.tsx, ui-react/packages/atlasmap-core/src/services/mapping-management.service.ts, ui-react/packages/atlasmap-core/src/utils/mapping-serializer.ts, ui-react/packages/atlasmap-ui/src/AtlasmapUI/MappingDetails/MappingField.tsx
=> fix: support mapping index modifications

ui-react/packages/atlasmap-core/src/AtlasmapMappingDetails.tsx, ui-react/packages/atlasmap-core/src/AtlasmapProvider.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/MappingDetails/MappingAction.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/MappingDetails/MappingDetails.tsx
Fixes: #1763
@riccardo-forina - the mapping details needs to move to the 'sm' patternfly font family - need help setting the style sheet...
=> fix: support multiplicity transformations

ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapContextToolbar.tsx
Fixes: #1783 
Fixes: [ENTESB-12730](https://issues.redhat.com/browse/ENTESB-12730)
=> fix: UI_REACT: Change toolbar menu separators to spaces

docs/src/main/asciidoc/developer-guide/swagger/core/overview.adoc, docs/src/main/asciidoc/developer-guide/swagger/java/overview.adoc, docs/src/main/asciidoc/developer-guide/swagger/json/overview.adoc, docs/src/main/asciidoc/developer-guide/swagger/xml/overview.adoc, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/AtlasmapCanvasView.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapContextToolbar.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapLayout.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/CanvasViewControlBar.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/index.ts
=> fix: UI_REACT: Move topology buttons to bottom toolbar

ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapContextToolbar.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapLayout.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/CanvasViewControlBar.tsx
=> fix: Freeview button should be moved to bottom toolbar

ui-react/packages/atlasmap-core/src/utils/to-ui-models-util.ts, ui-react/packages/atlasmap-ui/src/AtlasmapUI/models.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/Document.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/FieldGroup.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/models.ts, ui-react/packages/atlasmap-ui/stories/sampleData.tsx, ui-react/packages/atlasmap-ui/stories/utils/fromJava.ts, ui-react/packages/atlasmap-ui/stories/utils/fromJson.ts, ui-react/packages/atlasmap-ui/stories/utils/fromXML.ts, ui-react/packages/atlasmap-ui/stories/views/CanvasView/FieldGroup.stories.tsx
=> fix: UI_REACT: Enable source/target model search

ui-react/packages/atlasmap-core/src/components/field/field-util.ts, ui-react/packages/atlasmap-core/src/models/config.model.ts, ui-react/packages/atlasmap-core/src/models/document-definition.model.ts, ui-react/packages/atlasmap-core/src/react/Atlasmap.tsx, ui-react/packages/atlasmap-core/src/react/AtlasmapProvider.tsx, ui-react/packages/atlasmap-core/src/react/useAtlasmapDialogs.tsx, ui-react/packages/atlasmap-core/src/services/initialization.service.ts, ui-react/packages/atlasmap-core/src/utils/to-ui-models-util.ts, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/AtlasmapCanvasViewSource.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/AtlasmapCanvasViewTarget.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/DocumentField.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/models.tsx, ui-react/packages/atlasmap-ui/src/common/useInputTextSelectDialog.tsx, ui-react/packages/atlasmap-ui/stories/Atlasmap.stories.tsx, ui-react/packages/atlasmap-ui/stories/sampleData.tsx, ui-react/packages/atlasmap-ui/stories/utils/fromJava.ts, ui-react/packages/atlasmap-ui/stories/utils/fromJson.ts, ui-react/packages/atlasmap-ui/stories/utils/fromXML.ts
Fixes: #1815
The edit/delete icons need some location work - will file a new issue for that
=> fix: Add support for edit/ delete constants / properties

ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapUIProvider.tsx, ui-react/packages/atlasmap-ui/src/Canvas/CanvasTransforms.tsx
=> fix: UI_REACT: Mapping details should stay shown after successive mappings selected

ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/DocumentField.tsx
Fixes: #1847
Still not perfect but the icons line up better.  @riccardo-forina is actively modifying the look and feel - will rely on his changes for final appearance.
=> fix: Line the edit and delete icons up

ui-react/packages/atlasmap-ui/src/AtlasmapUI/MappingDetails/MappingField.tsx
=> fix: UI_REACT: Nested DataListItem in MappingField causes console warning

ui-react/packages/atlasmap-ui/src/AtlasmapUI/MappingDetails/MappingField.tsx
=> fix: Correct invalid comment in MappingField

ui-react/packages/atlasmap-core/src/components/expression/expression-util.ts, ui-react/packages/atlasmap-core/src/models/expression.model.ts, ui-react/packages/atlasmap-core/src/react/Atlasmap.tsx, ui-react/packages/atlasmap-core/src/react/AtlasmapProvider.tsx, ui-react/packages/atlasmap-core/src/services/mapping-management.service.ts, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/AtlasmapCanvasView.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapLayout.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/CanvasViewToolbar.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/ConditionalExpression.tsx, ui-react/packages/atlasmap-ui/stories/Atlasmap.stories.tsx
Fixes: #1860
Successfully parse existing mapping conditional expressions
No widget tokenization yet - that's next.
=> fix: Initial conditional expression support

ui-react/packages/atlasmap-core/src/components/expression/expression-util.ts, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/AtlasmapCanvasView.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/CanvasViewToolbar.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/ConditionalExpression.tsx
=> fix: Correct conditional expression toggle

ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/DocumentField.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapContextToolbar.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/MappingDetails/MappingAction.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/MappingDetails/MappingDetails.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/MappingDetails/MappingField.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/MappingDetails/MappingFields.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/CanvasViewToolbar.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/Document.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/FieldGroup.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/FieldsBoxHeader.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/MappingElement.tsx, ui-react/packages/atlasmap-ui/src/common/useConfirmationDialog.tsx, ui-react/packages/atlasmap-ui/src/common/useInputTextSelectDialog.tsx, ui-react/packages/atlasmap-ui/src/common/useSingleInputDialog.tsx
Fixes: [#1890](https://github.com/atlasmap/atlasmap/issues/1890)
This should simplify the rewrite of test suite from Angular UI to the new React UI
=> Added `data-testid`s to UI elements

ui-react/packages/atlasmap-core/src/services/initialization.service.ts, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/AtlasmapCanvasView.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/AtlasmapCanvasViewSource.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/AtlasmapCanvasViewTarget.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapUIProvider.tsx, ui-react/packages/atlasmap-ui/src/Canvas/CanvasTransforms.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/CanvasView.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/CanvasViewCanvas.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/Document.tsx, ui-react/packages/atlasmap-ui/stories/views/CanvasView/CanvasView.stories.tsx, ui-react/packages/atlasmap-ui/stories/views/CanvasView/Document.stories.tsx, ui-react/packages/atlasmap-ui/stories/views/CanvasView/FieldGroup.stories.tsx, ui-react/packages/atlasmap-ui/stories/views/CanvasView/FieldsBox.stories.tsx, ui-react/packages/atlasmap-ui/stories/views/CanvasView/MappingElement.stories.tsx
=> fix: UI_REACT: Logic for deselecting a mapping when whitespace clicked not working correctly

ui-react/packages/atlasmap-core/src/models/mapping.model.ts, ui-react/packages/atlasmap-core/src/react/AtlasmapMappingDetails.tsx, ui-react/packages/atlasmap-core/src/services/mapping-management.service.ts, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapUIProvider.tsx
=> fix: UI_REACT: Make selecting a field populate selected mapping

camel/src/main/java/org/apache/camel/component/atlasmap/AtlasEndpoint.java, camel3/src/main/java/org/apache/camel/component/atlasmap/AtlasEndpoint.java, lib/core/src/main/java/io/atlasmap/core/ADMArchiveHandler.java, lib/core/src/main/java/io/atlasmap/core/AtlasUtil.java, lib/core/src/test/java/io/atlasmap/core/ADMArchiveHandlerTest.java, lib/model/src/main/java/io/atlasmap/v2/AtlasMapping.java, lib/model/src/main/java/io/atlasmap/v2/DataSourceCatalog.java, lib/model/src/main/java/io/atlasmap/v2/DataSourceMetadata.java, lib/service/src/main/java/io/atlasmap/service/AtlasLibraryLoader.java, lib/service/src/main/java/io/atlasmap/service/AtlasService.java, lib/service/src/test/java/io/atlasmap/service/AtlasServiceTest.java, standalone/pom.xml, standalone/src/main/java/io/atlasmap/standalone/JaxrsApplication.java
=> fix: Create .adm file handler API

ui-react/packages/atlasmap-core/src/components/field/field-util.ts, ui-react/packages/atlasmap-core/src/react/Atlasmap.tsx, ui-react/packages/atlasmap-core/src/services/mapping-management.service.ts, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/AtlasmapCanvasViewSource.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/AtlasmapCanvasViewTarget.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/DocumentField.tsx, ui-react/packages/atlasmap-ui/stories/Atlasmap.stories.tsx
=> fix: UI_REACT: Create mapping when source field selected

ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/AtlasmapCanvasView.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapContextToolbar.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapLayout.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/MappingTable.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/index.ts
This isn't a complete fix, but represents most of what needs to be done for this view. The main thing remaining is getting the entire path of sources and targets displayed.
=> fix: UI_REACT: Provide mapping table view

ui-react/packages/atlasmap-core/src/models/expression.model.ts, ui-react/packages/atlasmap-core/src/models/mapping.model.ts, ui-react/packages/atlasmap-core/src/react/Atlasmap.tsx, ui-react/packages/atlasmap-core/src/react/AtlasmapProvider.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapCanvasView/AtlasmapCanvasView.tsx, ui-react/packages/atlasmap-ui/src/AtlasmapUI/AtlasmapLayout.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/CanvasViewToolbar.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/ConditionalExpression.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/ExpressionContent.tsx, ui-react/packages/atlasmap-ui/src/CanvasView/components/ExpressionFieldSearch.tsx, ui-react/packages/atlasmap-ui/stories/Atlasmap.stories.tsx
Fixes: #1914
Ran into an issue with the newest server.  Works with older server - will address server issue separately.
Still needs d&d support as well as keyboard nav (arrows, tab)
=> fix: Add expression box support for adding field nodes.

ui-react/packages/atlasmap/src/Views/ColumnMapperView/Actions/EditMappingAction.tsx
=> fix: UI_REACT: Make show mapping details icons consistent

camel3/src/main/java/org/apache/camel/component/atlasmap/AtlasEndpoint.java
`org.apache.camel.StreamCache` can be read only once, so if we want to extract the payload of the same message on more than one step, we need to reset the stream.
This fix makes sure we will be able to re-read the body on future steps (if possible, as described on StreamCache): https://github.com/apache/camel/blob/master/core/camel-api/src/main/java/org/apache/camel/StreamCache.java#L25
The reset is done *after* the read in case the reset throws some error that makes the stream unusable (because it may really be a only-one-read stream) so it is prepared for future calls.
=> StreamCache not being resetted after read

camel3/src/main/java/org/apache/camel/component/atlasmap/AtlasEndpoint.java
Using Camel classes to reset stream cache instead of custom code.
=> Improving #1979

ui-react/packages/atlasmap/src/Atlasmap/Atlasmap.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/ColumnMapperView.stories.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Columns/ConstantsTree.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Columns/PropertiesTree.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Columns/SourcesColumn.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Columns/TargetsColumn.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Columns/commonActions.tsx, ui-react/packages/atlasmap/src/Views/SourceMappingTargetView.stories.tsx, ui-react/packages/atlasmap/src/Views/SourceTargetView.stories.tsx
Fixes #1965, ENTESB-13618, ENTESB-13619
=> feat(react-ui): start a new mapping from a field

ui-react/packages/atlasmap/src/Atlasmap/AtlasmapProvider.tsx, ui-react/packages/atlasmap/src/UI/ExpressionContent.tsx
=> fix: Remove opaque any refs in the expression box.

ui-react/packages/atlasmap/src/UI/Document.tsx, ui-react/packages/atlasmap/src/UI/useToggle.ts
=> feat(react-ui): documents can be collapsed

ui-react/packages/atlasmap/src/UI/ColumnMapper/SearchableColumnHeader.tsx
Fixes ENTESB-13646, ENTESB-13645
=> fix(react-ui): search on changes and reset search on toggle off

ui-react/packages/atlasmap/src/Atlasmap/AtlasmapProvider.tsx
=> fix(react-ui): reduce the debounce interval when the system is initialized

ui-react/packages/atlasmap-core/tsconfig.json, ui-react/packages/atlasmap/src/Atlasmap/Atlasmap.tsx, ui-react/packages/atlasmap/src/Atlasmap/AtlasmapProvider.tsx, ui-react/packages/atlasmap/src/Atlasmap/utils/field.ts, ui-react/packages/atlasmap/src/Atlasmap/utils/ui.ts, ui-react/packages/atlasmap/src/UI/MappingField.tsx, ui-react/packages/atlasmap/src/UI/MappingTransformation.stories.tsx, ui-react/packages/atlasmap/src/UI/MappingTransformation.tsx, ui-react/packages/atlasmap/src/Views/MappingDetailsView.tsx, ui-react/packages/atlasmap/src/Views/models.ts, ui-react/packages/atlasmap/src/stories/fromJava.ts, ui-react/packages/atlasmap/src/stories/fromJson.ts, ui-react/packages/atlasmap/src/stories/fromXML.ts, ui-react/packages/atlasmap/src/stories/sampleData.ts
This completes the wiring of the mapping details view. All functions should be working with the exception of adding a source/target field from the mapping details view directly. I'll make a new PR for that.
Fixes ENTESB-13633, ENTESB-13613, ENTESB-13612, #1964
=> feat(react-ui): finish wiring the MappingDetails

ui-react/packages/atlasmap/src/Atlasmap/AtlasmapProvider.tsx, ui-react/packages/atlasmap/src/Layout/MainLayout.tsx, ui-react/packages/atlasmap/src/UI/Canvas/Arc.tsx, ui-react/packages/atlasmap/src/UI/Canvas/NodesArc.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Links/SourceTargetLinks.tsx, ui-react/packages/atlasmap/src/Views/SourceTargetView.tsx
Highlighting lines should be quicker now.
Also updated some critical callbacks from anonymous closures to named functions to ease debugging.
=> fix(react-ui): improve some performance bottlenecks

ui-react/packages/atlasmap/src/Views/ColumnMapperView/Columns/MappingsColumn.tsx
=> fix: UI_REACT: Add expandable spacing between sources and targets in mappings view

ui-react/packages/atlasmap/src/Atlasmap/toolbarItems.tsx, ui-react/packages/atlasmap/src/UI/ColumnMapper/SearchableColumnHeader.tsx, ui-react/packages/atlasmap/src/UI/Document.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Actions/DeleteDocumentAction.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Actions/DeleteMappingAction.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Actions/EditMappingAction.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Actions/EnableJavaClassAction.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Actions/ImportAction.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Columns/ConstantsTree.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Columns/MappingsColumn.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Columns/PropertiesTree.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Columns/SourcesColumn.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Columns/TargetsColumn.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Columns/TreeItemFieldAndNodeRefsAndDnD.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Columns/commonActions.tsx
Added missing `data-testid's` for easier element search with test automation.
=> Added missing data-testid's to UI elements

ui-react/packages/atlasmap-core/src/utils/mapping-serializer.ts, ui-react/packages/atlasmap/package.json, ui-react/packages/atlasmap/src/Atlasmap/Atlasmap.tsx, ui-react/packages/atlasmap/src/Atlasmap/AtlasmapProvider.tsx, ui-react/packages/atlasmap/src/Atlasmap/utils/ui.ts, ui-react/packages/atlasmap/src/UI/Document.tsx, ui-react/packages/atlasmap/src/UI/DocumentField.tsx, ui-react/packages/atlasmap/src/UI/DocumentFieldPreview.tsx, ui-react/packages/atlasmap/src/UI/TruncatedString.tsx, ui-react/packages/atlasmap/src/UI/index.ts, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Columns/ConstantsTree.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Columns/MappingsColumn.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Columns/PropertiesTree.tsx, ui-react/packages/atlasmap/src/Views/ColumnMapperView/Columns/SourcesColumn.tsx, ui-react/packages/atlasmap/src/Views/MappingDetailsView.tsx, ui-react/packages/atlasmap/src/Views/models.ts, ui-react/packages/atlasmap/src/stories/sampleData.ts, ui-react/yarn.lock
Fixes the mapping preview not showing and its performance by optimizing
the number of events passed to the rxjs core.
Fixes the alerts to provide more context.
Fixes some UI layout glitch.
=> fix(react-ui): number of bugfixes

ui-react/packages/atlasmap-core/src/services/mapping-management.service.ts, ui-react/packages/atlasmap/src/Atlasmap/AtlasmapProvider.tsx
Fixes ENTESB-13718, ENTESB-13642
=> fix(react-ui): fixes the add/remove logic for fields

ui-react/packages/atlasmap-core/src/utils/mapping-serializer.ts
=> Don't serialize expressions of they don't exist.

ui-react/packages/atlasmap-core/src/services/document-management.service.ts, ui-react/packages/atlasmap/.storybook/webpack.config.js, ui-react/packages/atlasmap/package.json, ui-react/yarn.lock
Fixes ENTESB-13743
Also adds support to loading source maps for 3rd party deps (@atlasmap/core included) inside storybook to simplify debugging.
=> fix(react-ui): fix the document import

ui/packages/atlasmap/src/Atlasmap/Atlasmap.tsx, ui/packages/atlasmap/src/Atlasmap/AtlasmapProvider.tsx, ui/packages/atlasmap/src/Atlasmap/useAtlasmapDialogs.tsx, ui/packages/atlasmap/src/Atlasmap/utils/document.ts, ui/packages/atlasmap/src/Atlasmap/utils/ui.ts, ui/packages/atlasmap/src/UI/index.ts, ui/packages/atlasmap/src/UI/useNamespaceDialog.tsx, ui/packages/atlasmap/src/Views/NamespaceTableView.tsx, ui/packages/atlasmap/src/Views/index.ts, ui/packages/atlasmap/src/Views/models.ts
=> fix: UI_REACT: Create namespace view

ui/packages/atlasmap/src/Atlasmap/Atlasmap.stories.tsx, ui/packages/atlasmap/src/Atlasmap/Atlasmap.tsx, ui/packages/atlasmap/src/Atlasmap/useContextToolbar.tsx, ui/packages/atlasmap/src/UI/ColumnMapper/ColumnHeader.tsx, ui/packages/atlasmap/src/UI/Document.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Columns/SourcesColumn.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Columns/TargetsColumn.tsx
=> feat(ui): make the UI configuration options more granular

ui/package.json, ui/packages/atlasmap-standalone/public/index.html, ui/packages/atlasmap-standalone/src/App.tsx, ui/packages/atlasmap/doc/0.Intro.stories.mdx, ui/packages/atlasmap/src/Atlasmap/Atlasmap.stories.tsx, ui/packages/atlasmap/src/Layout/CanvasControlBar.stories.tsx, ui/packages/atlasmap/src/Layout/ContextToolbar.stories.tsx, ui/packages/atlasmap/src/Layout/MainContent.stories.tsx, ui/packages/atlasmap/src/Layout/MainLayout.stories.tsx, ui/packages/atlasmap/src/Layout/MappingDetailsSidebar.stories.tsx, ui/packages/atlasmap/src/Layout/Sidebar.stories.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/ColumnMapperView.stories.tsx, ui/packages/atlasmap/src/Views/MappingTableView.stories.tsx, ui/packages/atlasmap/src/Views/SourceMappingTargetView.stories.tsx, ui/packages/atlasmap/src/Views/SourceTargetView.stories.tsx
=> chore(ui): fix AtlasMap casing for public facing strings

ui/packages/atlasmap/src/Atlasmap/utils/ui.ts, ui/packages/atlasmap/src/UI/DocumentField.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Columns/TreeItemFieldAndNodeRefsAndDnD.tsx, ui/packages/atlasmap/src/Views/models.ts, ui/packages/atlasmap/src/stories/fromJava.ts, ui/packages/atlasmap/src/stories/fromJson.ts, ui/packages/atlasmap/src/stories/fromXML.ts, ui/packages/atlasmap/src/stories/sampleData.ts
=> fix(ui): disable fields not yet supported

ui/packages/atlasmap-core/src/utils/mapping-serializer.ts
=> fix: Serialize input field mapping actions in one-to-many mode.

lib/service/src/main/java/io/atlasmap/service/AtlasService.java
=> fix: AtlasService pulls an NPE on source import

ui/packages/atlasmap/src/Atlasmap/useSidebar.tsx, ui/packages/atlasmap/src/Atlasmap/utils/ui.ts, ui/packages/atlasmap/src/UI/MappingTransformation.tsx, ui/packages/atlasmap/src/Views/MappingDetailsView.tsx, ui/packages/atlasmap/src/Views/models.ts
Fixes ENTESB-13808 and ENTESB-13809
=> fix(ui): properly retrieve and display transformations' options and arguments

ui/packages/atlasmap/src/Views/ColumnMapperView/Links/SourceTargetLinks.tsx
With this all lines relative to the same mapping will be highlighted when hovering with the mouse, instead of the specific single line which was confusing.
=> fix(ui): highlight all mapping lines at once when hovering

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasExpressionProcessor.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, lib/itests/core/src/test/java/io/atlasmap/itests/core/BaseClass.java, lib/itests/core/src/test/java/io/atlasmap/itests/core/ExpressionTest.java, lib/itests/core/src/test/resources/mappings/atlasmapping-expression2-average.json
=> fix: Average(intArray) expression mapping doesn't work

ui/packages/atlasmap/src/UI/ColumnMapper/SearchableColumnHeader.tsx
=> fix(ui): make the search icon active when toggled

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasValidationService.java
=> fix: Validation - Field mappings should not be empty

docs/publish-docs.sh, docs/src/main/asciidoc/developer-guide/index.adoc, pom.xml
Fixes: #2098
chore: downgrade maven-javadoc-plugin to restore expected aggregate behavior
Fixes: #2103
=> chore: Attach upstream master coverage report to developer guide

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasValidationService.java, ui/packages/atlasmap-core/src/services/mapping-management.service.ts, ui/packages/atlasmap-core/test/services/mapping-management.service.spec.ts
Fixes: ENTESB-13797
Follow up to https://github.com/atlasmap/atlasmap/pull/2100
=> fix: Validation - Field mappings should not be empty - followup

ui/packages/atlasmap/src/Views/MappingTableView.tsx
=> fix: Mapping preview tab - missing mapping preview

ui/packages/atlasmap/src/Atlasmap/dialogs/useCustomClassDialog.tsx
=> fix(ui): set default type for custom classes

standalone/src/test/java/io/atlasmap/standalone/E2ETest.java
=> fix: Potential NPE in E2ETest

ui/packages/atlasmap/src/Atlasmap/useSidebar.tsx, ui/packages/atlasmap/src/UI/AddFieldTypeahead.stories.tsx, ui/packages/atlasmap/src/UI/AddFieldTypeahead.tsx
=> fix(ui): make field typeahead dropdown overflow if needed

lib/core/src/main/java/io/atlasmap/core/ADMArchiveHandler.java, lib/core/src/test/java/io/atlasmap/core/ADMArchiveHandlerTest.java, lib/service/src/main/java/io/atlasmap/service/AtlasService.java
=> fix: Do not save empty mapping definition

ui/packages/atlasmap/src/Atlasmap/Atlasmap.tsx, ui/packages/atlasmap/src/Views/MappingTableView.stories.tsx, ui/packages/atlasmap/src/Views/MappingTableView.tsx
=> fix(ui): decouple the MappingTableView from the business logic functions

ui/packages/atlasmap-core/src/services/document-management.service.ts, ui/packages/atlasmap-core/src/services/file-management.service.ts
=> fix: Don't generate an exportMappings if no mappings exist

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasValidationService.java, lib/core/src/test/java/io/atlasmap/core/DefaultAtlasContextTest.java, ui/packages/atlasmap-core/src/services/mapping-management.service.ts, ui/packages/atlasmap-core/test/services/mapping-management.service.spec.ts
Fixes: ENTESB-13932 ENTESB-13919 ENTESB-13797
=> fix: Delete mapping button doesn't delete mapping

ui/packages/atlasmap-core/src/models/expression.model.ts
=> fix: Enable removal of single text node character.

ui/packages/atlasmap-core/src/models/expression.model.ts
=> fix: Distinguish field nodes from text in the expression box.

ui/packages/atlasmap/src/Atlasmap/Atlasmap.tsx, ui/packages/atlasmap/src/Atlasmap/useAtlasmapDialogs.tsx, ui/packages/atlasmap/src/Atlasmap/utils/field.ts, ui/packages/atlasmap/src/UI/dialogs/PropertyDialog.tsx
=> fix: Support editing property names.

ui/packages/atlasmap-core/src/services/mapping-management.service.ts
=> fix: Correct undefined document definition Id reference in preview code.

lib/core/src/main/java/io/atlasmap/actions/ExpressionFieldAction.java, lib/core/src/main/java/io/atlasmap/core/AtlasPath.java, lib/core/src/main/java/io/atlasmap/core/AtlasUtil.java, lib/core/src/main/java/io/atlasmap/core/BaseFunctionFactory.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasFunctionResolver.java, lib/core/src/main/java/io/atlasmap/functions/FILTER.java, lib/core/src/main/java/io/atlasmap/functions/ISEMPTY.java, lib/core/src/main/java/io/atlasmap/functions/SELECT.java, lib/core/src/main/java/io/atlasmap/functions/TOLOWER.java, lib/core/src/test/java/io/atlasmap/actions/ExpressionFieldActionTest.java, lib/expression/pom.xml, lib/expression/src/main/java/io/atlasmap/expression/Expression.java, lib/expression/src/main/java/io/atlasmap/expression/ExpressionContext.java, lib/expression/src/main/java/io/atlasmap/expression/internal/ArithmeticExpression.java, lib/expression/src/main/java/io/atlasmap/expression/internal/ComparisonExpression.java, lib/expression/src/main/java/io/atlasmap/expression/internal/ConstantExpression.java, lib/expression/src/main/java/io/atlasmap/expression/internal/LogicExpression.java, lib/expression/src/main/java/io/atlasmap/expression/internal/UnaryExpression.java, lib/expression/src/main/java/io/atlasmap/expression/internal/VariableExpression.java, lib/expression/src/test/java/io/atlasmap/expression/ExpressionTest.java, lib/itests/core/src/test/java/io/atlasmap/itests/core/BaseClass.java, lib/itests/core/src/test/java/io/atlasmap/itests/core/ExpressionTest.java, lib/itests/core/src/test/resources/log4j2.xml, lib/itests/core/src/test/resources/mappings/atlasmapping-expression2-compare.json, lib/itests/core/src/test/resources/mappings/atlasmapping-expression2-oper.json, lib/model/src/main/java/io/atlasmap/v2/AtlasModelFactory.java
Fixes: #2112
This makes #2094 slightly better, but still expression and field action have to wrap with/unwrap Field, which is not cool.
=> fix: expression fails to process primitive value

ui/packages/atlasmap/src/Atlasmap/Atlasmap.tsx, ui/packages/atlasmap/src/Atlasmap/utils/ui.ts, ui/packages/atlasmap/src/Views/MappingTableView.stories.tsx, ui/packages/atlasmap/src/Views/MappingTableView.tsx
=> fix: Add preview capability to mapping table view

lib/itests/core/src/test/java/io/atlasmap/itests/core/BaseClass.java, lib/itests/core/src/test/java/io/atlasmap/itests/core/ExpressionTest.java, lib/itests/core/src/test/resources/log4j2.xml, lib/itests/core/src/test/resources/mappings/atlasmapping-expression2-action.json, lib/model/src/main/java/io/atlasmap/v2/AtlasModelFactory.java
=> fix: Transformation for each collection item fails in expression

lib/service/src/main/java/io/atlasmap/service/AtlasService.java, ui/packages/atlasmap-core/src/models/config.model.ts, ui/packages/atlasmap-core/src/services/mapping-management.service.ts, ui/packages/atlasmap/src/Atlasmap/utils/document.ts
=> fix: Split old validate REST into validate and save.

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java
=> fix: Avoid potential NPE in DefaultAtlasContext.init()

lib/modules/xml/module/src/main/java/io/atlasmap/xml/module/XmlModule.java
=> fix: XML schema enforcer fails with empty namespace

ui/packages/atlasmap/src/Views/ColumnMapperView/Links/SourceTargetLinks.tsx
=> fix: SourceTargetLinks causing warning about missing keys in list

ui/packages/atlasmap/src/Layout/MappingDetailsSidebar.tsx, ui/packages/atlasmap/src/UI/Actions.tsx, ui/packages/atlasmap/src/UI/Canvas/Arc.tsx, ui/packages/atlasmap/src/UI/Canvas/ArcEdge.tsx, ui/packages/atlasmap/src/UI/Canvas/HTMLObject.tsx, ui/packages/atlasmap/src/UI/Canvas/NodeRef.tsx, ui/packages/atlasmap/src/UI/Canvas/NodeRefProvider.tsx, ui/packages/atlasmap/src/UI/Canvas/NodesArc.tsx, ui/packages/atlasmap/src/UI/Canvas/index.ts, ui/packages/atlasmap/src/UI/ColumnMapper/Column.stories.tsx, ui/packages/atlasmap/src/UI/ColumnMapper/Column.tsx, ui/packages/atlasmap/src/UI/ColumnMapper/ColumnBody.tsx, ui/packages/atlasmap/src/UI/ColumnMapper/ColumnHeader.tsx, ui/packages/atlasmap/src/UI/ColumnMapper/ColumnMapper.stories.tsx, ui/packages/atlasmap/src/UI/ColumnMapper/SearchableColumnHeader.test.tsx, ui/packages/atlasmap/src/UI/ColumnMapper/SearchableColumnHeader.tsx, ui/packages/atlasmap/src/UI/Document.tsx, ui/packages/atlasmap/src/UI/DocumentField.tsx, ui/packages/atlasmap/src/UI/DocumentGroup.tsx, ui/packages/atlasmap/src/UI/MappingField.tsx, ui/packages/atlasmap/src/UI/MappingTransformation.stories.tsx, ui/packages/atlasmap/src/UI/MappingTransformation.tsx, ui/packages/atlasmap/src/UI/Tree/TreeGroup.tsx, ui/packages/atlasmap/src/UI/Tree/TreeItem.tsx, ui/packages/atlasmap/src/UI/dnd/DraggableField.tsx, ui/packages/atlasmap/src/UI/dnd/FieldDropTarget.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Links/SourceTargetLinks.tsx, ui/packages/atlasmap/src/Views/MappingDetailsView.tsx, ui/packages/atlasmap/src/Views/SourceTargetView.tsx
* updated form spacing in the mapping details
* changed columns UI
* toolbars background fixed to white
* expression box made look like a PF control
Fixes #2193
=> fix(ui): address UXD feedback

ui/packages/atlasmap/src/UI/DocumentGroup.tsx
=> fix: Distinguish collection of primitive and collection of complex with icon

ui/packages/atlasmap-core/src/models/config.model.ts, ui/packages/atlasmap-core/src/models/document-definition.model.ts, ui/packages/atlasmap-core/src/services/document-management.service.ts, ui/packages/atlasmap-core/src/services/initialization.service.ts, ui/packages/atlasmap/src/Atlasmap/AtlasmapProvider.tsx, ui/packages/atlasmap/src/Atlasmap/dialogs/useImportDocumentDialog.tsx, ui/packages/atlasmap/src/Atlasmap/dialogs/useParametersDialog.tsx, ui/packages/atlasmap/src/Atlasmap/utils/document.ts, ui/packages/atlasmap/src/Atlasmap/utils/toolbar.ts, ui/packages/atlasmap/src/UI/dialogs/ParametersDialog.stories.tsx, ui/packages/atlasmap/src/UI/dialogs/ParametersDialog.tsx, ui/packages/atlasmap/src/UI/dialogs/index.ts
=> fix: Add UI for providing CSV parameters

ui/packages/atlasmap/src/UI/DocumentGroup.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Columns/TreeGroupAndNodeRefsAndDnD.tsx
=> fix: Complex collection icon has no tooltip

ui/packages/atlasmap-core/src/models/document-definition.model.ts, ui/packages/atlasmap-core/src/models/expression.model.ts, ui/packages/atlasmap-core/src/models/field.model.ts, ui/packages/atlasmap-core/src/models/mapping.model.ts, ui/packages/atlasmap-core/src/services/mapping-management.service.ts, ui/packages/atlasmap-core/src/utils/mapping-serializer.ts, ui/packages/atlasmap-core/src/utils/mapping-util.ts, ui/packages/atlasmap/src/Atlasmap/utils/ui.ts
Fixes: #1604
Adds serializer support for input field groups for complex refs.
No React UI changes.
=> fix: Support referencing complex elements in conditional expressions.

ui/packages/atlasmap/src/Atlasmap/dialogs/useCustomClassDialog.tsx
I tried to fix the issue with import custom class dialog - can you @pleacu please have a look? I don't have too much experience yet with the async/await, so I'm not really sure this is the right fix for this.
=> [ENTESB-14404] fix import custom class dialog

ui/packages/atlasmap/src/Atlasmap/dialogs/useConstantDialog.tsx, ui/packages/atlasmap/src/Atlasmap/dialogs/usePropertyDialog.tsx
The reason for this is explained in detail in [ENTESB-14445](https://issues.redhat.com/browse/ENTESB-14445). 
Also I would like to ask, whether this could be backported to 7.8. branch (of course in case the fix I provided makes sense), as this is also present in 7.7. 
I know that master will differ from 7.8., but I'm not completely sure what the 7.8. branch is.
=> [ENTESB-14445] fix initial property and constant value type

ui/packages/atlasmap-core/src/services/document-management.service.ts, ui/packages/atlasmap-core/src/services/initialization.service.ts
=> fix: Imported CSV file doesn't retain state when page refreshes

ui/packages/atlasmap/src/Atlasmap/AtlasmapProvider.tsx
=> fix: AtlasmapProvider should accept inspectionParameters for CSV

ui/packages/atlasmap/src/Atlasmap/dialogs/useConstantDialog.tsx, ui/packages/atlasmap/src/Atlasmap/dialogs/usePropertyDialog.tsx
=> Backport atlasmap-2.0.x: [ENTESB-14445] fix initial property and constant value type

lib/core/src/main/java/io/atlasmap/actions/CollectionActions.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, lib/core/src/main/resources/META-INF/services/io.atlasmap.spi.AtlasFieldAction, lib/itests/reference-mappings/src/test/java/io/atlasmap/itests/reference/json_to_json/JsonJsonCopyToTest.java, lib/itests/reference-mappings/src/test/java/io/atlasmap/itests/reference/json_to_json/JsonTestHelper.java, lib/itests/reference-mappings/src/test/resources/jsonToJson/atlasmapping-empty-mapping.json, lib/model/src/main/java/io/atlasmap/v2/CopyTo.java, lib/model/src/main/resources/META-INF/services/io.atlasmap.v2.Action
See #2007 
POC of the json implementation (backend only atm)
=> Map source elements to a specific instance in a target array

ui/packages/atlasmap/src/Atlasmap/toolbarItems.tsx, ui/packages/atlasmap/src/Atlasmap/useContextToolbar.tsx
=> fix: Add new mapping in the 'show mapping table' view

ui/packages/atlasmap-core/package.json, ui/packages/atlasmap/package.json
=> Fixes: #2043 - handle prettier EOL errors on windows

ui/packages/atlasmap/src/Atlasmap/useContextToolbar.tsx
=> fix: Make new mapping available in mapping table view

ui/packages/atlasmap-core/src/utils/mapping-serializer.ts
Fixes: https://github.com/atlasmap/atlasmap/issues/2296
=> [fix]: Atlasmap camel header/property lookup not working in UI

lib/core/src/main/java/io/atlasmap/core/CompoundClassLoader.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasCompoundClassLoader.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasContextFactory.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, lib/service/src/main/java/io/atlasmap/service/AtlasLibraryLoader.java, lib/service/src/main/java/io/atlasmap/service/AtlasService.java
=> fix: Infinite loop in class loader chain causes SOE

lib/core/src/main/java/io/atlasmap/actions/StringComplexFieldActions.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, lib/itests/core/src/test/java/io/atlasmap/itests/core/MultiplicityTransformationTest.java, lib/itests/core/src/test/resources/data/json-source-repeat.json, lib/itests/core/src/test/resources/data/json-source-repeat_count_3.json, lib/itests/core/src/test/resources/data/json-source-repeat_for_nested_collection_field.json, lib/itests/core/src/test/resources/data/json-source-repeat_no_field.json, lib/itests/core/src/test/resources/mappings/atlasmapping-multiplicity-transformation-action_repeat.json, lib/itests/core/src/test/resources/mappings/atlasmapping-multiplicity-transformation-action_repeat_nested_collection.json, lib/model/src/main/java/io/atlasmap/v2/Repeat.java, lib/model/src/main/resources/META-INF/services/io.atlasmap.v2.Action
=> fix: one_to_many mapping - repeat source value based on count

lib/model/src/main/java/io/atlasmap/v2/ActionDetail.java, lib/model/src/main/java/io/atlasmap/v2/ActionListUpgradeDeserializer.java, lib/model/src/main/java/io/atlasmap/v2/AtlasModelFactory.java, lib/model/src/main/java/io/atlasmap/v2/Json.java, lib/modules/json/core/src/main/java/io/atlasmap/json/core/JsonFieldReader.java, lib/modules/json/core/src/main/java/io/atlasmap/json/core/JsonFieldWriter.java, lib/modules/json/core/src/main/java/io/atlasmap/json/inspect/JsonInstanceInspector.java, lib/modules/json/core/src/main/java/io/atlasmap/json/inspect/JsonSchemaInspector.java, parent/pom.xml
=> fix: Set BLOCK_UNSAFE_POLYMORPHIC_BASE_TYPES on jackson ObjectMapper

ui/packages/atlasmap/src/Atlasmap/dialogs/usePropertyDialog.tsx, ui/packages/atlasmap/src/Atlasmap/useAtlasmapDialogs.tsx, ui/packages/atlasmap/src/Atlasmap/utils/document.ts
=> fix: Correct error in target property scoping in create/edit dialogs.

ui/packages/atlasmap/src/Atlasmap/utils/ui.ts, ui/packages/atlasmap/src/UI/MappingTransformation.tsx
=> fix: Honor title settings for field action arguments.

lib/itests/core/src/test/java/io/atlasmap/itests/core/MultiplicityTransformationTest.java, lib/itests/core/src/test/resources/mappings/atlasmapping-multiplicity-transformation-concatenate-csv.json, lib/modules/csv/core/src/main/java/io/atlasmap/csv/core/CsvFieldReader.java, lib/modules/csv/core/src/main/java/io/atlasmap/csv/core/CsvFieldWriter.java
=> fix: Split/concatenate on CSV rows does not work correclty

lib/modules/csv/core/src/main/java/io/atlasmap/csv/core/CsvFieldWriter.java, lib/modules/csv/core/src/test/java/io/atlasmap/csv/core/CsvFieldReaderTest.java, lib/modules/csv/core/src/test/java/io/atlasmap/csv/core/CsvFieldWriterTest.java
…undsException
Fixes: #2219
(cherry picked from commit 8863b7fc3084e343e556e3437a74920b2bd45ef0)
=> Backport of #2219 to 2.0.x

lib/itests/core/src/test/java/io/atlasmap/itests/core/MultiplicityTransformationTest.java, lib/itests/core/src/test/resources/mappings/atlasmapping-multiplicity-transformation-concatenate-csv.json, lib/modules/csv/core/src/main/java/io/atlasmap/csv/core/CsvFieldReader.java, lib/modules/csv/core/src/main/java/io/atlasmap/csv/core/CsvFieldWriter.java
Fixes #2069
(cherry picked from commit 1a56efd23aa303cc28dc55cada95ed5ea313be72)
=> Backporting #2069 to 2.0.x

docs/pom.xml
=> fix: image links are broken in user-guide/developer-guide

ui/packages/atlasmap/src/Atlasmap/Atlasmap.tsx, ui/packages/atlasmap/src/Atlasmap/dialogs/useConstantDialog.tsx, ui/packages/atlasmap/src/Atlasmap/dialogs/usePropertyDialog.tsx, ui/packages/atlasmap/src/Atlasmap/useAtlasmapDialogs.tsx, ui/packages/atlasmap/src/UI/dialogs/ConstantDialog.stories.tsx, ui/packages/atlasmap/src/UI/dialogs/ConstantDialog.tsx, ui/packages/atlasmap/src/UI/dialogs/PropertyDialog.stories.tsx, ui/packages/atlasmap/src/UI/dialogs/PropertyDialog.tsx
Fixes #2336 
I found the same issue with constants, so I fixed that here also.
=> fix: Multiple properties with same name allowed

standalone/src/test/java/io/atlasmap/standalone/E2ETest.java
=> fix: Fix exported ADM file detection in E2ETest

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasContextFactory.java, lib/service/src/main/java/io/atlasmap/service/AtlasService.java
=> fix: NPE in AtlasService constructor

lib/modules/xml/core/src/main/java/io/atlasmap/xml/inspect/XmlSchemaInspector.java, lib/modules/xml/core/src/test/java/io/atlasmap/xml/inspect/BaseXmlInspectionServiceTest.java, lib/modules/xml/core/src/test/java/io/atlasmap/xml/inspect/XmlSchemaInspectionTest.java, lib/modules/xml/model/src/main/java/io/atlasmap/xml/v2/XmlField.java
=> fix: Let XML schema inspector use XmlField.isAttribute()

ui/packages/atlasmap/src/Views/MappingTableView.tsx
downstream issue: https://issues.redhat.com/browse/ENTESB-14013
=> Backport: fix mapping table preview - display the results in target

ui/packages/atlasmap/src/Atlasmap/useAtlasmapDialogs.tsx, ui/packages/atlasmap/src/Atlasmap/utils/field.ts, ui/packages/atlasmap/src/UI/dialogs/PropertyDialog.tsx
Edit properties should only show the user-defined property name.  Also fixed property namer update.
Hopefully the last of the property tweeks.
=> Fixes: #2378

lib/itests/core/src/test/java/io/atlasmap/itests/core/CsvMappingTest.java, lib/itests/core/src/test/resources/mappings/atlasmapping-csv-not-used.json, lib/modules/csv/core/src/main/java/io/atlasmap/csv/core/CsvFieldWriter.java
=> fix: target CSV not used causing java.lang.IndexOutOfBoundsException

standalone/src/test/java/io/atlasmap/standalone/E2ETest.java
Fixes: #2351
seems it misses file create event between poll timeout and next poll.
=> fix: Fix E2ETest

lib/modules/json/core/src/main/java/io/atlasmap/json/inspect/JsonInspectionException.java, lib/modules/json/core/src/main/java/io/atlasmap/json/inspect/JsonInspectionService.java, lib/modules/json/core/src/main/java/io/atlasmap/json/inspect/JsonInspector.java, lib/modules/json/core/src/main/java/io/atlasmap/json/inspect/JsonInstanceInspector.java, lib/modules/json/core/src/main/java/io/atlasmap/json/inspect/JsonSchemaInspector.java, lib/modules/json/core/src/test/java/io/atlasmap/json/inspect/JsonSchemaInspectorTest.java, lib/modules/json/core/src/test/resources/inspect/schema/address.json, lib/modules/json/model/src/main/java/io/atlasmap/json/v2/JsonComplexType.java, lib/modules/json/model/src/main/java/io/atlasmap/json/v2/JsonEnumField.java, lib/modules/json/model/src/main/java/io/atlasmap/json/v2/JsonEnumFields.java
Fixes: #2402
Partially fixes: #1594
UI currently shows it as disabled
=> feat: Support enum for JSON schema inspection

ui/packages/atlasmap-core/src/services/document-management.service.ts, ui/packages/atlasmap/src/Atlasmap/utils/toolbar.ts
xref: https://issues.redhat.com/browse/ENTESB-14961
=> fix: UUID not generated for imported CSV files

ui/packages/atlasmap-core/src/services/mapping-management.service.ts
=> fix: Mapping preview - when the input is deleted, the result field isn' cleaned too

ui/packages/atlasmap/src/Atlasmap/Atlasmap.tsx, ui/packages/atlasmap/src/Atlasmap/dialogs/index.ts, ui/packages/atlasmap/src/Atlasmap/dialogs/useCaptureDocumentNameToast.tsx, ui/packages/atlasmap/src/Atlasmap/useAtlasmapDialogs.tsx, ui/packages/atlasmap/src/Atlasmap/utils/ui.ts, ui/packages/atlasmap/src/Views/ColumnMapperView/Actions/CaptureDocumentNameAction.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Actions/index.ts, ui/packages/atlasmap/src/Views/ColumnMapperView/Columns/ConstantsTree.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Columns/PropertiesTree.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Columns/SourcesColumn.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Columns/TargetsColumn.tsx
chore: Add a button to capture the document ID to the clipboard. (techdebt)
Fixes: #2389
=> Fixes: #2389

ui/packages/atlasmap-core/src/services/mapping-management.service.ts
=> fix: Disable multiplicity transformations when expression box enabled

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasPreviewSession.java, lib/core/src/test/java/io/atlasmap/core/DefaultAtlasContextTest.java
=> fix: Support expression in mapping preview

parent/pom.xml
https://issues.redhat.com/browse/ENTESB-10454
=> chore: ENTESB-10454 Version alignment

ui/packages/atlasmap-core/src/models/transition.model.ts, ui/packages/atlasmap/src/UI/MappingTransformation.tsx
=> fix: User defined separator not working

ui/packages/atlasmap-core/src/services/document-management.service.ts, ui/packages/atlasmap-core/src/utils/mapping-util.ts
=> Handle legacy data source elements for Java field mappings.

ui/packages/atlasmap/src/Atlasmap/Atlasmap.tsx, ui/packages/atlasmap/src/Atlasmap/AtlasmapProvider.tsx, ui/packages/atlasmap/src/Atlasmap/dialogs/index.ts, ui/packages/atlasmap/src/Atlasmap/dialogs/useChangeDocumentNameDialog.tsx, ui/packages/atlasmap/src/Atlasmap/useAtlasmapDialogs.tsx, ui/packages/atlasmap/src/Atlasmap/utils/document.ts, ui/packages/atlasmap/src/UI/dialogs/ChangeDocumentNameDialog.tsx, ui/packages/atlasmap/src/UI/dialogs/index.ts, ui/packages/atlasmap/src/Views/ColumnMapperView/Actions/ChangeDocumentNameAction.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Actions/index.ts, ui/packages/atlasmap/src/Views/ColumnMapperView/Columns/SourcesColumn.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Columns/TargetsColumn.tsx
=> feat: Add ability to change imported document names.

lib/core/src/main/java/io/atlasmap/actions/StringComplexFieldActions.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, lib/core/src/test/java/io/atlasmap/actions/ExpressionFieldActionTest.java, lib/core/src/test/java/io/atlasmap/core/DefaultAtlasContextTest.java, lib/itests/core/src/test/resources/mappings/atlasmapping-multiplicity-transformation-concatenate-csv.json, lib/itests/core/src/test/resources/mappings/atlasmapping-multiplicity-transformation-concatenate-expression.json, lib/model/src/main/java/io/atlasmap/v2/Concatenate.java, ui/packages/atlasmap-core/src/services/mapping-management.service.ts, ui/packages/atlasmap-core/src/utils/mapping-serializer.ts, ui/packages/atlasmap/src/UI/MappingTransformation.tsx
=> fix: Add option for concatenate action to skip delimiters for null values

ui/packages/atlasmap-core/src/services/document-management.service.ts
Fixes: #2476
Trivial one-liner.
=> fix: Correctly process documents with multiple dots.

lib/modules/csv/core/src/main/java/io/atlasmap/csv/core/CsvFieldReader.java, lib/modules/csv/core/src/test/java/io/atlasmap/csv/core/CsvFieldReaderTest.java
=> fix: CSV - parameter headers is not working

ui/packages/atlasmap/src/UI/MappingTransformation.tsx
Fixes: #2478
One-line change - Corrects this issue:
=> fix: Add key to mutliplicity delimiter checkbox.

lib/modules/csv/core/src/main/java/io/atlasmap/csv/core/CsvConfig.java, lib/modules/csv/core/src/main/java/io/atlasmap/csv/core/CsvFieldReader.java, lib/modules/csv/core/src/main/java/io/atlasmap/csv/core/CsvFieldWriter.java, lib/modules/csv/core/src/test/java/io/atlasmap/csv/core/CsvFieldReaderTest.java, lib/modules/csv/core/src/test/java/io/atlasmap/csv/core/CsvFieldWriterTest.java, lib/modules/csv/service/src/main/java/io/atlasmap/csv/service/CsvService.java, lib/modules/csv/service/src/test/java/io/atlasmap/csv/service/CsvServiceTest.java, ui/packages/atlasmap/src/Atlasmap/dialogs/useImportDocumentDialog.tsx
=> fix: CSV - ignoreHeaderCase is not reflected in the UI

ui/packages/atlasmap-core/src/models/expression.model.ts, ui/packages/atlasmap-core/src/models/mapping.model.ts, ui/packages/atlasmap-core/src/models/transition.model.ts, ui/packages/atlasmap-core/src/services/mapping-management.service.ts, ui/packages/atlasmap-core/src/utils/mapping-serializer.ts, ui/packages/atlasmap-core/src/utils/mapping-util.ts, ui/packages/atlasmap/src/Atlasmap/utils/ui.ts
Translate current mapping transformations when expression is enabled
=> Fixes: #2413

lib/core/src/main/java/io/atlasmap/core/AtlasPath.java, lib/core/src/test/java/io/atlasmap/core/AtlasPathTest.java, lib/itests/core/src/test/java/io/atlasmap/itests/core/issue/Atlasmap2357Test.java, lib/itests/core/src/test/resources/mappings/issue/atlasmap-2357-mapping.json, lib/itests/core/src/test/resources/mappings/issue/atlasmap-2357-source.json, lib/itests/core/src/test/resources/mappings/issue/atlasmap-2357-target.json, lib/modules/xml/core/src/main/java/io/atlasmap/xml/core/XmlPath.java
=> fix:  is not allowed for the first char of field name

ui/packages/atlasmap/src/Atlasmap/utils/ui.ts, ui/packages/atlasmap/src/UI/MappingField.tsx, ui/packages/atlasmap/src/UI/MappingTransformation.tsx, ui/packages/atlasmap/src/Views/MappingDetailsView.tsx
=> fix: Correct transformation order integrity on transformation delete.

ui/packages/atlasmap-core/src/models/document-definition.model.ts, ui/packages/atlasmap-core/src/models/field.model.ts, ui/packages/atlasmap-core/src/models/mapping.model.ts, ui/packages/atlasmap-core/src/services/initialization.service.ts, ui/packages/atlasmap-core/src/utils/mapping-serializer.ts, ui/packages/atlasmap-core/src/utils/mapping-util.ts, ui/packages/atlasmap/src/Atlasmap/utils/ui.ts
Fixes: #1518
The real issue here is that the processMappingsCatalogFiles call in initialize needed to finish before the mappings are loaded.
Will issue a different issue for differentiating attributes from field elements.
=> fix: Correct ghost field addition to COMPLEX fields.

ui/packages/atlasmap/src/Atlasmap/Atlasmap.tsx, ui/packages/atlasmap/src/Atlasmap/AtlasmapProvider.tsx, ui/packages/atlasmap/src/Atlasmap/utils/field.ts
=> fix: Correct d&d for compound mappings.

lib/modules/xml/core/src/main/java/io/atlasmap/xml/inspect/XmlSchemaInspector.java, lib/modules/xml/core/src/test/java/io/atlasmap/xml/inspect/XmlSchemaInspectionTest.java, lib/modules/xml/core/src/test/resources/inspect/simple-schema.xsd
=> fix: Map unsupported xsd standard types to atlasmap primitive

ui/packages/atlasmap-core/src/models/mapping.model.ts, ui/packages/atlasmap/src/Atlasmap/utils/ui.ts, ui/packages/atlasmap/src/UI/MappingField.tsx, ui/packages/atlasmap/src/Views/MappingDetailsView.tsx
=> fix: Add d&d support to the mapping details sidebar.

ui/packages/atlasmap/src/Atlasmap/AtlasmapProvider.tsx, ui/packages/atlasmap/src/Atlasmap/utils/ui.ts
=> fix: Disable field elements whose type is 'UNSUPPORTED'

lib/modules/csv/core/src/main/java/io/atlasmap/csv/core/CsvFieldReader.java, lib/modules/csv/service/src/test/java/io/atlasmap/csv/service/CsvServiceTest.java
=> fix: Erroneous CSV inspection response

camel3/src/test/java/org/apache/camel/component/atlasmap/issue/AtlasMapIssue2552Test.java, camel3/src/test/resources/org/apache/camel/component/atlasmap/issue/2552-input.json, camel3/src/test/resources/org/apache/camel/component/atlasmap/issue/AtlasMapIssue2552Test-context.xml, camel3/src/test/resources/org/apache/camel/component/atlasmap/issue/atlasmapping-2552-new.json, camel3/src/test/resources/org/apache/camel/component/atlasmap/issue/atlasmapping-2552-old.json, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java, lib/modules/json/core/src/main/java/io/atlasmap/json/core/JsonFieldWriter.java
=> fix: null value fails to be written for JSON BIG_INTEGER field

ui/packages/atlasmap/src/Atlasmap/utils/field.ts
=> fix: Create new mapping button from Target panel does not work

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasValidationService.java, lib/itests/core/src/test/java/io/atlasmap/itests/core/DfdlCsvTest.java, lib/itests/core/src/test/java/io/atlasmap/itests/core/TestHelper.java, lib/itests/core/src/test/java/io/atlasmap/itests/core/XMLAttributeTest.java, lib/itests/core/src/test/resources/data/xml-source-attribute-ns.xml, lib/itests/core/src/test/resources/mappings/atlasmapping-xml-attribute-ns.json, lib/modules/xml/core/src/main/java/io/atlasmap/xml/core/XmlFieldReader.java
=> fix: Cannot read namespaced XML attribute

ui/packages/atlasmap-core/src/utils/mapping-serializer.ts
=> fix: Persist XSD documents into xmlNameSpace within DataSource.

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasPreviewContext.java, lib/core/src/main/java/io/atlasmap/functions/ISEMPTY.java, lib/core/src/test/java/io/atlasmap/core/DefaultAtlasContextTest.java, lib/core/src/test/java/io/atlasmap/core/DefaultAtlasPreviewContextTest.java
=> fix: ISEMPTY NPE in preview mode

lib/core/src/main/java/io/atlasmap/core/BaseAtlasModule.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasPreviewContext.java, lib/core/src/test/java/io/atlasmap/core/DefaultAtlasPreviewContextTest.java
Fixes: https://github.com/atlasmap/atlasmap/issues/2590
https://issues.redhat.com/browse/ENTESB-15845
=> fix: Preview kicks out any field types

README.md, ui/packages/atlasmap-core/src/services/mapping-management.service.ts, ui/packages/atlasmap-core/src/utils/lookup-table-util.ts, ui/packages/atlasmap/src/Atlasmap/Atlasmap.tsx, ui/packages/atlasmap/src/Atlasmap/AtlasmapProvider.tsx, ui/packages/atlasmap/src/Atlasmap/dialogs/index.ts, ui/packages/atlasmap/src/Atlasmap/dialogs/useEditMappingEnumerationDialog.tsx, ui/packages/atlasmap/src/Atlasmap/useAtlasmapDialogs.tsx, ui/packages/atlasmap/src/Atlasmap/useSidebar.tsx, ui/packages/atlasmap/src/Atlasmap/utils/field.ts, ui/packages/atlasmap/src/Layout/MappingDetailsSidebar.stories.tsx, ui/packages/atlasmap/src/Layout/MappingDetailsSidebar.tsx, ui/packages/atlasmap/src/UI/dialogs/ConfirmationDialog.tsx, ui/packages/atlasmap/src/UI/dialogs/LookupTableDialog.tsx, ui/packages/atlasmap/src/UI/dialogs/index.ts, ui/packages/atlasmap/src/Views/MappingDetailsView.tsx
Fixes: #2589, #1508
Keeping #2401 open - JSON enum support needs more work.  WIll also add an additional issue to err if mapping is not 1-1
=> fix: Add lookup table support for enumeration mapping.

ui/packages/atlasmap-core/src/models/field-action.model.ts
Fixes: #2609
Just fixes the default value issue.  See comment in https://github.com/atlasmap/atlasmap/issues/2609#issuecomment-803075802
=> fix: Correct default value for number action fields.

ui/packages/atlasmap-core/src/utils/mapping-serializer.ts
=> fix: Correct processing of input field groups in ForEach mode

ui/packages/atlasmap/src/Atlasmap/toolbarItems.tsx, ui/packages/atlasmap/src/Atlasmap/useContextToolbar.tsx
=> fix: About has to move out of AtlasMap pulldown menu

lib/api/src/main/java/io/atlasmap/spi/AtlasInternalSession.java, lib/api/src/main/java/io/atlasmap/spi/AtlasModule.java, lib/core/src/main/java/io/atlasmap/core/AtlasUtil.java, lib/core/src/main/java/io/atlasmap/core/BaseAtlasModule.java, lib/core/src/main/java/io/atlasmap/core/ConstantModule.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasExpressionProcessor.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasFieldActionService.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasPreviewContext.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasSession.java, lib/core/src/main/java/io/atlasmap/core/PropertyModule.java, lib/core/src/test/java/io/atlasmap/core/DefaultAtlasContextFactoryTest.java, lib/modules/csv/core/src/main/java/io/atlasmap/csv/core/CsvFieldReader.java, lib/modules/csv/module/src/main/java/io/atlasmap/csv/module/CsvModule.java, lib/modules/java/core/src/main/java/io/atlasmap/java/core/JavaFieldReader.java, lib/modules/java/core/src/main/java/io/atlasmap/java/core/TargetValueConverter.java, lib/modules/java/module/src/main/java/io/atlasmap/java/module/JavaModule.java, lib/modules/json/core/src/main/java/io/atlasmap/json/core/JsonFieldReader.java, lib/modules/json/module/src/main/java/io/atlasmap/json/module/JsonModule.java, lib/modules/xml/core/src/main/java/io/atlasmap/xml/core/XmlFieldReader.java, lib/modules/xml/module/src/main/java/io/atlasmap/xml/module/XmlModule.java
=> fix: Set Document name for constant and property

ui/packages/atlasmap-core/src/common/config.types.ts
=> fix: Use String for default constant/property type

lib/core/src/main/java/io/atlasmap/core/BaseAtlasModule.java, lib/itests/core/src/test/java/io/atlasmap/itests/core/JsonXmlEnumTest.java, lib/itests/core/src/test/resources/mappings/atlasmapping-json-xml-enum.json, lib/modules/json/core/src/main/java/io/atlasmap/json/core/JsonFieldReader.java, lib/modules/json/module/src/main/java/io/atlasmap/json/module/JsonModule.java, lib/modules/xml/core/src/main/java/io/atlasmap/xml/core/XmlFieldReader.java, lib/modules/xml/core/src/main/java/io/atlasmap/xml/inspect/XmlSchemaInspector.java, lib/modules/xml/core/src/test/java/io/atlasmap/xml/inspect/XmlSchemaInspectionTest.java, lib/modules/xml/core/src/test/resources/inspect/complex-schema.xsd, lib/modules/xml/model/src/main/java/io/atlasmap/xml/v2/XmlEnumField.java, lib/modules/xml/module/src/main/java/io/atlasmap/xml/module/XmlModule.java, ui/test-resources/xml/schema/XMLSchemaSource.xml
Fixes: #2638
feat: Add enum support for XML schema inspection
Fixes: #2603
=> fix: JSON/XML enum doesn't map at runtime

ui/packages/atlasmap/src/Views/ColumnMapperView/Columns/TreeItemFieldAndNodeRefsAndDnD.tsx
=> fix: Use ENUM for type of enumerations when show types is enabled.

lib/modules/json/core/src/main/java/io/atlasmap/json/inspect/JsonSchemaInspector.java, lib/modules/json/core/src/test/resources/inspect/schema/card-inline.json
=> feat: JSON schema: support specifying an array for field type

docs/src/main/asciidoc/developer-guide/openapi/core/index.adoc, docs/src/main/asciidoc/developer-guide/openapi/csv/index.adoc, docs/src/main/asciidoc/developer-guide/openapi/dfdl/index.adoc, docs/src/main/asciidoc/developer-guide/openapi/java/index.adoc, docs/src/main/asciidoc/developer-guide/openapi/json/index.adoc, docs/src/main/asciidoc/developer-guide/openapi/xml/index.adoc, lib/model/src/main/java/io/atlasmap/v2/FieldStatus.java, lib/modules/java/core/src/main/java/io/atlasmap/java/inspect/ClassInspectionService.java, lib/modules/java/model/src/main/java/io/atlasmap/java/v2/ClassInspectionRequest.java, lib/modules/java/model/src/test/java/io/atlasmap/java/v2/BaseMarshallerTest.java, lib/modules/java/service/src/main/java/io/atlasmap/java/service/JavaService.java, lib/modules/json/model/src/main/java/io/atlasmap/json/v2/JsonInspectionRequest.java, lib/modules/xml/core/src/main/java/io/atlasmap/xml/inspect/XmlSchemaInspector.java, lib/modules/xml/model/src/main/java/io/atlasmap/xml/v2/XmlInspectionRequest.java, ui/packages/atlasmap-core/src/models/config.model.ts, ui/packages/atlasmap-core/src/services/document-management.service.ts
=> fix: Use Conscious Language

ui/packages/atlasmap/src/Atlasmap/AtlasmapProvider.tsx, ui/packages/atlasmap/src/Atlasmap/utils/field.ts
=> fix: Correct erroneous error diagnostic when existing mapping is active.

ui/packages/atlasmap/src/Atlasmap/useContextToolbar.tsx
=> fix: Flip the default for show types.

standalone/src/test/java/io/atlasmap/standalone/E2ETest.java
Fixes: #2667
No idea why it didn't fail at first place.
=> fix: E2ETest failure only on CircleCI

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasPreviewContext.java, lib/core/src/test/java/io/atlasmap/core/DefaultAtlasPreviewContextTest.java, lib/service/src/test/java/io/atlasmap/service/AtlasServiceTest.java, lib/service/src/test/resources/mappings/process-mapping-request.json
=> fix: preview fails to populate collection target value

ui/packages/atlasmap-core/src/services/mapping-management.service.ts, ui/packages/atlasmap-core/src/utils/mapping-serializer.ts
=> fix: Correct issue with collection mappings.

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasPreviewContext.java
=> fix: Change skipping empty source WARN to INFO

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasContext.java, lib/itests/core/src/test/java/io/atlasmap/itests/core/issue/ENTESB16270Test.java, lib/itests/core/src/test/resources/data/issue/entesb-16270-source.json, lib/itests/core/src/test/resources/mappings/issue/entesb-16270-mapping.json
=> fix: Regression: for each mapping (collection-collection) doesn't work

docs/src/main/asciidoc/developer-guide/openapi/core/index.adoc, lib/service/src/main/java/io/atlasmap/service/AtlasLibraryLoader.java, lib/service/src/main/java/io/atlasmap/service/AtlasService.java, lib/service/src/test/java/io/atlasmap/service/AtlasServiceTest.java, lib/service/src/test/resources/upload/io/atlasmap/service/my/MyCustomMappingBuilder.java
Fixes: #2680
#2678 has to be merged before this one.
=> feat: Add REST endpoint to retrieve AtlasMappingBuilder impl classes

ui/packages/atlasmap-core/src/services/mapping-management.service.ts, ui/packages/atlasmap-core/src/utils/mapping-serializer.ts
Fixes: #2664
Also corrected a react-dom issue setting value to null - now set it to an empty string.
=> fix: Correct non-preview mode after preview mode.

lib/api/src/main/java/io/atlasmap/api/AtlasMappingBuilder.java, lib/core/src/main/java/io/atlasmap/builder/DefaultAtlasMappingBuilder.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasCustomMappingProcessor.java, lib/core/src/test/java/io/atlasmap/builder/DefaultAtlasMappingBuilderTest.java, lib/itests/core/src/test/java/io/atlasmap/itests/core/MappingBuilderTest.java
=> fix: Catch exception from processMapping and add audit

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasCompoundClassLoader.java
=> Reproducible iteration order in DefaultAtlasCompoundClassLoader #2702

.circleci/config.yml
=> fix: Cache node_modules in CircleCI build

camel/src/main/java/org/apache/camel/component/atlasmap/AtlasComponent.java, camel/src/main/java/org/apache/camel/component/atlasmap/AtlasEndpoint.java
Fixes: #2708 
Moved propertiesFile parameter from endpoint to component
=> fix: Backport CAMEL-16556 to the Camel2 camel-atlasmap component

lib/core/src/main/java/io/atlasmap/core/ADMArchiveHandler.java, lib/model/src/main/java/io/atlasmap/v2/DataSourceMetadata.java, standalone/src/test/java/io/atlasmap/standalone/E2ETest.java
=> DataSourceMetadata: change isSource getter and setter names fixes #2722

ui/packages/atlasmap/src/UI/dialogs/AboutDialog.tsx
=> fix: Remove version mismatch warning

ui/packages/atlasmap/src/Atlasmap/dialogs/useImportDocumentDialog.tsx, ui/packages/atlasmap/src/UI/dialogs/ParametersDialog.stories.tsx, ui/packages/atlasmap/src/UI/dialogs/ParametersDialog.tsx
=> fix: Correct CSV dialog.

ui/packages/atlasmap/package.json, ui/yarn.lock
=> chore: Remove tslib dep

ui/packages/atlasmap/package.json, ui/yarn.lock
=> chore: Remove fork-ts-checker-webpack-plugin dep

ui/packages/atlasmap-standalone/package.json, ui/yarn.lock
=> chore: Remove @types/node dep

.gitignore, camel/pom.xml, lib/core/src/test/java/io/atlasmap/core/DefaultAtlasPropertyStrategyTest.java, lib/expression/src/main/java/io/atlasmap/expression/internal/BooleanExpression.java, lib/expression/src/main/java/io/atlasmap/expression/internal/LRUCache.java, lib/modules/java/core/src/main/java/io/atlasmap/java/core/JdkPackages.java, lib/modules/json/core/src/main/java/io/atlasmap/json/inspect/JsonInspectionException.java, lib/modules/xml/core/src/main/java/io/atlasmap/xml/core/AtlasXmlNamespaceContext.java, lib/modules/xml/core/src/main/java/io/atlasmap/xml/inspect/XmlInspectionException.java, parent/pom.xml
Fixes: #1127
CircleCI will keep using java8 container and added a GitHub Action building with java11, both should run as PR checks.
=> fix: Support building/running with java11

pom.xml
=> fix: license maven plugin prevents module build

ui/packages/atlasmap-core/package.json, ui/packages/atlasmap/package.json, ui/yarn.lock
=> chore: remove ts-loader dep

.github/workflows/experimental-build.yml, .github/workflows/supported-build.yml, docs/pom-javadoc.xml, lib/modules/xml/xsom/src/com/sun/xml/xsom/XSAnnotation.java, lib/modules/xml/xsom/src/com/sun/xml/xsom/XSComponent.java, lib/modules/xml/xsom/src/com/sun/xml/xsom/XSElementDecl.java, lib/modules/xml/xsom/src/com/sun/xml/xsom/XSSchema.java, lib/modules/xml/xsom/src/com/sun/xml/xsom/XSTerm.java, lib/modules/xml/xsom/src/com/sun/xml/xsom/XSType.java, lib/modules/xml/xsom/src/com/sun/xml/xsom/impl/parser/state/NGCCRuntime.java, lib/modules/xml/xsom/src/com/sun/xml/xsom/impl/scd/Iterators.java, lib/modules/xml/xsom/src/com/sun/xml/xsom/impl/scd/ParseException.java, lib/modules/xml/xsom/src/com/sun/xml/xsom/impl/util/SchemaTreeTraverser.java, lib/modules/xml/xsom/src/com/sun/xml/xsom/parser/AnnotationParser.java, lib/modules/xml/xsom/src/com/sun/xml/xsom/parser/SchemaDocument.java, lib/modules/xml/xsom/src/com/sun/xml/xsom/parser/XSOMParser.java, lib/modules/xml/xsom/src/com/sun/xml/xsom/util/DomAnnotationParserFactory.java, parent/pom.xml, pom.xml
=> fix: newer maven javadoc plugin

ui/packages/atlasmap-core/src/utils/mapping-serializer.spec.ts, ui/packages/atlasmap-core/src/utils/mapping-util.ts, ui/test-resources/mapping/atlasmapping-enum-lookup-table.json
=> fix: Augment mapping serializer tests with enum examples

ui/packages/atlasmap-standalone/src/setupProxy.js
=> fix: Yarn start for standalone UI fails

ui/packages/atlasmap/src/UI/dialogs/LookupTableDialog.module.css
=> fix: Tweeked the lookup table/enum mapper dialog post PF4 update.

ui/packages/atlasmap/src/UI/ExpressionFieldSearch.module.css, ui/packages/atlasmap/src/UI/ExpressionFieldSearch.tsx
=> fix: Correct css for expression field candidate menu

ui/packages/atlasmap/src/UI/MappingFields.module.css
=> fix: Correct font size for mapping details panel titles.

ui/packages/atlasmap-core/src/services/mapping-management.service.spec.ts, ui/packages/atlasmap-core/src/services/mapping-management.service.ts, ui/packages/atlasmap-core/src/utils/mapping-serializer.spec.ts, ui/packages/atlasmap-core/tsconfig.json, ui/packages/atlasmap/tsconfig.json, ui/test-resources/mapping/atlasmapping-mock.json
=> fix: UI UT for mapping-management.service.ts

ui/packages/atlasmap-core/package.json, ui/packages/atlasmap-standalone/package.json, ui/packages/atlasmap/package.json, ui/packages/atlasmap/src/Atlasmap/dialogs/useConstantDialog.tsx, ui/packages/atlasmap/src/Atlasmap/dialogs/useNamespaceDialog.tsx, ui/packages/atlasmap/src/Atlasmap/dialogs/usePropertyDialog.tsx, ui/packages/atlasmap/src/UI/Canvas/NodesArc.tsx, ui/packages/atlasmap/src/Views/SourceMappingTargetView.stories.tsx, ui/packages/atlasmap/src/Views/SourceMappingTargetView.tsx, ui/packages/atlasmap/src/Views/SourceTargetView.stories.tsx, ui/yarn.lock
=> chore: UI: Update prettier from 2.3.0 to 2.3.1

ui/packages/atlasmap/src/UI/dialogs/ParametersDialog.tsx
=> fix: Correct CSV parameters dialog.

.github/workflows/experimental-build.yml, .github/workflows/supported-build.yml
=> chore: Enable E2ETest in GH action

.github/workflows/experimental-build.yml, .github/workflows/supported-build.yml
=> chore: Enable maven/node_modules cache in GH actions

.github/workflows/chromatic.yml, README.md
changed my mind, shouldn't be a big problem having chromatic project token public.
=> chore: enable chromatic PR checks (#2913)

ui/packages/atlasmap-core/src/utils/mapping-serializer.spec.ts, ui/test-resources/mapping/atlasmapping-csv.json
=> fix: Add a CSV serializer test.

ui/packages/atlasmap-core/src/models/transition.model.ts, ui/packages/atlasmap-core/src/services/mapping-management.service.ts, ui/packages/atlasmap-core/src/utils/mapping-serializer.ts
=> fix: UI: Add expression transition mode

ui/packages/atlasmap-core/src/services/initialization.service.spec.ts
=> chore: UI UT for initialization-service.ts

ui/packages/atlasmap-core/src/services/document-management.service.spec.ts
=> chore: UI UT for document-management.service.ts

ui/packages/atlasmap/src/Views/SourceTargetView.spec.tsx, ui/packages/atlasmap/src/Views/SourceTargetView.stories.tsx
Also limited preview input box to active mapping mapped field
=> chore: Add UT for SourceTargetView (#2694)

ui/packages/atlasmap-core/src/models/expression.model.ts, ui/packages/atlasmap-core/src/models/transition.model.ts, ui/packages/atlasmap/src/Atlasmap/utils/ui.ts, ui/packages/atlasmap/src/UI/ExpressionContent.tsx
=> fix: Correct expression box delete key/ backspace over field/text nodes.

lib/modules/java/core/src/main/java/io/atlasmap/java/inspect/ClassInspectionService.java, lib/modules/java/service/pom.xml, lib/modules/java/service/src/test/java/io/atlasmap/java/service/JavaServiceTest.java, ui/packages/atlasmap-core/src/models/document-definition.model.ts
Fixes: #3030
Remove double slash from Java inspection field path
Fixes: #3051
=> fix: UI: Remove field path recalculation

ui/packages/atlasmap-core/src/contracts/documents/csv.ts, ui/packages/atlasmap/src/Atlasmap/dialogs/useImportDocumentDialog.tsx, ui/packages/atlasmap/src/Atlasmap/useAtlasmapDialogs.tsx
=> fix: Refactor getCsvParameterOptions out of its current class.

ui/packages/atlasmap/src/UI/MappingTransformation.spec.tsx, ui/packages/atlasmap/src/UI/MappingTransformation.stories.tsx, ui/packages/atlasmap/src/UI/MappingTransformation.tsx
=> fix: "User defined" separator not working

lib/core/src/main/java/io/atlasmap/actions/StringComplexFieldActions.java, lib/core/src/test/java/io/atlasmap/actions/StringComplexFieldActionsTest.java
=> fix: Split: Some characters doesn't work as a delimiter

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasPreviewContext.java, lib/core/src/test/java/io/atlasmap/core/DefaultAtlasPreviewContextTest.java, lib/service/src/test/java/io/atlasmap/service/AtlasServiceTest.java, lib/service/src/test/resources/mappings/process-mapping-request-3064.json
=> fix: Preview creates erroneous duplicated collection source field

ui/packages/atlasmap-core/src/contracts/common.ts, ui/packages/atlasmap-core/src/services/initialization.service.spec.ts, ui/packages/atlasmap-core/src/services/initialization.service.ts
=> fix: Runtime version is empty in About dialog

lib/core/src/main/java/io/atlasmap/actions/StringComplexFieldActions.java, lib/core/src/test/java/io/atlasmap/actions/StringComplexFieldActionsTest.java, lib/model/src/main/java/io/atlasmap/v2/Split.java, standalone/src/test/java/io/atlasmap/standalone/E2ETest.java, ui/packages/atlasmap-core/src/contracts/field-action.ts, ui/packages/atlasmap-core/src/models/transition.model.ts, ui/packages/atlasmap-core/src/services/field-action.service.ts, ui/packages/atlasmap-core/src/utils/mapping-serializer.spec.ts, ui/packages/atlasmap/src/UI/MappingTransformation.spec.tsx, ui/packages/atlasmap/src/UI/MappingTransformation.stories.tsx, ui/packages/atlasmap/src/UI/MappingTransformation.tsx, ui/packages/atlasmap/src/impl/useSidebar.tsx, ui/packages/atlasmap/src/impl/utils/ui.ts, ui/test-resources/mapping/atlasmapping-split-collapse.json
=> fix: Split: Support collapsing repeating delimiter

.github/workflows/supported-build.yml, lib/core/src/main/java/io/atlasmap/core/ADMArchiveHandler.java
=> fix: Fails to load a jar from adm on Windows

.github/workflows/chromatic.yml
=> fix: Skip chromatic upload if there's no change under ui dir

lib/itests/core/src/test/java/io/atlasmap/itests/core/NestedCollectionJavaTest.java, lib/itests/reference-mappings/src/test/java/io/atlasmap/itests/reference/java_to_java/JavaJavaCollectionTest.java, lib/itests/reference-mappings/src/test/java/io/atlasmap/itests/reference/json_to_json/JsonJsonCollectionTest.java, lib/itests/reference-mappings/src/test/java/io/atlasmap/itests/reference/xml_to_xml/XmlXmlCollectionTest.java, lib/itests/reference-mappings/src/test/resources/javaToJava/atlasmapping-collection-list-empty.json, lib/itests/reference-mappings/src/test/resources/jsonToJson/atlas-json-collection-list-empty.json, lib/itests/reference-mappings/src/test/resources/jsonToJson/atlasmapping-collection-list-empty.json, lib/itests/reference-mappings/src/test/resources/xmlToXml/atlas-xml-collection-list-empty.xml, lib/itests/reference-mappings/src/test/resources/xmlToXml/atlasmapping-collection-list-empty.json, lib/model/src/main/java/io/atlasmap/v2/AtlasModelFactory.java, lib/modules/java/core/src/main/java/io/atlasmap/java/core/JavaFieldReader.java, lib/modules/java/core/src/test/java/io/atlasmap/java/core/JavaFieldReaderTest.java
=> fix: Do not create an empty collection item if there's nothing to map

lib/modules/json/core/src/test/java/io/atlasmap/json/core/JsonFieldWriterTest.java, standalone/src/test/java/io/atlasmap/standalone/E2ETest.java
Fixes: #3128
It was just the test case broken
=> fix: Fix test

ui/packages/atlasmap/src/UI/Tree/TreeGroup.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/ColumnMapperView.spec.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/ColumnMapperView.stories.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Columns/TargetsColumn.tsx
=> fix: Preview: target property is editable and doesn't display the value

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasPreviewContext.java, lib/core/src/test/java/io/atlasmap/core/DefaultAtlasExpressionProcessorTest.java, lib/core/src/test/java/io/atlasmap/core/DefaultAtlasPreviewContextTest.java, lib/itests/reference-mappings/src/test/java/io/atlasmap/itests/reference/java_to_java/JavaJavaFlatMappingTest.java, lib/itests/reference-mappings/src/test/resources/javaToJava/atlasmapping-flatprimitive-expression.json
=> fix: Preview: boolean is handled wrong in expression

lib/modules/java/core/src/main/java/io/atlasmap/java/inspect/ClassInspectionService.java, lib/modules/java/core/src/test/java/io/atlasmap/java/inspect/ClassInspectionServiceTest.java, ui/packages/atlasmap-core/src/models/document-definition.model.ts, ui/packages/atlasmap-core/src/services/document-management.service.spec.ts
=> fix: Wrong path for Java collection field

lib/api/src/main/java/io/atlasmap/api/AtlasMappingBuilder.java, lib/core/src/main/java/io/atlasmap/builder/AtlasField.java, lib/core/src/main/java/io/atlasmap/builder/DefaultAtlasMappingBuilder.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasCustomMappingProcessor.java, lib/core/src/test/java/io/atlasmap/builder/DefaultAtlasMappingBuilderTest.java
=> fix: Add write() directly on DefaultAtlasMappingBuilder

ui/packages/atlasmap/src/impl/utils/field.ts
Fixes: #3213
I'll add an UT later with those routines migrated to document-management.service (#2883)
=> fix: Fail to create constant field

ui/packages/atlasmap-core/src/services/document-management.service.spec.ts, ui/packages/atlasmap-core/src/services/document-management.service.ts, ui/packages/atlasmap/src/impl/utils/field.ts
Also add UTs for #3213
fix: editConstant() doesn't update the path, makes it out of sync
Fixes: #3218
=> fix: Move constant/property handling routine to @atlasmap/core (#2883)

.github/workflows/chromatic.yml
Run only if
* Not a dependabot PRs
* Checked workflow succeeded
for both of master push and forked PRs.
=> fix: Better condition for chromatic upload

ui/packages/atlasmap/package.json, ui/yarn.lock
Fixes: #3277
It turned out #3260 broke it silently
=> fix: UI lint fails

ui/packages/atlasmap/src/UI/Loading.tsx
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
Fixes: #
=> Avoid duplicated import in Loading.tsx

release.sh
=> fix: Fix runtime version in Docker image

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasCompoundClassLoader.java
=> fix: Avoid null being added as a class loader

camel/pom.xml
=> fix: Do not include DFDL module by default

lib/core/src/main/java/io/atlasmap/core/DefaultAtlasCompoundClassLoader.java
=> fix: Use TCCL as a fallback in DefaultAtlasCompoundClassLoader

ui/packages/atlasmap/src/Views/ColumnMapperView/Actions/CaptureDocumentIDAction.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Actions/index.ts, ui/packages/atlasmap/src/Views/ColumnMapperView/ColumnMapperView.stories.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Columns/SourcesColumn.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Columns/TargetsColumn.tsx, ui/packages/atlasmap/src/Views/SourceTargetView.stories.tsx, ui/packages/atlasmap/src/impl/Atlasmap.tsx, ui/packages/atlasmap/src/impl/dialogs/index.ts, ui/packages/atlasmap/src/impl/dialogs/useCaptureDocumentIDToast.tsx, ui/packages/atlasmap/src/impl/useAtlasmapDialogs.tsx
=> fix: Change "extended file name" in a tooltip to "Document ID"

ui/packages/atlasmap-core/src/services/mapping-management.service.spec.ts, ui/packages/atlasmap-core/src/services/mapping-management.service.ts
=> fix: D&D doesn't create a new mapping when there's a selected mapping

lib/modules/xml/core/src/main/java/io/atlasmap/xml/inspect/XmlSchemaInspector.java, lib/modules/xml/core/src/test/java/io/atlasmap/xml/inspect/XmlSchemaInspectionMultipleNamespacesTest.java, lib/modules/xml/core/src/test/java/io/atlasmap/xml/inspect/XmlSchemaInspectionTest.java
=> fix: No collection suffix in the path for XML field

ui/packages/atlasmap-core/src/services/file-management.service.spec.ts, ui/packages/atlasmap-core/src/services/file-management.service.ts
Fetch field actions after importing user JAR file.
Fixes: #3482
=> fix: Fetch field actions after importing user JAR file.

ui/packages/atlasmap/src/impl/utils/document.ts, ui/packages/atlasmap/src/impl/utils/toolbar.ts
Generate an info message when JAR file import is complete.
Fixes: #3483
=> fix: Generate an info message when JAR file import is complete.

ui/packages/atlasmap-core/package.json, ui/packages/atlasmap-standalone/package.json, ui/packages/atlasmap/package.json, ui/packages/atlasmap/src/Layout/MappingDetailsSidebar.tsx, ui/packages/atlasmap/src/UI/ColumnMapper/SearchableColumnHeader.tsx, ui/packages/atlasmap/src/UI/ConditionalExpressionInput.tsx, ui/packages/atlasmap/src/UI/DocumentFieldPreview.tsx, ui/packages/atlasmap/src/UI/DocumentFieldPreviewResults.tsx, ui/packages/atlasmap/src/UI/ExpressionEnumSelect.tsx, ui/packages/atlasmap/src/UI/ExpressionFieldSearch.tsx, ui/packages/atlasmap/src/UI/MappingTransformation.tsx, ui/packages/atlasmap/src/UI/dialogs/ChangeDocumentNameDialog.tsx, ui/packages/atlasmap/src/UI/dialogs/ConfirmationDialog.tsx, ui/packages/atlasmap/src/UI/dialogs/ExportCatalogDialog.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Actions/CaptureDocumentIDAction.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Actions/ChangeDocumentNameAction.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Actions/DeleteDocumentAction.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Actions/DeleteMappingAction.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Actions/EditCSVParamsAction.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Actions/EnableJavaClassAction.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Columns/TreeGroupAndNodeRefsAndDnD.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Columns/TreeItemFieldAndNodeRefsAndDnD.tsx, ui/packages/atlasmap/src/Views/MappingDetailsView.tsx, ui/packages/atlasmap/src/impl/toolbarItems.tsx, ui/yarn.lock
=> chore: Update to prettier 2.5.0

lib/itests/core/src/test/java/io/atlasmap/itests/core/issue/AtlasMap3549Test.java, lib/itests/core/src/test/resources/data/issue/atlasmap-3549-source1.json, lib/itests/core/src/test/resources/data/issue/atlasmap-3549-source2.json, lib/itests/core/src/test/resources/mappings/issue/atlasmap-3549-mapping.json, lib/modules/xml/core/src/main/java/io/atlasmap/xml/core/XmlFieldWriter.java
=> fix: NPE when a XML target collection to be written is empty

ui/packages/atlasmap-core/src/services/initialization.service.ts
=> fix: Document type 'Java' is not supported for inspection

ui/packages/atlasmap/src/UI/Canvas/3.NodesArc.stories.mdx, ui/packages/atlasmap/src/UI/Canvas/NodesArc.stories.tsx
=> fix: Let chromatic ignore NodesArc story

.github/workflows/experimental-build.yml, .github/workflows/main.yml, .github/workflows/post-release.yml, .github/workflows/supported-build.yml, lib/modules/xml/xsom/src/com/sun/xml/xsom/impl/parser/NGCCRuntimeEx.java
=> chore: Add Java17 build, remove Java8 build

lib/modules/json/core/src/main/java/io/atlasmap/json/inspect/JsonSchemaInspector.java, lib/modules/json/core/src/test/java/io/atlasmap/json/inspect/JsonSchemaInspectorTest.java, lib/modules/json/core/src/test/resources/inspect/schema/recursive.json
=> fix: StackOverflowError on a recursive JSON object inspection

camel/pom.xml, parent/pom.xml
=> fix: Remove jaxb dependency

lib/core/src/main/java/io/atlasmap/core/AtlasUtil.java, ui/packages/atlasmap-core/src/services/document-management.service.ts, ui/packages/atlasmap/src/impl/utils/document.ts
=> fix: UI: Clean up error handling when failing file inspection.

ui/packages/atlasmap/src/UI/DocumentActions.tsx, ui/packages/atlasmap/src/Views/ColumnMapperView/Actions/DeleteDocumentAction.tsx
=> fix: UI: Correct remove document icon tool tip.

ui/packages/atlasmap/package.json
=> should make @atlasmap/atlasmap consistent with @atlasmap/core version？

lib/core/src/main/java/io/atlasmap/converters/EnumConverter.java, lib/core/src/main/java/io/atlasmap/converters/StringConverter.java, lib/core/src/main/java/io/atlasmap/core/DefaultAtlasConversionService.java, lib/core/src/main/resources/META-INF/services/io.atlasmap.spi.AtlasConverter, lib/itests/reference-mappings/src/test/java/io/atlasmap/itests/reference/java_to_java/JavaJavaComplexTest.java, lib/itests/reference-mappings/src/test/resources/javaToJava/atlasmapping-enum.json, lib/model/src/main/java/io/atlasmap/v2/FieldType.java, lib/modules/java/core/src/main/java/io/atlasmap/java/core/TargetValueConverter.java, lib/modules/java/model/src/main/java/io/atlasmap/java/v2/JavaEnumField.java
=> feat: Map a Java String to Java Enum [RFE]

ui/packages/atlasmap-core/src/services/initialization.service.spec.ts, ui/packages/atlasmap-core/src/services/mapping-preview.service.ts, ui/packages/atlasmap-core/src/utils/mapping-serializer.ts
=> fix: UI: Correct REST Jest testing async issue.

ui/packages/atlasmap/src/UI/ExpressionContent.tsx
=> fix: UI: Correct BS/DEL in conditional expression window.

lib/service/pom.xml, lib/service/src/main/java/io/atlasmap/service/lsp/AtlasExpressionLSPServerEndpointConfig.java, lib/service/src/main/java/io/atlasmap/service/lsp/AtlasExpressionLSPService.java, lib/service/src/main/java/io/atlasmap/service/lsp/AtlasExpressionLanguageServer.java, lib/service/src/main/java/io/atlasmap/service/lsp/AtlasExpressionTextDocumentService.java, lib/service/src/main/java/io/atlasmap/service/lsp/AtlasExpressionWorkspaceService.java, parent/pom.xml, standalone/pom.xml, standalone/src/main/java/io/atlasmap/standalone/WebSocketConfiguration.java, standalone/src/test/java/io/atlasmap/standalone/E2ETest.java
Checkpoint: Established LSP server websocket endpoint and mocked up the server impl. E2ETest tests the websocket connection and initialization.
TODO:
* Implement LSP server logic for the conditional mapping expression syntax support
* Establish function metadata registry so that the LSP function completion can leverage it
* Integrate with server side field search (#603) for the field reference in expression
* Connect from UI, probably with using https://github.com/TypeFox/monaco-languageclient
=> feat: LSP server for conditional mapping expression (#3138)

camel/pom.xml
=> chore: build error in camel-atlasmap

camel/pom.xml
=> chore: Build error with java17, jaxb confliction

ui/packages/atlasmap/src/Views/ColumnMapperView/Actions/ImportAction.tsx
Fixes: #3781
This fixes the current critical issue with loading files into the src/tgt panels.  It still uses useFilePicker because FilePicker does not limit the files shown in the select menu.  As it turns out neither does this fix.  I'll create a new bug to track limiting files to choose from.
=> fix: UI: Correct useFilePicker file access post render.

ui/packages/atlasmap-core/src/services/mapping-expression.service.ts
=> fix: UI: Extend expr search element max.

lib/service/src/main/java/io/atlasmap/service/MappingService.java, ui/packages/atlasmap-core/src/services/file-management.service.ts, ui/packages/atlasmap-core/src/services/initialization.service.ts, ui/packages/atlasmap-core/src/services/mapping-management.service.spec.ts, ui/packages/atlasmap-core/src/services/mapping-management.service.ts, ui/yarn.lock
=> fix: UI: Refactored removeAllMappings()

docs/src/main/asciidoc/developer-guide/openapi/core/index.adoc, lib/service/src/main/java/io/atlasmap/service/MappingService.java, ui/packages/atlasmap-core/src/services/mapping-management.service.spec.ts, ui/packages/atlasmap-core/src/services/mapping-management.service.ts, ui/packages/atlasmap/src/impl/dialogs/useDeleteMappingDialog.tsx, ui/packages/atlasmap/src/impl/utils/document.ts, ui/packages/atlasmap/src/impl/utils/ui.ts
=> fix: UI: Refactored removeMapping() - now uses backend pull

README.md
update README to have correct path for UI build
=> update README to have correct path for UI build

.github/workflows/experimental-build.yml, .github/workflows/supported-build.yml, atlasmap-maven-plugin/src/test/resources/fhir-patient.xsd, ui/test-resources/inspected/atlasmap-inspection-fhir-patient.json, ui/test-resources/inspected/atlasmap-inspection-fhir-rafal-170.json
=> fix: Remove git LFS usage

lib/service/src/main/java/io/atlasmap/service/AtlasService.java, lib/service/src/test/java/io/atlasmap/service/AtlasServiceTest.java
=> fix: Correct reset - NPE in backend service.

ui/packages/atlasmap-core/src/contracts/common.ts, ui/packages/atlasmap-core/src/models/inspect/csv-inspection.model.ts, ui/packages/atlasmap-core/src/models/inspect/java-inspection.model.ts, ui/packages/atlasmap-core/src/models/inspect/json-inspection.model.ts, ui/packages/atlasmap-core/src/models/inspect/kafkaconnect-inspection.model.ts, ui/packages/atlasmap-core/src/models/inspect/xml-inspection.model.ts
=> fix: Correct UI hang by specifying document type.

ui/packages/atlasmap-core/src/services/document-management.service.ts
=> fix: DataSource URI disappears

ui/packages/atlasmap-core/src/services/initialization.service.ts, ui/packages/atlasmap-core/src/utils/mapping-serializer.ts, ui/packages/atlasmap-core/src/utils/mapping-util.ts
=> fix: XML Doc namespace duplicates

parent/pom.xml, standalone/src/test/java/io/atlasmap/standalone/E2ETest.java
=> Fuse 7.12 alignment

parent/pom.xml
=> [ENTESB-21332][ENTESB-20648] Upgrade to Spring Boot 2.7.12

parent/pom.xml
=> [ENTESB-22384][ENTESB-22385] Update to Logback 1.3.14

parent/pom.xml
=> [ENTESB-22698] Upgrade to Spring Framework 5.3.32

parent/pom.xml
=> [ENTESB-22790] Upgrade to Spring Framework 5.3.34
